### ISSUE TITLE
Can't execute «postMessage» on «DOMWindow»

### ISSUE THREAD

**Issue by sychov** [fastaddons/GroupSpeedDial#103]
**Describe the bug**
When I work with my Python's Django project HTTP development server on localhost, on every page I have got an error in console:

Не удалось выполнить «postMessage» над «DOMWindow»: указанный источник цели («https://group-speed-dial.fastaddons.com») не соответствует источнику окна получателя («http://localhost:8000»).

**Device info:**
 - operating system: Windows 10
 - Browser and version: Mozilla Firefox 95.0.2 (x64)
 - GroupSpeedDial version: 18.0

**Comment by fastaddons** [comment]
Oh, I think I know! I've forgot to remove localhost script injection I've used for testing the new server...
Thanks for reporting! I will release update now.

**Comment by fastaddons** [comment]
New version 18.1 has been released. 
To install it now, click "Check for updates" in the "about:addons" page in the gear icon menu.

Thanks again for reporting this!

**Comment by sychov** [comment]
Thanx! Everything works fine now.
