### ISSUE TITLE
18.2 caused problems with Facebook

### ISSUE THREAD

**Issue by Pizzapops** [fastaddons/GroupSpeedDial#106]
**Describe the bug**
Last evening Facebook was very unstable and would keep going to the **_Facebook has a Problem  ;-(_** page.

**Experienced Behavior**
After repeated tries to use Facebook with Vivaldi (main browser), I started experimenting with Firefox, Waterfox and Edge. They all exhibited the same Facebook problem. All had GSD installed. I tried Pale Moon 29.4.3 and Facebook worked. It was the only browser without GSD. I disabled GSD in Firefox 97 and Facebook worked. The same with Vivaldi 5.0. I have since tried it with Chrome 96 without GSD. Facebook fails but it could be that Vivaldi with GSD was open at the same time.

Vivaldi and GSD 18.2 seem to be working together fine. The Vivaldi side panel with GSD still works.

**Device info:**
 - operating system: Win 10
 - Browser and version: Many 
 - GroupSpeedDial version: 18.2

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
That sounds highly unlikely related to my addon :).

Facebook is slow and unstable for everyone in the whole world, that's simply the way the page works.
I really can't think of any reason why would a web-page, not related to my addon, where the addon script is not injected, would be affected. Also the network handlers my addon is using are only registered and applied inside the addon page in the iframe where thumbnails are created so there is no way a page loaded in a tab would be affected.

Please check the `about:processes` and `about:performance` to see if my addons is taking too much resources.

**Comment by Pizzapops** [comment]
I guess I should have reversed the title: **Facebook causing problems for 18.2**. 

FB must have made a fix. everything is back working. I will refrain from making rash judgements in the future.
