### ISSUE TITLE
Change Group Name or Delete Group

### ISSUE THREAD

**Issue by ToaKamate** [fastaddons/GroupSpeedDial#107]
Greetings,
I bought the Pro version a long time ago - couldn't live without this.  I've noticed that in later versions everything works off of the cloud dials instead of the actual FF add-on.  

Is there a way to change the name of a Group?  I also can not find a way to delete an entire group.  I've created a couple of groups for special projects and now can't get rid of them to free up space where the group names appear.

**Comment by fastaddons** [comment]
Hello,
The Cloud dials page is mean to be used on browsers where you can't install the addon. Like on tablets or phones.
So on desktop simply install addon and when you open new tab page, it should open your dials.
https://addons.mozilla.org/addon/groupspeeddial/?utm_source=home
https://chrome.google.com/webstore/detail/groupspeeddial/imfeikbeimbfpmgfkkmjekabdehiiajc

**Comment by ToaKamate** [comment]
I might have to reinstall it because it isn't working that way. If reinstall doesn't work, I'll send screenshots

On January 10, 2022 10:15:10 AM MST, "Juraj Mäsiar" ***@***.***> wrote:
>Hello,
>The Cloud dials page is mean to be used on browsers where you can't install the addon. Like on tablets or phones.
>So on desktop simply install addon and when you open new tab page, it should open your dials.
>https://addons.mozilla.org/addon/groupspeeddial/?utm_source=home
>https://chrome.google.com/webstore/detail/groupspeeddial/imfeikbeimbfpmgfkkmjekabdehiiajc
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/fastaddons/GroupSpeedDial/issues/107#issuecomment-1009145413
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ToaKamate** [comment]
Ok. I reinstalled and FF now goes to the add-on instead of cloud.  Before the add-on was there but there was no way too get FF to use it as home page or new tabs - it always went to cloud.

On January 10, 2022 10:15:10 AM MST, "Juraj Mäsiar" ***@***.***> wrote:
>Hello,
>The Cloud dials page is mean to be used on browsers where you can't install the addon. Like on tablets or phones.
>So on desktop simply install addon and when you open new tab page, it should open your dials.
>https://addons.mozilla.org/addon/groupspeeddial/?utm_source=home
>https://chrome.google.com/webstore/detail/groupspeeddial/imfeikbeimbfpmgfkkmjekabdehiiajc
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/fastaddons/GroupSpeedDial/issues/107#issuecomment-1009145413
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fastaddons** [comment]
Great, so you should be able to edit your groups / dials now.
I will close this issue now.
