### ISSUE TITLE
cannot add a website page to speed dial

### ISSUE THREAD

**Issue by dduran1210** [fastaddons/GroupSpeedDial#109]
I re-installed Chrome.   but now, when i right click on a website tab,  the link to add this
site to the speeddial page is no longer there.  

i re-installed Group Speeddial, but it STILL is not there.

this problem is in the latest version of Chrome.

nevermind,  I  found a different way to copy and paste ....more of a hassle than before.

**Comment by dduran1210** [comment]
nevermind, I found a different way to copy and paste ....more of a hassle than before.

**Comment by fastaddons** [comment]
Check also the Options page / Context menu tab. There you can enable / disable context menu items on pages.

**Comment by dduran1210** [comment]
fantastic....I should have read it better.  thank you for a GREAT program!

Dave
