### ISSUE TITLE
SYNCED but Logged Out .... lost many GROUPS

### ISSUE THREAD

**Issue by pulsar14** [fastaddons/GroupSpeedDial#111]
**Describe the bug**
Losted last added GROUPS with many dials (thanks!)

**Steps To Reproduce**
BEFORE:
ALL last added GROUPS availables.
I see the Cloud Icon white ... synced
I click on my user account and I see that I was logged out (WHAT ? )
So, I click on Log in --> Credentials --> User Logged

NOW:
- All the current GROUPS and DIALS changed with the last saved GROUPS on the Cloud
- ALL the last added GROUPS vanished
- Close and Reopen the Browser
- I can see my last opened new GROUP with their Dials ... but not responding (seems freezed, Yeh, because the Group not exists in the Groups bar!) 
- Cloud Icon start syncing with the Cloud ... this time user is really logged ... Speed Dials restored but ...
- the last GROUPS losted because not in saved in the Cloud

**Expected behavior**
How do you think?
Synching must be reviewed! If I'm offline and add some new Dials, then when I sync I expect that the new ones are saved (ADDED) not DELETED to the profile in the Cloud. How can I recover my last added Groups and their many Dials ?

**Device info:**
 - operating system:  win 10 pro last
 - Browser and version: Firefox 96.0.2
 - GroupSpeedDial version: put a version num in your About that is missing

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
Hello,
Each device has a local history of changes, you should be able to revert any recent change with a few clicks:
![_history](https://user-images.githubusercontent.com/55486931/150550739-5c2ea907-2b8d-4d49-b4d9-6561e260ccfd.png)

**Comment by pulsar14** [comment]
Hi,

Thanks a lot for your response!

Kind regards
