### ISSUE TITLE
Thumbnail images no longer generate or crop/scale

### ISSUE THREAD

**Issue by TrunerReisar** [fastaddons/GroupSpeedDial#114]
Running on Windows 10, Firefox 96.0.3.
I've noticed a couple of days ago that my dials weren't updating. I have about 30 of them, all set up to update at different times and/or intervals. I've started messing around with the dial settings and I've noticed that for most of the dials, the only thing that works is "Refresh Image in Background 2". This provides a brand new thumbnail for most of the dails and they refresh when they should. However, with this option, crop/scale stopped working and shows only a small section of the website in the dial. If I preview the crop/scale I've set up, it shows the dial I've last seen (which was about a week ago) instead of showing the newly generated one. Unsure where to go from here. I haven't changed any of my settings since setting the plugin up many moons ago, but Windows and Firefox update whenever they feel like.

**Comment by fastaddons** [comment]
Hello,
If you have a DPI scaling enabled on your monitor, then thumbnails may be shifted and over-zoomed.
This is new bug in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1751961
I will be releasing workaround soon in 18.3 version and it will be active for users of Firefox 97 which will be released the upcoming Tuesday.

The new version 18.3 fixes also few other auto-reload issues. So please let me know how it works after your Firefox updated to 97.

**Comment by TrunerReisar** [comment]
I have everything set to 100%, but I'll be reporting back once the updates drop, thank you for the quick answer. (:

**Comment by TrunerReisar** [comment]
Everything is working perfectly now. Thank you!
