### ISSUE TITLE
Dial for local html file is not opened

### ISSUE THREAD

**Issue by OneOf4400** [fastaddons/GroupSpeedDial#115]
**Describe the bug**
Dial to a local html file is don't opened.

**Steps To Reproduce**
Create new dial with "link to page" is "file:///D:/Books&Docs/Programming/C++/CPPREFERENCE/reference/en/Main_Page.html"

**Expected behavior**
Open and show contents of the local html file.

**Device info:**
 - operating system: Windows 7
 - Browser and version: Firefox Nightly 86.0a1 (2020-12-30) (64-bit)
 - GroupSpeedDial version: v18.2

**Comment by fastaddons** [comment]
See this comment for more info and solution:
https://github.com/fastaddons/GroupSpeedDial/issues/36#issuecomment-788283828

I will also write a wiki page that will explain it.

**Comment by OneOf4400** [comment]
> See this comment for more info and solution: [#36 (comment)](https://github.com/fastaddons/GroupSpeedDial/issues/36#issuecomment-788283828)
> 
> I will also write a wiki page that will explain it.
> 
> EDIT: Wiki page created: https://github.com/fastaddons/GroupSpeedDial/wiki/Opening-local-.HTML-pages-stored-on-drive

Thanks very much. In firefox added policy options to about:config is worked.
Im so glad to use my local web content in simple step.
