### ISSUE TITLE
Broken layout on Firefox on Windows 10

### ISSUE THREAD

**Issue by crashbone** [fastaddons/GroupSpeedDial#118]
**Describe the bug**
My speeddial is completely broken. Black screen, broken layout.

**Steps To Reproduce**
It happened after updating my firefox (it was probably a few years old)
I've also tried updating the plugin (again it was probably a few years old)

**Expected behavior**
It's not broken

**Device info:**
 - operating system: Windows 10
 - Browser and version: Firefox 97.0
 - GroupSpeedDial version: 18.3

**Additional info**
- Doing a right click and selecting edit group makes my speed-dials shown as black
- Doing a right click on top of the page and clicking add new group makes my layout shown, then clicking into my group makes them shown properly.
<p>
<image src="https://user-images.githubusercontent.com/18111628/153754164-6dbac254-6fc4-4e05-950b-c5b8eb00e854.png" width="250"/>
<image src="https://user-images.githubusercontent.com/18111628/153754342-e525b00c-a789-423e-adc3-5a663739b726.png" width="250"/>
<image src="https://user-images.githubusercontent.com/18111628/153754354-b029d32c-7b66-4599-a8a4-6398b10b0b51.png" width="250"/>
</p>

**Comment by fastaddons** [comment]
Hello,
There is some issue in Firefox, I've seen this many times, the storage gets corrupted when Firefox updates over many versions.
First, make sure you have a backup if needed.
To fix this, you need to uninstall the addon, then restart Firefox or whole PC and then install it back - after installing it should be completely empty and all databases should be recreated and working again.

Also could you please try to visit this storage test page?
https://firefox-storage-test.glitch.me/
(the test takes about 10 seconds and you should see "Storage is working." message)

**Comment by crashbone** [comment]
**Overview:**
Storage is working. This is your first visit or all storage was automatically cleared.

**Specific Subsystem Statuses:**

LocalStorage
- Good: Totally Working. (fullyOperational)

QuotaManager
- Good: Totally Working. (fullyOperational)

IndexedDB
- Good: Totally Working. (fullyOperational)

Cache API
- Good: Totally Working. (fullyOperational)

```
Debug Info:
{
  "v": 1,
  "curVersion": 97,
  "prevVersion": 0,
  "ls": {},
  "qm": {
    "lastWorkedIn": 97
  },
  "idb": {
    "persistentCreatedIn": 97,
    "persistentLastOpenedIn": 97,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 97,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 97
  }
}
```

At first glance to your message, I was worried if I have to clean my browse data (history, cookies, etc.). But it was not needed.

It's solved by

1. Uninstall GroupSpeedDial
2. Restart firefox GroupSpeedDial
3. Reinstall GroupSpeedDial

thank you 👍

**Comment by crashbone** [comment]
This error re-occured today, looking for better solution since repeating these steps a few times in a weeks is not a real solution.

- Firefox updates are disabled
- Groupspeeddial updates are disabled

ℹ️ https://firefox-storage-test.glitch.me still says my storage is working properly.

**Comment by crashbone** [comment]
Unfortunately, I don't see any error message and I don't use and software that could mess up with my browser files or caches like CCleaner.

I repeated the steps once again, it didn't happened for 18 days atm. I just hope it doesn't happen 😄
