### ISSUE TITLE
backup file to readable format 

### ISSUE THREAD

**Issue by trinib** [fastaddons/GroupSpeedDial#119]
hello your addon works great .. but can the backup file be convert this to a readable format? i want to get all the urls in one easy access

**Comment by fastaddons** [comment]
The backup file is a simple JSON text file. There are many tools which can format JSON or extract data from it.
But why would you want to extract URL from it?

**Comment by trinib** [comment]
OK.., just paranoid if Firefox ban this extension and I can't get back urls so I want to save all them manually.. it's alot lol

**Comment by fastaddons** [comment]
Don't worry, I have a good relationship with Mozilla ([look, this is me](https://blog.mozilla.org/addons/2020/06/15/friend-of-add-ons-juraj-masiar/)) and I'm not doing anything shady (unlike some other extensions) so there is no way I would get banned.
Also, as long as you have a cloud account, there is no way to loose data (it's one of the reasons I've build the server).

**Comment by trinib** [comment]
I found this website https://conversiontools.io/convert/format-json and formats it very well and fast.. just _**don't use no spaces (compact)**_ ..that worked the hell out of Firefox and **seriously** slowed down my pc and just never converts . Never in my 7 years of having my pc with no issues running 24/7 and I needed to power off from psu switch cause i taught the hdd or gpu was dying 🤣🤣🤣.. tried it twice to make sure and definitely the website scripting conversion , powerful 💩.

### 1 space is good enough
![image](https://user-images.githubusercontent.com/18756975/154873301-88b00b54-d56b-4ba2-915f-d735f60a7f85.png)
