### ISSUE TITLE
Windows 11 - the extension's interface missing

### ISSUE THREAD

**Issue by IvoAndonov** [fastaddons/GroupSpeedDial#120]
**Describe the bug**
Windows 11 - the extension's interface missing

**Steps To Reproduce**
1. Export settings WITH dials from another Firefox (linux version works too).
2. Run Firefox with GSD in Windows 11 and import the exported settings.
3. Close the settings window - no dials at all.

**Expected behavior**
Importing settings with dials should make them appear.

**Device info:**
 - operating system: Windows 11
 - Browser and version: FF 96.0.3.
 - GroupSpeedDial version: v18.3.

**Additional info**
I also tried copying over the entire FF profile from Linux to Windows 11 (this always works for Windows 10 and lower versions of it) but that didn't fix the problem. I've attached two screenshots here: one named linux.png which is what GSD looks like in linux and also what it SHOULD look like in Windows 11 and one screenshot of what it actually looks like in Windows 11.
I even tried running Firefox as administrator but that didn't fix the problem either.

![linux](https://user-images.githubusercontent.com/41172201/155873400-573a7f3b-59d3-4b54-af1b-068953acbd85.png)

![windows11](https://user-images.githubusercontent.com/41172201/155873401-286fe244-c6e5-405f-b0b9-e957b95f9b43.jpg)

**Comment by fastaddons** [comment]
Hello,
I'm not sure it's a good idea to copy Linux profile folder to Windows machine. It's hard to say how it will behave, many software has a platform specific code and settings.
Anyway, the blank page usually means broken storage. It's powered by the IndexedDB engine which is pretty fragile and can break easily (single unexpected file on the drive can break it).
The best way is to reinstall my addon - BUT you have to restart Firefox after uninstalling. Then importing data should work.

Also, please test your storage engine here:
https://firefox-storage-test.glitch.me/
If this fails, then there is something wrong with your Firefox. You should see "Storage is working" message after a few seconds.

**Comment by IvoAndonov** [comment]
Yeah, reinstalling GSD fixed it. Thanks! :) 

Copying over the entire profile from linux has never been a problem for me bc I've done it hundreds of times with Windows 7, 8.1 and 10. Never had a single problem with either of them! If you know what you're doing (which I do), it's quite easy to move the profile between operating systems. All you have to do is edit the install.ini and profiles.ini files to contain the name of the profile you want, set the profile to "locked=0" and then make both files "read-only". Then, enter the profile directory, delete "compatibility.ini" file and start the browser. And that's it - your whole profile from linux is there.

There's probably something different in Windows 11 because I put that same profile (with the missing interface from above) in a VM with Windows 7 and it worked perfectly fine.

**Comment by fastaddons** [comment]
Thanks! That's good to know!
In theory simply copy should work since profile folder should contain only data and should be platform independent. 
But software is often full of exceptions and special cases that needs special handling and the result is often "undefined" or in other words "not guaranteed to work".

Anyway, thank you for pointing this out! I need to fix my "broken storage" detection because there should be an error message explaining it more.

**Comment by IvoAndonov** [comment]
Simply copy-pasting used to work until about a year or two ago when Mozilla made changes to the way profiles are handled and also added that "Compatibility.ini" file which appears only in linux.

Here's a screenshot of the two files, in case you ever need to copy your profile from linux to windows. The line with the yellow dot contains the name of my profile where all of my settings and extensions are located.

![Picture_created_27-02-2022_18-23-31](https://user-images.githubusercontent.com/41172201/155890718-f52d262b-5280-4f4c-a151-203fc06db56d.png)

After you make these files (in Windows) look the same way, it's mandatory to make them both read-only, otherwise after the next browser update they'll revert to default state and you'll have to do this all over again.
