### ISSUE TITLE
Very slow startup times

### ISSUE THREAD

**Issue by Netchicken** [fastaddons/GroupSpeedDial#123]
When starting Chrome for the first time, GSD takes up to 20 seconds to populate the browser. All you get an empty GSD tab and a long wait before the browser becomes operational. 

It immedialty becomes usable as soon as the groups generate.

I have turned sync to off, and it makes no difference in time to load.

**Comment by fastaddons** [comment]
Hello,
Yeah, I'm gonna start working on this problem soon.
There is something wrong in Chrome and during the startup something starts consuming a HUGE amount of memory and blocks whole browser for several seconds.
This is most probably related to the storage so what should help is reinstalling my extension. More specifically, do this:
1) export your dials and thumbnails to a file from the Options page / Import backup - check also the checkbox to export thumbnails
2) uninstall my extension
3) restart Chrome or whole PC
4) install back my extension and import the backup file
This will restore all settings and dials but the databases should be recreated and the problem should be gone - for some time.

**Comment by Netchicken** [comment]
Works perfectly!
Thanks for your great program, I use it constantly, its a great way for keeping track of lots of topics I use.

**Comment by fastaddons** [comment]
Thanks :), good feedback is the reason I go to work every day.

Anyway, sadly the problem may reappear in some time but hopefully I will be able to find a workaround till then. 
I'm still not sure what is causing it, only that it affects Chromium browsers and that its related to storage.

Please let me know if the problem reappears. Thanks!
