### ISSUE TITLE
basic question

### ISSUE THREAD

**Issue by rlehmler** [fastaddons/GroupSpeedDial#124]
After launching Firefox, open a new page or a new tab the the content is always the first dial of the group. I would like to see the window with all dials at the beginning. What do I wrong?

**Comment by fastaddons** [comment]
Could you describe it more? I'm not sure what you mean. :)
Instead of a single group with dials you want to see all dials from all groups?

**Comment by rlehmler** [comment]
I have just one group. And if I open a new page or a new tab the content of this page or tab is the content of the first dial from this group. I would like to see the overview with all the dials at first. Sorry for my english :-)

**Comment by fastaddons** [comment]
> the content of this page or tab is the content of the first dial

This makes no sense :). Dial is composed of "name" and "image" (or thumbnail), so content of first dial is name and image.
And you want to see all dials? But you have only one group, you already see all dials. :D

If you are trying to change a layout, right click on the group name (or any dial) and select "Edit group" - that may help :).
If this is not what you are asking, could you maybe make a screenshot with some arrows? Thanks :)

**Comment by rlehmler** [comment]
Got it! Thank you.

<img width="1200" alt="sd" src="https://user-images.githubusercontent.com/101600313/158710905-651b0ce1-3302-4cfc-ab02-7accbf74e31b.png">
