### ISSUE TITLE
I and i letters are changing the search results

### ISSUE THREAD

**Issue by bbley1** [fastaddons/GroupSpeedDial#126]
**Describe the bug**

Using I and i letters in search button, are changing the outcome of search results.

**Steps To Reproduce**

Create a URL or Title with "i" letter in it. For example : github.com url with GitHub title.

Now make a search  using uppercase i =  "GITHUB", "gItHuB" etc.

**Expected behavior**

Search shouldnt be upper/lower case sensitive with "i, I" letters.

**Device info:**
 - GroupSpeedDial version: 18.3

**Comment by fastaddons** [comment]
Are you sure? I can't reproduce it here. All searches are case insensitive.

**Comment by bbley1** [comment]
Yeah i also cant reproduce it right now.

Maybe something was wrong with my browser and it seems it fixed itself after a restart.

Its all good now. I'm closing this one, thank you for your reply.
