### ISSUE TITLE
Groups and Dials lost

### ISSUE THREAD

**Issue by schulzjetzt** [fastaddons/GroupSpeedDial#127]
GroupSpeedDial Version v18.3
Firefox 98.0.2 (64-Bit)
Win 10 Pro 21H2 19044.1620

The GroupSpeedDial-Tab just shows a black page. Right-Click inside then black area opens a popup which allows to select an option named "Gruppe bearbeiten". Closing this dialog by clicking "Speichern" has the effect that i see the groups again. But layoiut configuration is limited.

**Comment by fastaddons** [comment]
Hello, please read this article I've wrote recently:
https://github.com/fastaddons/GroupSpeedDial/wiki/Recovery-of-your-dials,-how-are-dials-stored-and-how-to-make-a-backup

Also, what exactly happened?

**Comment by schulzjetzt** [comment]
Thank you for the information.
I execute these steps to solve the problem
- Export the configuration
- Reinstallation of the addon
- Import of the exported configuration.
. Rebuild the lost thumbnails

**Comment by fastaddons** [comment]
Great, I'm glad you managed to restore it.
