### ISSUE TITLE
Cannot login on a new device

### ISSUE THREAD

**Issue by daisyywl** [fastaddons/GroupSpeedDial#129]
Hi~

When logging into my account on a new device with firefox today, I have to re-login everytime I open a new tab on browser, or all the tabs in speed dial just disappear. Also I notice that when I open a new tab, the status of the speed dial account shows not logged in yet, and after I log into the account and open a new tab or window, it shows not logged in again. 

Is this normal?

Thank you ~

**Comment by fastaddons** [comment]
Thank you for the fast report!
I've released new version 19.0 today and I'm pretty sure I've broke this.
I will release 19.1 with fix asap!

**Comment by fastaddons** [comment]
New version 19.1 was just released. You can check for updates in the "about:addons" page - click the gear icon menu / Check for updates.

Thanks a lot for reporting this!
