### ISSUE TITLE
Cloud sync problems with settings.

### ISSUE THREAD

**Issue by Pizzapops** [fastaddons/GroupSpeedDial#13]
**Describe the bug:**
Cloud sync does not apply all Group & Dial settings to cloud display or sync them to  another installation. This includes custom thumbnail graphics. It automatically generates thumbnail screen grabs for all dials of new installation. 

I did a manual local backup  and used it to correct problems on both browsers but Cloud dials are still wrong. Both browsers are currently synced to cloud. Did I do something wrong?

![2020-06-09_GSD02](https://user-images.githubusercontent.com/33039961/84187998-7da48780-aa58-11ea-9e27-1544ab591d84.jpg)

**Device info:** 
 - operating system: Windows 10-64
 - Browsers and version: Vivaldi 3.0 & Firefox 77
 - GroupSpeedDial version:  Pro

**Comment by Juraj-Masiar** [comment]
Hello,
Yes, the Cloud Dials page is very VERY old. It doesn't support many features.
I have a fixed new version that will look just like the extension including all the Options and the Cloud Options page. It's amazing... but it still needs some tweaking so just be patient. It will come soon... I just need a week or two to finish the tasks I'm working on right now.
