### ISSUE TITLE
Since the update to 19.1

### ISSUE THREAD

**Issue by wdsellers** [fastaddons/GroupSpeedDial#131]
I am unable to add new pages to the dials.

**Comment by fastaddons** [comment]
Hello,
Could you provide exact steps to reproduce?
Thanks!

**Comment by wdsellers** [comment]
Click the Group Speed Dial icon on the menu bar
Click Add Page to Dial
Click location to add ... wants me to edit the location clicked
Does not add

**Comment by fastaddons** [comment]
Oh, yes that got broken but I've fixed soon after in 19.3. I've several hotfixes yesterday, current version is 19.4.
You can fix this simply by checking for updates:
1. open "about:addons" page (Ctrl + Alt + a)
2. open Extensions tab
3. click the Gear icon and select "Check for updates"
That should update my addon immediately to the last version. The default interval for checking for updates in Firefox is pretty slow.

**Comment by wdsellers** [comment]
Awesome, thanks! Worked Perfectly.

**Comment by fastaddons** [comment]
No problem, and thank you for reporting bugs!

**Comment by wdsellers** [comment]
Thank you.
