### ISSUE TITLE
Unnecessary "Loading" Animation

### ISSUE THREAD

**Issue by bbley1** [fastaddons/GroupSpeedDial#132]
**Steps To Reproduce**

Create a dial, select "Custom Thumbnail from file" but dont add any image file.

Click save changes.

Now the dial will show "Loading thumbnail animation" until you close the "group speed dial" tab and reopen it again.

 - Browser and version: Firefox 99
 - GroupSpeedDial version: 19.5

**Comment by fastaddons** [comment]
Good catch! :)
I'll fix this in the next release.

**Comment by fastaddons** [comment]
Fixed in 19.6, soon to be released.

**Comment by bbley1** [comment]
Well that was fast. Thank you. 👍‍
