### ISSUE TITLE
Thumbnails with Basic Auth

### ISSUE THREAD

**Issue by tamaskan** [fastaddons/GroupSpeedDial#133]
Hi,

anybody else ran into the issue that getting the thumbnail via default background-method got stuck on a basic-auth protected site ?

Best regards

**Comment by fastaddons** [comment]
Hello,
Could you send me a screenshot or more info and ideally steps to reproduce? I'm not sure I understand the issue.
Also, what browser do you use?
Thanks!

**Comment by tamaskan** [comment]
If i try to add a site on firefox like https://authenticationtest.com/HTTPAuth/ it keeps spinning (probably waiting for the prompt in the background). I got everything working now, so this issue is just a quick info that those prompts aren't skipped automatically :-)

**Comment by fastaddons** [comment]
Interesting, I would also think the prompt is blocked. There is a timeout fail-safe though, but it's maybe two minutes. So it would spin a lot.
This whole thumbnails generation is pretty fragile, it's one of the wort things I've ever programmed. And it's gonna completely break in 2023 when Chrome forces Manifest V3. I will have to find some workaround soon...
