### ISSUE TITLE
Group Speed Dial is creating a tab stack in Vivaldi

### ISSUE THREAD

**Issue by Locutus64** [fastaddons/GroupSpeedDial#134]
When I click a dial to open it it is stacked with the Group Speed Dial tab in Valadi. I was expecting it to open the tab next to Group Speed Dial or at the end of the tab bar not as a tab stack including Group Speed Dial. I have FVD installed and I added Group to replace FVD. FVD when I click a dial opens it at the end of the open tabs. FVD is always left as a standalone tab unless I physically drag another tab to it and drop it on FVD to create a tab stack.

**Device info:**
 - operating system:  Manjaro KDE 21.2.6
 - Browser and version:  Vivaldi 5.2.2623.39 
 - GroupSpeedDial version:  19.7

**Comment by fastaddons** [comment]
Hello,
Open Options page / Dials tab, and try to enable "Open without relation / position to current tab". That should help.

**Comment by Locutus64** [comment]
OK just came to say this can be closed. After I installed in my roommates browsers I noticed the setting and enabled it then went back to my system and made the adjustment. Again fantastic addon.

Rather than email you again I do have one question. Since we don't have a auto-updating popular group like with FVD if I create a Most Used group and copy my 20 or so most used dials to it will GSD automatically add that new group to my other browsers since I have sync enabled and I'm signed into it in all my browsers, or will I have to manually create that group in each browser? Thanks

**Comment by fastaddons** [comment]
I'm glad that worked :)

Yes, with the synchronization enabled, all data will be synchronized so no need to do anything on the other devices / browsers.
Thumbnails synchronization must be enabled manually though in Options page / Thumbnails.

**Comment by Locutus64** [comment]
Great info and thanks again.
