### ISSUE TITLE
No coordination between Firefox and Chrome.   

### ISSUE THREAD

**Issue by elchinero** [fastaddons/GroupSpeedDial#135]
New "Pro" customer.  No "History/Backups" on Upper LH pull-down menu.  Chrome "Main Page" pretty much unlike Firefox (which I wish to "rule" the pages = only one page, layout unlike Firefox.

**Comment by fastaddons** [comment]
Hello,
First, make sure to install the extension into both browsers:
Firefox:
https://addons.mozilla.org/addon/groupspeeddial/?utm_source=home
Chrome:
https://chrome.google.com/webstore/detail/groupspeeddial/imfeikbeimbfpmgfkkmjekabdehiiajc

Then make sure to login to your cloud account on both browsers:
https://group-speed-dial.fastaddons.com/

And if you want to enable also thumbnails synchronization (not just dials), then on both browsers open Options page / Thumbnails tab and check the "Enable automatic thumbnails synchronization with the cloud server".

That should be it for the basic setup, please let me know if you need further assistance :)

**Comment by elchinero** [comment]
10-4

Thanks

__________________
Anthony Tellier
***@***.***

"Winning is habit. Unfortunately, so is losing.” - Vince Lombardi

**Comment by fastaddons** [comment]
No problem :)
Have a nice day!
