### ISSUE TITLE
Merge Groups

### ISSUE THREAD

**Issue by simontrhodes** [fastaddons/GroupSpeedDial#136]
In the past I've used folders in bookmarks and TooManyTabs to organise URL's
I've imported the folders into GroupSpeedDial Pro.
Now I have some duplicate groups, with some duplicate dials.
Moving individual dials is too slow.

Please could we have the option of joining two groups together, even if this created a new third group?

This feature could include issue 28, "Duplicates finder"
https://github.com/fastaddons/GroupSpeedDial/issues/28

Thank you in advance.

**Comment by fastaddons** [comment]
Good point, I've been missing a proper "organizer" for too long.
I've implemented "selecting multiple dials" for the Productivity mode, I could reuse it to allow you to select all dials in a single group and then move them to a different group.
That could trigger also some duplicate detector that would allow you to find and remove duplicates, like when you paste files from one folder to another one and there are duplicates.

I will try to implement this by the end of next week.

**Comment by simontrhodes** [comment]
Thank you, that's amazing.
I's be happy to beta test this function with my groups and dials.

**Comment by fastaddons** [comment]
So, 19.9 was just released for Firefox (Chrome version is still in review queue) with a new "Dials selection" feature:
- you can now activate "Select dials" mode from the main menu or from the context menu / "Move dial" / "Select dials" (or press "s")
- click or select dials you want to move
- right click to access context menu and click "Cut"
- then right click and "Paste" dials in target group
- you can also mark dials and from the context menu select "Move to group"
- more operations and a status bar / command bar / duplicate finder will be added soon, probably in the next release 20.0

**Comment by simontrhodes** [comment]
That's brilliant!
I normally use Chrome, but just tried it now in Firefox and it works really well.
Thank you for all your hard work.
Simon

**Comment by simontrhodes** [comment]
Just tried Chrome and Brave, single dials work well.
But I'm unable to select multiple dials, there is no select option in the menu.

**Comment by fastaddons** [comment]
Chrome version is not released yet. Usually it takes about one day for them to review the update. So I guess tomorrow it should be released.
You can see the version number in main menu or in the popup menu when you click the toolbar icon. New version is 19.9.

**Comment by simontrhodes** [comment]
Thank you, I was just getting too excited about these new features.

**Comment by simontrhodes** [comment]
Works perfectly in Chrome and Brave.
Thank you for adding this functionality.

**Comment by fastaddons** [comment]
No problem :), it should have been added long time ago. Thank you for pointing it out :)
I will also try to upgrade it further in the next releases.
Have a nice week!
