### ISSUE TITLE
add a crxmouse gesture for home page

### ISSUE THREAD

**Issue by fuorigioco1981** [fastaddons/GroupSpeedDial#137]
i have in microsoft edge an add on called crxmouse gestures and i want to add a gesture for  home page which is the type chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.html   
so i have your add on as home page.
but the ONLY gesture it doesnt work is this!any idea?
in firefox with another add on for gestures i can

**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: 
 - Browser and version: 
 - GroupSpeedDial version: 

**Additional info**
Add any other info about the problem here.

**Comment by fuorigioco1981** [comment]
groupspeedial 19.7
microsoft edge 101.0.1210.32 (Official build) (64-bit)
windows 10

**Comment by fastaddons** [comment]
Hello,
Addons cannot run on another addon pages - it's a browser security measure and to prevent compatibility issues. 
So I'm pretty sure it's impossible, even in Firefox.

However, as long time gestures users I can highly recommend using a desktop gestures app - not only it will work on all pages, but also in all other apps in your Windows. It takes some time to set it up and it may miss some browser specific features which can't be done by emulating key-presses (for example you can close tab with Ctrl + W so the gesture tab can emulate this keypress).

**Comment by fuorigioco1981** [comment]
in firefox with  gesturefy it works i added your home page!

**Comment by fastaddons** [comment]
You can actually draw a gesture on my dials page and it works?

**Comment by fastaddons** [comment]
Oh, you mean gesture that navigates you to homepage?

**Comment by fastaddons** [comment]
Try to use:
```
edge://newtab
```

**Comment by fuorigioco1981** [comment]
> Try to use:
> 
> ```
> edge://newtab
> ```

with this if iam in a web page and do the gesture will it STAY in the same tab like in ffox?

**Comment by fastaddons** [comment]
That depends on the gestures app you use, but unless you can emulate "Alt + Home" shortcut which opens homepage, this is the best chance you have.

**Comment by fuorigioco1981** [comment]
so its a problem of the gestures add on ,browser or grouspeeddial?
i want to open IN THE SAME TAB the home page(while i am in a web page) this is ok in ffox with gesturefy add on

**Comment by fastaddons** [comment]
This is not actually related to my addon. My addon can't affect it at all.
It's your gestures addon you have in your Edge that needs to open the homepage and it may be blocked by Edge because addons has special URL.

**Comment by fuorigioco1981** [comment]
the same problem happens in chrome too

**Comment by fastaddons** [comment]
Yeah, both Chrome / Edge and many other browsers are build from the Chromium core, so they share many issues / restrictions.
So using `edge://newtab` didn't worked?

**Comment by fuorigioco1981** [comment]
the "new tab " gesture works but opens the tab in NEW TAB not in the current tab i want!

**Comment by fastaddons** [comment]
It's the gestures app that opens it in the new tab, you need to set it there to redirect current page to that page. Sounds like something that should be possible in every gestures addon.

**Comment by fuorigioco1981** [comment]
![Screenshot 2022-05-07 230046](https://user-images.githubusercontent.com/33813539/167269982-09c2e1bc-cc3f-458e-b36b-bc4124d5e073.jpg)
![Screenshot 2022-05-07 230025](https://user-images.githubusercontent.com/33813539/167269983-7bfa20aa-f930-488e-92ca-2f937058f7b5.jpg)
Despite i set it to open in CURRENT tab in doesnt!

**Comment by fastaddons** [comment]
Hmm, I can't say why. You should contact the developer of that addon, he should be able to help you.

**Comment by fuorigioco1981** [comment]
ok thanks for your time!your add on is my home page(cloud or not) in all my devices!

**Comment by fastaddons** [comment]
No problem, I hope you find a solution!
Good night :)
