### ISSUE TITLE
Auto-generated thumbnail does not auto-reload

### ISSUE THREAD

**Issue by TigBuh99** [fastaddons/GroupSpeedDial#143]
I have a speed dial for the BBC News page (https://www.bbc.co.uk/news/uk) since a long time ago. In the last few days I noticed that the auto-generated thumbnail does not reload.

The setting is for the reloading to take place every 15 minutes and the thumbnail used to be auto-reloaded regularly with no problem in the last few months.

However, the thumbnail does get refreshed by right clicking on it and choosing Refresh image --> Refresh by visiting page.

Windows 10 Pro 21H2 OS Build 22000.708
Chrome 102.0.5005.63 64 bit
GroupSpeedDial version 19.9

**Comment by fastaddons** [comment]
See Options page / Thumbnails / Auto-reload settings / Disable on this device - make sure it's not checked.
Other than that, it should work - more less.

However, auto-reload in Chrome is now pretty bad because it doesn't allow creating new windows outside of user monitor so when auto-reload runs, you will see flash of the reloading page.

**Comment by TigBuh99** [comment]
That setting in the Options page is not checked. However, now that you mention it, I remember that until recently I used to see a flash of the reloading page, but this has recently stopped. I'm guessing that when it stopped must have been the time when the auto-reload problem arose.

Recent changes that I did in WIndows/Chrome is to add an extension to Chrome called Tablerone, uninstalled Comodo Internet Security and installed Voodooshield and DefenderUI.

The refresh image by visiting page is the only thing that works with auto-reload.

**Comment by fastaddons** [comment]
When you try the default reload, do you see a new pinned tab being created? 
Does it disappear or it stays there? Will it work if you focus it?

**Comment by TigBuh99** [comment]
I see the tab that you mention. It appears briefly (3-4 seconds and then it disappears. The page being opened appears very small, in fact smaller than the speed dial image, but if I click on it it expands to about a fifth of my monitor area and then it disappears.

I couldn't test if it will work if I focus on it. I'll have to wait until the actual page content changes from the current one on the speed dial.

**Comment by TigBuh99** [comment]
I clicked on the small image in the transient tab and it updated to the current page. Then the speed dial was also updated to the current page.

**Comment by fastaddons** [comment]
So, what should happen is:
- pinned tab is created
- when the page inside it is loaded, it's moved into own window
- then the screenshot is taken and the window should disappear

Can you tell me, if you don't focus the pinned tab, can you see the new window being created and then disappear?
Also, do you have multi-monitor setup?

**Comment by TigBuh99** [comment]
![CopyQ jchoQD](https://user-images.githubusercontent.com/49759462/172836175-831bb47f-b732-4b8b-8060-fbe661245a7d.png)
The image shows what I see if I press "Refresh" and focus on the temporary tab. That is, a tab with no title is created on the left hand side of my monitor, it remains for 3-4 seconds and then it closes.

I don't see a new Window being created and then disappear whether I focus on the new tab or not. As I wrote before, there were times in the past few weeks when I used to see a brief appearance of a new Window, presumably when the auto-reload was taking place. I don't see this happening anymore.

I have a laptop and I have connected it to a tabletop monitor. I have set it up so that only the monitor is active.

**Comment by fastaddons** [comment]
Thanks for the info.
The small image is not a problem, it should resize to big right before taking the screenshot.
But something is broken. Could you paste here your "Runtime errors" right after reloading one page - without focusing the pinned tab, just click reload and wait. Then open main menu / Advanced / Send error logs, and paste the text here - mostly the bottom part after "Runtime logs:"

If the reloading failed, it should throw some useful exception there.

**Comment by fastaddons** [comment]
Great! That makes sense now. That' the new Chrome 102 security that prevents creation of windows outside of user monitor - at least 50% must be visible.
But I'm doing that already, so why does it still complain....
Hmmm.... I'm keeping only a very small margin, is your toolbar or other part of the Chrome window somehow bigger than it should be? :)

Too bad I'm not logging the exact position where the window is being created. 
Maybe it's trying to create it on the laptop monitor, could you try to disconnect the main monitor to see if it works on laptop only?

**Comment by fastaddons** [comment]
Thank you for the info!
OK I have some ideas, I will increase the margin just in case and also add a fallback since I can detect this error. And I will improve my logger as well, just to be sure.
I need to finish few more tasks for the next release so this will take a few days to release.
Thanks again for the collaboration!

**Comment by TigBuh99** [comment]
Thank you very much for your attention to this issue. I'll look forward to seeing how the problem may be resolved.

**Comment by fastaddons** [comment]
New version 20.0 was just released, it should fix the default thumbnails generation.
Please let me know if it's still broken.

**Comment by fastaddons** [comment]
Oh, still broken on my Ubuntu :(, does it work for you?
I will be releasing hotfix 20.1 soon :)

**Comment by TigBuh99** [comment]
I replied by email. Unfortunately it's not yet fixed on Chrome.

**Comment by fastaddons** [comment]
Great, yeah it should work also for auto-reload, it's using the same code.

**Comment by TigBuh99** [comment]
Thank you very much for fixing this!

**Comment by TigBuh99** [comment]
It didn't work with v.20. However, I did see a brief flash of a window, 
which I was no longer seeing in the last few weeks when I was trying to 
refresh the image. It only works if I refresh the image by visiting the 
website.
------------------------------------------------------------------------
*From:* Juraj Mäsiar ***@***.***
*Sent:* Thursday, June 16, 2022, 2:20 PM
*To:* fastaddons/GroupSpeedDial
*Cc:* TigBuh99; Author
*Subject:* [fastaddons/GroupSpeedDial] Auto-generated thumbnail does not 
auto-reload (Issue #143)

**Comment by fastaddons** [comment]
Hello,
So it's still broken?
Could you send me the runtime logs again after trying to reload one? Just like I've mentioned in https://github.com/fastaddons/GroupSpeedDial/issues/143#issuecomment-1151140788
