### ISSUE TITLE
Thumbnails Disappear - Chrome Windows 11   I see it is listed as a bug.   Any progress?

### ISSUE THREAD

**Issue by ghost** [fastaddons/GroupSpeedDial#148]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: 
 - Browser and version: 
 - GroupSpeedDial version: 

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
https://github.com/fastaddons/GroupSpeedDial/issues/139#issuecomment-1160689846
Please don't create new duplicate thread after commenting in one and then deleting your account???
