### ISSUE TITLE
Only some thumbnails have auto loaded  after attempted export & synch from Chrome to Brave 

### ISSUE THREAD

**Issue by simonlarb** [fastaddons/GroupSpeedDial#149]
**Describe the bug**
Only some thumbnails have auto loaded  after attempted export & synch from Chrome to Brave .

**Steps To Reproduce**
As above.

**Expected behavior**
Not the above. Expected ALL thumbnails in new Group Speed Dial to update automatically after exporting from Chrome & synching.

**Device info:**
 - operating system: Windows 7 - 64 Bit
 - Browser and version: Brave [Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)](https://brave.com/latest/)
 - GroupSpeedDial version: 20.2

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
I'm not sure I have automatic reload for imported dials enabled.
But if you try to reload them manually, it still fails? You can re-create all missing from the Main menu / Refresh images.

Also, could you estimate how many were created and how many were missing?
Thumbnails generation is a very fragile these days, especially in Chromium based browsers, so I'm still trying to improve it...

**Comment by simonlarb** [comment]
God I love you!
"I'm not sure I have automatic reload for imported dials enabled."
That was all I had to enable!

Such a great product!

Thank you yet again, oh master, lol!

Simon L.

**Comment by fastaddons** [comment]
No problem, I'm glad it worked out.
Have a nice day :)

**Comment by simonlarb** [comment]
Thanks, you too!
Oh code magician, lol!
