### ISSUE TITLE
Keeps reloading live thumbnail over custom 

### ISSUE THREAD

**Issue by kwambono** [fastaddons/GroupSpeedDial#150]
**Describe the bug**
Custom thumbnail is overwritten by re-saving URL information (website pagination changes)

**Steps To Reproduce**
Change url and save dial.

**Expected behavior**
Thumbnail stays in place unless changed. Took time to create and apply!! Now that time is wasted.

**Device info:**
 - operating system: Mac os 12.4
 - Browser and version: Firefox 102.0.1
 - GroupSpeedDial version: 21

**Additional info**
Do not overwrite custom thumbnails please, its annoying and wastes my time

**Comment by fastaddons** [comment]
Hello,
The thumbnail should stay if you don't change the domain.
For example if you change:
https://appstoreconnect.apple.com/trends/insights?pageid=8
into:
https://appstoreconnect.apple.com/trends/insights?pageid=CHANGE_HERE
It will keep the thumbnail, because the domain name is the same.

Could you clarify more what exactly changed in the URL?

**Comment by kwambono** [comment]
Hi Juraj,

The domain change is only the digits on the end (ie pagination position in an infinite scroll page):

Common example - changing the "26100" to “26140” in this URL:

https://vk.com/topic-178186634_39300111?offset=26100 <https://vk.com/topic-178186634_39300111?offset=26100>

See attached video. (sorry email - bounced mail due to size of video: see it here - https://gochimor.co.za/changedial.mp4  )

As soon as I ’save changes’ it immediately then says “create thumbnail” and then blanks the tile and displays a spinner graphic top right. Then it loads an auto thumbnail of the page.

Until recently (a week or so ago) it did not do this as I have been using it for quite a while.

Apologies for the tone of my post - I was pissed off at having a bunch of custom made thumbnails suddenly get replaced by auto generated web page images! I like your plugin a lot and find it really useful.

Regards,

Mike

**Comment by kwambono** [comment]
Hi Juraj,

I use the option for "custom thumbnail from file”. This will keep the loaded thumbnail but if I quit the browser and re-open it will revert to creating a new thumbnail on URL edit and then if I look its changed to “auto generated thumbnail” by itself.

**Comment by fastaddons** [comment]
Thank you for the steps to reproduce, I'll look into it and fix it in the upcoming release 21.2.

**Comment by fastaddons** [comment]
Hello again,
I'm looking now at this problem but I'm still unable to reproduce it.
How exactly do you change the URL, are doing it through the "Edit dial" window? Or are you using "Add this page to dials"?

**Comment by kwambono** [comment]
Hi Juraj,

I am using right-click-Edit Dial window to change it. I have reloaded all the custom thumbnails a few days ago and it hasn’t deleted them yet (ie its staying on the “Custom Thumbnail” setting as expected now, even when quitting/restarting the browser” so I am not having the problem anymore?

Regards,
