### ISSUE TITLE
I typically use FF, but if I transition to say Chrome/Brave icons are not refreshed.  Similarly if using cloud many icons are not updates with anything, some have the favicon which is better than nothing.   At least without an image and 4 links to same site, a popup/title should be used so I know what I am clicking.  Ultimately images from browser should be uploaded to cloud.

### ISSUE THREAD

**Issue by mikwei** [fastaddons/GroupSpeedDial#158]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fastaddons** [comment]
Hello,
Thumbnails synchronization needs to be enabled in the Options page / Thumbnails.
So the thumbnails refreshing is working in your Firefox but not in Chrome? Does it create bad thumbnail, empty, or not at all?

**Comment by mikwei** [comment]
Duh, sync somehow got turned off.  Turned on and all is good.
