### ISSUE TITLE
Text only option

### ISSUE THREAD

**Issue by Nodachi216** [fastaddons/GroupSpeedDial#160]
FVD Speed Dial has the option to not show thumbnails at all but use a favicon and text title instead. Would this be possible to implement in this extension?

**Comment by fastaddons** [comment]
Hello,
There is a new "List layout" that doesn't show thumbnail, only title and favicon.
Right click group (or open main menu) and click "Edit group" and change the layout to "list".

**Comment by Nodachi216** [comment]
Awesome! Thank you very much!
