### ISSUE TITLE
There are empty slots on the page

### ISSUE THREAD

**Issue by tankist-git-2** [fastaddons/GroupSpeedDial#161]
This week I saw the appearance has changed: a lot of empty slots become visible. I can't hide them. What's going on?

![dial_failure](https://user-images.githubusercontent.com/94906168/190075113-776ebcef-03ae-43aa-a9dc-da0880bfbf9a.png)

**Comment by fastaddons** [comment]
Hello, two questions:
1. what layout do you use? Right click group name and select "Edit group" - there see what "Group layout" is selected.
2. are you using some custom CSS styles? See Options page / General / Custom CSS styles - is there some text entered?

I've released new version yesterday so maybe I've broke something, please let me know.

**Comment by SomeDude77** [comment]
I have the same problem after the new update. Even though "hide empty dials" is enabled in dials options I still se empty dials on every group. I use the layout "fill space". I use no custom CSS style in this addon.

**Comment by fastaddons** [comment]
Thank you for reporting!
I'm working on a fix now, it will be released for Firefox today.

**Comment by seregin2020** [comment]
Hello dear admin, the same problem, but only in Firefox. In the browser Catsxp (Chrome) everything works fine. Thank you.

**Comment by fastaddons** [comment]
Yeah, Chrome version wasn't released yet, it's still stuck in the review so it will get broken in Chrome as well...

But I have the fix ready, and I will release it in a few hours. I just need to fix few more small bugs I've found.
Chrome version will be fixed as soon as they approve the hotfix.

**Comment by fastaddons** [comment]
New Firefox version 21.6 has just been released with 14 bugfixes, I can't believe how many bugs I've managed to find (and I hope I didn't break more things, I'm totally exhausted now after whole day of fixing things so I may have missed something...).
Please let me know if it works now, there is so many combinations possible and with the new styling I've build there may be still some issues.

**To force update now, visit "about:addons" page and click "Check for updates" from the gear icon menu.**

**Comment by seregin2020** [comment]
Firefox already works great! Thank you for your hard work!

**Comment by Pizzapops** [comment]
The latest versions of GSD (Firefox, 21.6 & Chrome-Vivaldi, 21.5) have messed up my Group/Dials display. If **Hide empty dials** is checked, GSD still shows the border and background of the "empty" dial.  I have been using the Custom CSS style for a while but now it seems to be a problem. The CSS:

**#dials > a > div {
        padding: 3px;
	border: 3px solid #555555;
        border-radius: 6px;
	background-color: white;
        box-shadow: none;
}
#dials > a > div:hover {
        padding: 2px;
        border-radius: 6px;
	border:4px solid #E53B35;
        box-shadow: none;
}**

I use a 9x8 grid of dials but only populate the center 7x6. The empty dials provide a border around the group. But they can no longer be hidden.
![GSD_21-5](https://user-images.githubusercontent.com/33039961/190664717-ce9fbaa0-802b-4b7f-959a-bb94cded77d4.jpg)

**Comment by fastaddons** [comment]
Hello @Pizzapops,
Yeah, I'm sorry about that. There's been so many changes, your custom CSS styles needs to be updated a bit.
Let's change the very fist line of your first style into this:
```
#dials > a.dial:not(.is_empty_dial) > div {
```
That will make the style apply only to non-empty dials. Then with the "Hide empty dials" option they should be invisible again. That is in Firefox, in Chrome this option is still broken so you need to wait for Chrome update. I've submitted it yesterday so I've expected it to land today, but it's still being reviewed...

**Comment by Pizzapops** [comment]
It works... Thanks for the quick reply!! The **div:hover** line also needs to be changed.

**Comment by fastaddons** [comment]
Chrome 21.6 has just been released... finally!
Thank you all for your patience :)
Have a great weekend!
