### ISSUE TITLE
[Firefox, Linux] Space around dials disappeared this morning after an update

### ISSUE THREAD

**Issue by rado84-github** [fastaddons/GroupSpeedDial#162]
**Describe the bug**
Space around dials disappeared this morning after an update

**Steps To Reproduce**
IDK which package caused it, so I can't provide steps to reproduce it.

**Expected behavior**
Space around dials shouldn't disappear.

**Device info:**
 - operating system: Arch Linux
 - Browser and version: Firefox 104.0.2
 - GroupSpeedDial version: 21.5

**Additional info**
This morning there was a big update of at least 20 packages and some of them required a system reboot, so I did that. After the reboot I ran Firefox and noticed that the space between dials had disappeared. I've set that space to be 1 pixel but even resetting that value didn't bring the space back.

![Picture_created_14-09-2022_15-05-49](https://user-images.githubusercontent.com/41172201/190149158-274fc0a6-ba71-44f8-aeb1-cbcf0db66c67.png)

**Comment by fastaddons** [comment]
Hello,
I've released update with some big styling refactoring so I've probably broken something.
Are you using some custom CSS styles? See Options page / General / Custom CSS styles - is there some text entered?

**Comment by fastaddons** [comment]
Hmm, that looks fine, something else is broken.
What group layout do you use? Right click group name and select "Edit group" - see what "Group layout" is selected.
Also, which options do you have enabled in the Options page / Dials tab. By default they are all un-checked, so which one do you have checked? You can also send me a screenshot.

**Comment by rado84-github** [comment]
"Fill space" layout for all groups.

![Picture_created_14-09-2022_15-20-32](https://user-images.githubusercontent.com/41172201/190152332-ed391e2d-ecf2-4262-97e5-87cf70a86a4c.png)

**Comment by fastaddons** [comment]
Thanks!
So, there is a problem with the shadow that's now missing. Is that it? The space around dials should still work, but without the "border-like-shadow" they may feel too close to each other.
I will fix it and new version 21.6 will be released in a few hours.

**Comment by rado84-github** [comment]
Cool!

I suppose it could be a shadow problem. Frankly it never occurred to me that the shadow around dials and space around dials were the same thing. :)

**Comment by fastaddons** [comment]
New Firefox version 21.6 has just been released, I hope it will fix this.
To force update now, visit "about:addons" page and click "Check for updates" from the gear icon menu.

**Comment by rado84-github** [comment]
Yep, it fixed it. Thanks!
