### ISSUE TITLE
Chrome: hide empty speed dial err

### ISSUE THREAD

**Issue by Jerning** [fastaddons/GroupSpeedDial#163]
Chrome: hide empty speed dial err
chrome version: 版本 105.0.5195.125（正式版本） (x86_64)

the  hide empty speed dial setting in  edge is True

**Comment by fastaddons** [comment]
Hello,
Yes, I'm sorry, I've broke it in 21.5. The new version 21.6 is being reviewed by the Chrome store since yesterday so it should get approved soon (usually it takes them about 24h to approve a new version).

**Comment by Jerning** [comment]
oh! think you
