### ISSUE TITLE
How can I hide moz-extension URL from the start page (or home page) ?

### ISSUE THREAD

**Issue by Sen-nin** [fastaddons/GroupSpeedDial#165]
Hello. I have a little problem. I set the Group Speed Dial as my home page and a new tab in Firefox. When I start Firefox, I see something like "moz-extension" or "moz-extension: //url-like string" in the address box, depending on the version of Firefox. It is probably part of the Firefox specifications, but it inconveniently occupies too much space in the address box. Is there a way to hide it? Thank you.

**Comment by fastaddons** [comment]
Hello,
In Firefox it should be already set as homepage and has empty address bar.
See this page:
about:preferences#home
The "Homepage and new windows" setting should be set to "Group Speed Dial". Don't enter manually the URL.

**Comment by Sen-nin** [comment]
Thank you for replying so quickly. I am talking about the string in the red circle.

![group-speed-dial](https://user-images.githubusercontent.com/89894151/191699213-76747270-22a3-4b9b-832a-c1d10672a9fa.jpg)

**Comment by fastaddons** [comment]
Oh, yes I see.
I had actually the same question:
https://discourse.mozilla.org/t/make-addressbar-text-extension-name-of-the-extension-shorter-or-hide/28026

So yes, it's possible but it's not trivial.
You need to create "userChrome.css" file in the Firefox profile directory and add some custom CSS styles inside it. Also it needs to be enabled in the about:config page.
There is whole tutorial for this so it's not hard to do, it just takes time.

Just follow the instructions in the link above and you will get something like this:
![image](https://user-images.githubusercontent.com/55486931/191700511-3e12663b-9fb6-448a-a69d-83af340d4bd9.png)

**Comment by Sen-nin** [comment]
Thank you. It looks like I have been able to hide the part circled in red above.

But what about the URL part circled in red shown below? Do you think it possible to hide it as well? I have a feeling this would require a script. Thank you.

![address-bar-problem](https://user-images.githubusercontent.com/89894151/191882861-5c581ced-f73b-419d-b3dd-bb926a6ee4d2.jpg)

**Comment by fastaddons** [comment]
What Firefox version are you using? The text shouldn't be there at all.
See the settings page as I've mentioned before:

![image](https://user-images.githubusercontent.com/55486931/191907973-2d9aba59-a3cd-4106-977d-18ca1d121882.png)

**Comment by Sen-nin** [comment]
That one is a firefox fork based on Firefox Version 68 called Mypal 68. I mostly use that browser now.

**Comment by fastaddons** [comment]
Oh, that's very old browser. Firefox 68 was released in 2019. They've fixed the URL bar in the meantime :)

Anyway, **I would strongly recommend you switching into something newer.** These old versions doesn't have new security patches. And there's been A LOT of security holes fixed in the 2 years.

Few days ago Firefox released extended-support-release version ESR 102 and normal version is 105.

Also, my addon doesn't support these old browsers anymore, so current version 21.7 is available only for Firefox 91 or newer and soon I will move it to 102 since I plan to use some of the new features.

**Comment by Sen-nin** [comment]
It is probably outside your support limit, but it is just made to work with Windows XP. Options page looks like this now:

![address-bar-problem-mypal68-options](https://user-images.githubusercontent.com/89894151/191911016-14c69596-6d7c-4c2c-bc46-03e58034b892.jpg)

**Comment by fastaddons** [comment]
Yeah, that's the old interface.
But even if the address bar is not empty, when you open new tab page, it should be selected so when you start writing, it will disappear, right? So it shouldn't really affect the usability, only visual experience.

If you are restricted by your operating system, maybe migrate into Linux based operating system, for example Linux Mint. It can often run without issues on older hardware and it support all new browsers.

**Comment by Sen-nin** [comment]
You are right about that, and thanks for your advice.

I have a few much faster notebooks, but I am totally restricted by the keyboard layout of my ancient notebook. Following your advice, I may try Linux Mint or something in the future. Only I may have trouble making my ancient numerous Windows XP software programs work on Linux.
