### ISSUE TITLE
Save Dial Thumbnails with Backups

### ISSUE THREAD

**Issue by AdamHardix** [fastaddons/GroupSpeedDial#167]
It would be fantastic if the backup function allowed saving of thumbnails, and would make setting up Group Speed Dial on multiple devices much easier and more visually cohesive.

**Comment by fastaddons** [comment]
Hello,
There is a checkbox "export also thumbnails - this will greatly increase export file size" next to export button. That exports also thumbnails :)

**Comment by fastaddons** [comment]
Sadly I can't. I wanted to do it but currently it's not possible. 
You see, when you check the checkbox, the whole image database is serialized into text which takes A LOT of resources, depending on how many images and their size and PC speed, this can take more than 20 seconds.

I wanted to upgrade it with "downloads" API but Safari and Android doesn't support that.
Maybe I could auto-start the download after the checkbox is checked (and DB is exported), but I'm not sure it will work in every browser. I'll see what I can do.

Alternatively, you can enable Thumbnails synchronization and they will synchronize across devices / browsers.

**Comment by Juraj-Masiar** [comment]
This has been implemented now, not long ago.
