### ISSUE TITLE
Thunbs created with MakeText.io

### ISSUE THREAD

**Issue by tockschmock** [fastaddons/GroupSpeedDial#180]
Creating illustrative thumbs is the most time consuming step in organizing dials.
A thumbnail of the web page is not useful in most cases for me because it is too small.

That's why I like the option to create thumbs from text with MakeText.io in GSD.

However the thumbs created this way do not show on the website:
https://group-speed-dial.fastaddons.com/cloud/ 

and therefore also not on mobile devices.

**Comment by tockschmock** [comment]
Dragging image files onto the dials for thumbnail creation is also a very welcomed option.

However here also the images do not show on the website:
https://group-speed-dial.fastaddons.com/cloud/
and therefore also not on mobile devices.


Chrome-OS and browser 107.0.5304.92

**Comment by tockschmock** [comment]
Thumbs assigned from local image files also do not show up in the cloud.

Apparently, only thumbs assigned via image URL show up in the cloud here correctly.

https://group-speed-dial.fastaddons.com/cloud/

**Comment by fastaddons** [comment]
You need to enable thumbnails synchronization first in the Options page / Thumbnails tab.

**Comment by tockschmock** [comment]
Thanks - works great
