### ISSUE TITLE
keyboard shortcuts ?

### ISSUE THREAD

**Issue by tockschmock** [fastaddons/GroupSpeedDial#181]
the meaning of "A" and "e" is not exactly clear to me   (German language)
"e" probably stands for edit / calls the edit options 

![DSC_0019~2](https://user-images.githubusercontent.com/68165681/200177909-322eb571-5f86-4e3b-9fe6-f13e2fe281ed.jpg)

**Comment by tockschmock** [comment]
Understood now
"A" is the name of my (test) group ...

**Comment by cipricus** [comment]
then you should close the issue yourself, see "close" button left of "comment" button.

**Comment by tockschmock** [comment]
OK, I close it.
