### ISSUE TITLE
Thumbnail from Clipboard

### ISSUE THREAD

**Issue by tockschmock** [fastaddons/GroupSpeedDial#199]
Assigning a dial thumbnail from the current clipboard content would be a very handy feature.
Windows and Chrome OS both have built in tools to capture custom rectangular area screenshots, that are automatically copied into the clipboard (don't know about Linux).

This way not only images (GSD built in context menu option / fails on images that are part of links) but whole website areas (logo plus heading, etc.) could conveniently serve as dial thumbnails.

**Comment by fastaddons** [comment]
This is now implemented in 22.2.
You can press Ctrl + V when the "Edit dial" window opens or inside the Edit dial / Thumbnail / Custom thumbnail from file / "Paste from clipboard".
Currently only for Chrome/Chromium, Firefox version is being held by reviewer for a few weeks now.
