### ISSUE TITLE
Context menu - directly add site to folders

### ISSUE THREAD

**Issue by derdershat** [fastaddons/GroupSpeedDial#2]
thank you very much for this great addon.

I used fast dial <57 Firefox for years and tried some dial addons in newer firefox and miss the fast dial behavior to add sites via context menu directly in the folder that I want. 

I mean without opening the dial page and have to click into the group and add the site there.

would shorten the process extremly.

if you could add the groupfolders to context menu something like this would be great:

- Add this site to dials (if click than behavior like it is yet)
  (context in context menu)
  - add to default
  - folder 1
  - folder 2
  etc

**Comment by fastaddons** [comment]
Makes sense. I will new option to the Options page / Context menu tab.
I will try to include it in the next release 14.7.

**Comment by fastaddons** [comment]
Done, in 14.7, needs to be activated in Options page / Context menu / "Show list of groups in context menu for fast insert" checkbox.

Firefox version is released, Chrome version is being reviewed (this usually takes several days).
