### ISSUE TITLE
[Firefox] None of the "style" options work under the "dials" category

### ISSUE THREAD

**Issue by SLinxTheFox** [fastaddons/GroupSpeedDial#204]
All of these options (https://i.imgur.com/jYJU0te.png) make no changes other than the font size. 
I'd really like to remove the on hover effects and the empty dials

Win 10
Firefox 107.0.1 (64-bit)
GroupSpeedDial 21.8

**Comment by fastaddons** [comment]
Just to clarify:
- you did click "Save changes", right?
- and you are not changing it in the Cloud Dials settings page: "https://group-speed-dial.fastaddons.com/cloud/options/options.html"

Other than that it should work, otherwise many people would complain :)

**Comment by SLinxTheFox** [comment]
yeah I clicked save changes, I don't have a cloud dials account yet, i can make one and try to change stuff there as i was already planning to.

if it's just me, any ideas? the rest of the addon settings work, just not those settings for some reason

**Comment by fastaddons** [comment]
Are you using some "Custom CSS styles:" in the options page / General tab?

**Comment by SLinxTheFox** [comment]
Nope, no custom CSS

**Comment by fastaddons** [comment]
One more question, I've just remembered, there is a special option in the Layout section above it:
**Transparent dial name background (puts focus on thumbnail)**
If you enable this, some of the style options may not work anymore (since old style is using shadows and this one is not).

**Comment by SLinxTheFox** [comment]
oh damn, yeah that was it, it's a shame though since i like that, but i can just remove the titles for now. thank you!

**Comment by fastaddons** [comment]
I'll try to look into that when I revisit the themes, make it more intuitive and easier to test (I plan to remove the Options page and make it part of the dials page).

**Comment by tockschmock** [comment]
I was not even aware of these style options (https://i.imgur.com/jYJU0te.png), since they do not show up without scrolling the dials options window and because the scrollbar for the  dials options window only shows up for about one second.
Maybe you can improve the visibility of all options.
