### ISSUE TITLE
Space on the screen - Question

### ISSUE THREAD

**Issue by afern247** [fastaddons/GroupSpeedDial#205]
Hi, first and foremost, very impressive firefox addon, I was looking for a replacement for the old Speed Dial [FVD] and I had given up, by luck I found yours and I'm very happy, even considering adding patreon.

Quick question, maybe anyone can answer it. How can I remove those two things that the yellow arrow is pointing to? Also can the top right corner hamburger menu be dimmed a little? It's kind of irrelevant once you do all the setup and you only care about your tabs.

![image](https://user-images.githubusercontent.com/34192856/204691594-9fe924d4-e93d-4921-bd48-7a7a64e12447.png)

**Comment by tockschmock** [comment]
this hides the "Plus"

![Screenshot 2022-12-05 00 05 40](https://user-images.githubusercontent.com/68165681/205521122-d675721e-45d2-47cd-89d0-b78092e18c6b.png)

**Comment by afern247** [comment]
That's not working for me. I currently have it like this and still see it:

![image](https://user-images.githubusercontent.com/34192856/205521355-bbdcea0e-b9ff-4df3-a558-957d085e0442.png)

@RemixPL1994 @tockschmock

**Comment by afern247** [comment]
Nop, that didn't do it:

![image](https://user-images.githubusercontent.com/34192856/205528450-24b5e01f-6efe-4d62-94e5-8703dbfe53f3.png)
![image](https://user-images.githubusercontent.com/34192856/205528477-a3091ebf-7ce6-428b-9fb2-0477a2a9e8ac.png)
