### ISSUE TITLE
SPEED DIAL DOES NOT WORK IN FIREFOX

### ISSUE THREAD

**Issue by dduran1210** [fastaddons/GroupSpeedDial#206]
**Describe the bug**
SPEED DIAL  CLOSES  FIREFOX  WHEN I CLICK ON THE "IMPORT/SETTINGS BUTTON."

**Steps To Reproduce**
CLICK ON OPTIONS -> IMPORT/ BACKUP -> IMPORT/SETTINGS

**Expected behavior**
EXPECT TO OPEN  THE SETTINGS DIRECTORY  TO IMPORT SAVED SETTINGS

**Device info:**
 - operating system:   LINUXMINT 20.0
 - Browser and version:   FIREFOX 107.0.1
 - GroupSpeedDial version:  21.8

**Additional info**
Add any other info about the problem here.
REINSTALLED FIREFOX TWICE.   REINSTALLED GROUP SPEED DIAL TWICE....

**Comment by fastaddons** [comment]
Hello,
The file input is a standard HTML element, so if it crashes, it's probably something in the Firefox.
Could you try to open some other input just to see if it works?
For example here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

If this is broken in Firefox, try to use Firefox reset to fix it:
https://support.mozilla.org/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by dduran1210** [comment]
i'm not too swift at this:   i see the input entries:   <input type="file"
       id="avatar" name="avatar"
       accept="image/png, image/jpeg">

but where do i put this stuff at ?   in a file somewhere?  not on the
address bar ,  right?

i am not a programmer....just a user.

thanks
Dave

**Comment by fastaddons** [comment]
In the top of the page in the "Try it" section there is a "Browse" input:
![image](https://user-images.githubusercontent.com/55486931/204895722-16c51a25-a022-426e-bdfb-ff21593a9f00.png)
Try to click it.

**Comment by dduran1210** [comment]
i did,  i click on it and it puts me on the desktop.....what am i looking
for ?    Choose a profile picture:  ????  what is a profile picture?

**Comment by dduran1210** [comment]
ok, I solved the problem.    i  restored a backup of linux light from  an
old March 2002 backup and Firefox automatically updated itself to v 107.
and

it works.   Don't know why or how, but thanks  for your time.  I appreciate
it very much.

**Comment by fastaddons** [comment]
Nope, that was just a test to see if opening a different file picker would fail.
So just to clarify, the tab is closed the moment you click on the import button here, right?
![image](https://user-images.githubusercontent.com/55486931/204897878-17850d5f-1026-409c-bcb0-c568d4fb1c5f.png)

**Comment by fastaddons** [comment]
Great :)
No problem.

**Comment by dduran1210** [comment]
no, it was not just closing the tab....it was shutting down firefox
completely
