### ISSUE TITLE
Resize dials?

### ISSUE THREAD

**Issue by jlinkels** [fastaddons/GroupSpeedDial#210]
I would like very much to resize the dials.

First, square dials is a a bit inconvenient when the browser window is mostly 4:3 or 16:9. Secondly (more important) almost all web pages are rectangles in 4:3 or so. It wastes a lot of space if the dials are square and fixed.

Do those resize dial settings not exist or am I not able to find them?

**Comment by fastaddons** [comment]
Hello,
Right click a group name (or open main menu) and select "Edit group".
There you can find many group layouts to fit your needs (hopefully :)).

**Comment by jlinkels** [comment]
Oh yes! Awesome!
See it was my fault I could not find it. I was trying to find this in Dial Settings. But since you allow this setting PER GROUP I should have looked there.
Thanks so much for your fast feedback.
