### ISSUE TITLE
Always syncing thumbnails

### ISSUE THREAD

**Issue by Locutus64** [fastaddons/GroupSpeedDial#214]
**Thumbnails always syncing**
For at least a week now every time I go to close my browser regardless of which browser I notice the thumbnails syncing. 

**Running the browser**

**to sync maybe once a week not on every use of the browser**

**Device info:**
 - operating system: Garuda Linux
 - Browser and version: Vivaldi 5.6.2867.50
 - GroupSpeedDial version: 21.8

**Comment by fastaddons** [comment]
Hello,
Could you export your dials and thumbnails to a file (from Options page / import backup tab), and tell me how big the file is?
Currently there is an issue with the synchronization if the quota is exceeded.
But I think I've fixed it in 21.9 version this morning.

**Comment by Locutus64** [comment]
it's 31.1 megs

**Comment by Locutus64** [comment]
Looks like you did something on your end cause now I get the quick sync again.

**Comment by fastaddons** [comment]
Thank you for the info!
Have a nice week :)
