### ISSUE TITLE
GSD not working in Safari after I paid

### ISSUE THREAD

**Issue by PeterAMcG** [fastaddons/GroupSpeedDial#215]
I have been using GSD for about a decade on Windows. I love it! And so does my wife. 

We are switching over to the MAC system and I noticed GSD doesn't work well in Safari. I can't edit the dials, move them around, or add dials to a new group. So I paid for GSD from the App Store. Same deal. I can not add new dials to a group. I can not move dials around, I can not edit an already created dial, and now I am out $35.

Can you help me? I simply want the functionality of the program that I had in Windows. How can I get this program to work in Safari? I have enabled the extension. I have given it all the permissions it has asked for.  The GSD button is on the Safari Toolbar and it works. But when I go to the 'dials' nothing works. Also, the only way to 'open' a link in GSD on Safari is by right clicking and choosing "open link in new tab". Double clicking on the link does nothing.

Thank you so much. I have currently given your app a one star review in the App Store and will gladly change it to a five star review when we get these issues worked out. I love this program and am so looking forward to getting it to work.

Thank you.

MacBook Pro 16" M1 Max - 64gb ram - 8tb had space
Ventura 13.1

Note: The speed dials I am using are coming from 
(https://group-speed-dial.fastaddons.com/cloud/#0

This is the website the safari extension takes me to when clicking on the extension icon.

Peter McGovern 
petermcgov@comcast.net 

**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: 
 - Browser and version: 
 - GroupSpeedDial version: 

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
Hello,
The extension for Safari is build from the same source code so (almost) everything should work same as on Windows.
If you can't move or edit dials, that usually means you are viewing a Cloud Dials web-page, which is not editable and it's meant to be used only on browsers where you can't install it, like on a phone.
Cloud dials web page has URL:
https://group-speed-dial.fastaddons.com/cloud
So make sure you are not using it on desktop.

Anyway, after installing it in Safari, you should see your dials page when you open New tab. Does this work? If not, please send me a screenshot of what you see in the new tab page.
You can also check the Safari settings page:
![image](https://user-images.githubusercontent.com/55486931/211187909-030cb766-4d87-423f-88e2-25dfc88f1861.png)

**Comment by Juraj-Masiar** [comment]
All my Safari extensions are now deprecated:
https://ko-fi.com/post/Im-done-developing-Safari-extensions-D1D3MYJPL

Please ask for refund in the App Store, they should be able to refund you. 
I'm sorry about these complications :(
