### ISSUE TITLE
Make Open all dials - in new tabs only open the dials in the group that is currently selected

### ISSUE THREAD

**Issue by Locutus64** [fastaddons/GroupSpeedDial#216]
I just went to open all dials in my Mandriva group so I could mopre quick go through the dials in that group and see which if any need to be removed, but when I rightclicked the group name and clicked Open all dials - in new tabs GroupSpeedDial proceeded to open every speed dial in every group. I would rather have it only create new tabs for the group I'm currently in.

**Comment by fastaddons** [comment]
Hello,
I can't reproduce it here.
I've also check the code and it looks impossible. Only dials in the clicked group are iterated.
Could you test it again, maybe with a different group?

**Comment by Locutus64** [comment]
Sorry for the late reply bot looks like you're right. What happened is instead of keeping the tabs in that tab stack collapsed  Vivaldi expanded the tab stack out. Once I realized that I collapsed it and the tab cout on the collapsed stack matched the number of dials under Mandriva.
