### ISSUE TITLE
"Options / Groups / Hide "+" button at the end of groups list" does not seem to work. 

### ISSUE THREAD

**Issue by FindlayCK** [fastaddons/GroupSpeedDial#217]
**Describe the bug**
As stated in title the "Hide "+" button at the end of groups list" toggle doesn't appear to function. 

Found under the Options / Groups tab.

**Steps To Reproduce**

Go to top right of browser page
Click menu icon (three horizontal lines)
Click on "Options" from drop down
Change tab to "Groups"
Toggle on (check mark) for "Hide "+" button at the end of groups list"
Save or save and exit.

**Expected behavior**

For it to hide the + box on group tabs.

**Device info:**
 - operating system: Windows 11 Pro v21H2 OS build 22000.1455
 - Browser and version: BRAVE [Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)](https://brave.com/latest/)
 - GroupSpeedDial version: 21.9

**Additional info**

Sorry if this is already known, I'm new to github and find its layout and functionality highly confusing, I tried to search for this issue prior to asking about it.

**Comment by fastaddons** [comment]
Hello,
I can't reproduce it here.
Also looking at the code responsible for rendering groups:
```
  if ($IS_EXT && !OPTIONS.HIDE_ADD_GROUP) {
    const addGroupNode = document.createElement('a');
    addGroupNode.onclick = () => addNewGroup({archived: isArchiveState, sourceGroup: activeGroup.getCurrentGroup()});
    addGroupNode.textContent = '+';
    addGroupNode.title = tr('cm_create_new_group');
    fragment.appendChild(addGroupNode);
  }
```
It's simply not possible for the "plus" to be rendered if the options value is checked.
The only possibility is that the options were not saved - could you check if the checkbox stays checked after reloading the options page?

**Comment by piotrnikov** [comment]
Hello!
Thanks for your extension!!
I'm having the same problem on Mac. Everything is checked and Saved. Yet the + sign is still there. Any ideas?
![Screenshot 2023-08-26 at 12 31 37 copy](https://github.com/fastaddons/GroupSpeedDial/assets/28474540/033506e1-7142-404d-bf64-aa036aa50a16)
![Screenshot 2023-08-26 at 12 31 47](https://github.com/fastaddons/GroupSpeedDial/assets/28474540/82822644-4365-436d-b94a-e2c60f86436e)
