### ISSUE TITLE
Questions about uploading and syncing thumbnails

### ISSUE THREAD

**Issue by JBBBB** [fastaddons/GroupSpeedDial#220]
I installed Group Speed Dial a couple of days ago in Firefox and Chrome on one computer; however, my plan is to sync speed dial across browsers (Firefox, Chrome, and possibly Edge) on several computers (Mac, Linux, and Windows).  I have 23 groups and just under 500 dials.  All but a few dials have custom thumbnails that I created carefully to be minimal size for best performance during use and when syncing.  The thumbnails range in size from 1 KB to 87 KB and average 27 KB.  They total 13 MB.  

I realized when syncing for the first time from Firefox to Chrome that thumbnails only synced if uploaded to the public library. 

1. What is the public library?  My thumbnails are only logos and graphics from public web sites, so I have no issues with anyone having read-only access to them; however, I would not want anyone having the ability to delete, or change, them. 
2. How secure is the public library?
3. Is there a global setting for uploading all thumbnails to the public library.  Uploading thumbnails individually for 500 dials will be torturous. 

I am impressed with Group Speed Dial so far, and expect to be a patron when comfortable and confident with it.  Thank you.

**Comment by irishrow** [comment]
Thank you for this product.  I'm using it cross-platform and cross-browser now with the Pro version.  Your advice to "Enable automatic thumbnails synchronization with the cloud server" solved the only problem I've encountered lately.  Please consider making that "option" a default.  All the best.

**Comment by Johnny531965** [comment]
Hi i'm doing this but don't see any synchronisation happening

**Comment by Juraj-Masiar** [comment]
Hello @Johnny531965 ,
Check this article for more info:
https://github.com/fastaddons/GroupSpeedDial/wiki/Synchronization-issues
