### ISSUE TITLE
Bing background image is no longer refreshing

### ISSUE THREAD

**Issue by andfinally** [fastaddons/GroupSpeedDial#224]
**Describe the bug**

The Bing image is a fabulous feature! I have "Bing image of the day" selected. It used to refresh daily, but hasn't done this for several days now. When I cycle through the images under Bing background > Next image, I only see stale images, not the latest one on Bing.

**Steps To Reproduce**

- Have "Bing image of the day" selected.
- Open a tab with GroupSpeedDial.

**Expected behavior**

- New Bing image appears in the background.

**Device info:**
 - operating system: macOS Ventura	
 - Browser and version: FF 109
 - GroupSpeedDial version: 22.1

**Additional info**
Add any other info about the problem here.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1647564/219720344-e6509137-7693-4e1c-bffa-1d214ce3e00b.png">

**Comment by andfinally** [comment]
I've just noticed I'm not getting this issue with the Chrome extension 2.2 – only Firefox 2.1.

**Comment by fastaddons** [comment]
Hello,
Thank you for reporting. I'll look into.
But I think I'll have to improve my logger so that it logs errors if there are any. That should help find the cause.
This will take a while so please be patient :).
One that that could help is exporting dials data from Chrome and importing them to Firefox, although I'm not 100% sure.

**Comment by fastaddons** [comment]
Also to verify, could you open this link in Firefox to see if it loads some data:
https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=8&mkt=en-US

It should look like this:
![image](https://user-images.githubusercontent.com/55486931/220115986-096bba7d-7612-4b58-9d11-b0fccd38f430.png)

**Comment by andfinally** [comment]
Thanks a lot Juraj... It's come right! 

- Went to Options > Background and chose the option "None". 
- Quit and restarted Firefox.
- Went to Options > Background and chose the "Bing image of the day" option.
- Bing background appeared.

Previously I had just tried changing the option to "None" and back without restarting the browser.

I am getting data from https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=8&mkt=en-US. (Unfortunately I wasn't able to check this before it came right, but my hunch is it was OK.)
