### ISSUE TITLE
Bing background image doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by TigBuh99** [fastaddons/GroupSpeedDial#226]
**Describe the bug**
I started using Microsoft Edge. I wanted to show the Bing image as background, but all I see as background is just a black area. I tried it on my Chrome browser and it works with no problem at all on that browser.

**Steps To Reproduce**
Go to SpeedDial Options and enable the Bing image of the day in the "Background" tab.

**Expected behavior**
It should show an image in the background and also change it with the SpeedDial menu.

**Device info:**
 - operating system: Windows 11 Pro
 - Browser and version: Microsoft Edge v. 110.0.1587.57 (Official build) (64-bit)
 - GroupSpeedDial version: 22.2

**Additional info**
I imported my dials and settings from my Chrome browser.

**Comment by fastaddons** [comment]
Hello,
I have a feeling this may be an cache issue. I think the cache record was imported without the cached data.
Could you NOT do anything for the next few hours to see if it fixes itself? The cache lasts about 4 hours. So try to restart Edge 4 hours from now to see if it helps.

I'll check the code in the meantime.

**Comment by TigBuh99** [comment]
Thanks for the response. Do you mean keep the browser open, but not to use it during this period or to close it and then restart it after the four hours have elapsed?

**Comment by fastaddons** [comment]
It can be closed, it doesn't matter. 
The cache is time based, so once the 4 hours pass, it should fetch a new data from bing.

**Comment by TigBuh99** [comment]
Unfortunately, nothing changed. I see a completely black background. :(

**Comment by fastaddons** [comment]
Thank you for testing this!
So I think if you disable the bing background (set background to none) and restart Edge and then turn it on again, it should fix the problem. At least that's what help in a similar case recently.

**Comment by TigBuh99** [comment]
Thank you for the suggestion. It didn't work, but I found the cause of the problem by a process of elimination. It's DuckDuckGo Privacy Essentials. As soon as I disable this extension and open a new SpeedDial the problem is gone.

I can add an unprotected website to DDG Privacy Essentials. Can I take advantage of this and add an exception to DDG PE for SpeedDial?

**Comment by TigBuh99** [comment]
Based on my testing I can only exclude domains in the DDG addon, for example www.bing.com. Thus again it doesn't work in Edge. If no easy answer may be found I'll remove DDG.

**Comment by fastaddons** [comment]
Hello again,
I've installed it in Edge to see if I could fix it somehow and although I could exclude the first link, it still wouldn't help since the DDG will block even the image load, which is really stupid:
![image](https://user-images.githubusercontent.com/55486931/222823561-8462d425-499f-45b4-91b4-4ec955734e16.png)

And sadly they don't support wildcards for the excluded links:
https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/533

So yeah, I don't see how to fix it. Their extension is really bad from the "features point of view", I mean the settings page.
In any case, I would say, having uBlock Origin installed or Adguard should give you similar kind of protection on the web.
Just remember to enable "Region / language" specific rules if you live outside of USA.

**Comment by TigBuh99** [comment]
Thank you for investigating this. I'll remove the DuckDuckGo extension and I'll be using uBlock Origin from now on.
By the way do you know how many images are provided by Bing? I counted eight. Does Bing add more to them from time to time?

**Comment by fastaddons** [comment]
Bing service can return information about up-to 8 images, see the "n=8" parameter in the URL:
https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&mkt=en-US&n=8

**Comment by TigBuh99** [comment]
Eight images with one being updated every day is more than adequate! Again, thank you for investigating this problem, finding the cause and closing it accordingly.
