### ISSUE TITLE
tabs and the tabs themselves disappeared from the screen

### ISSUE THREAD

**Issue by HugoBo-SS** [fastaddons/GroupSpeedDial#229]
**Describe the bug**
tabs and the tabs themselves disappeared from the screen

**Steps To Reproduce**
browser restart after extension update

**Expected behavioror**

**Device info:**
 - operating system: windows 10
 - Browser and version: Firefox 111
 - GroupSpeedDial version: 22.3

**Additional info**
after the update to 22.3, the groups of tabs and the tabs themselves disappeared from the screen

**Comment by fastaddons** [comment]
Hello,
Is there also an error message?
And could you send me a screenshot?
See also:
https://github.com/fastaddons/GroupSpeedDial/wiki/Fixing-broken-dials-page

**Comment by HugoBo-SS** [comment]
No error message, just a blank screen.
Also missing from the context menu
Maybe Is the extension start page broken?
Earlier it was displayed explicitly in the browser settings, now only the name.

**Comment by fastaddons** [comment]
Try to restart browser or whole PC.
And can you open popup window when you click the toolbar icon? Try to open it and then open Options page and try to export your data to a file.

**Comment by HugoBo-SS** [comment]
Export setting work.

Restart browser -did not help
Restart PC - did not help
Removing extension -> restart drowser -> install extension -> import setting - did not help

**Comment by fastaddons** [comment]
Was the addon working before you imported your data?
Please send me a screenshot of the new tab page, the broken one.

**Comment by HugoBo-SS** [comment]
The extension was functional until today's update.
Export-import still works.
Does not display groups of bookmarks and, accordingly, their bookmarks, and also does not appear in the browser context menu.

[2023-03-19_004916.pdf](https://github.com/fastaddons/GroupSpeedDial/files/11009694/2023-03-19_004916.pdf)
[2023-03-19_004806.pdf](https://github.com/fastaddons/GroupSpeedDial/files/11009695/2023-03-19_004806.pdf)

**Comment by fastaddons** [comment]
What Firefox version are you running? If it is a Firefox :)
This new version is now using some new API that's required by the upcoming "Manifest V3" upgrade so you need to have at least Firefox 102. But the addon should not upgrade if the browser is older, so something's wrong.

**Comment by HugoBo-SS** [comment]
Firefox 111

**Comment by fastaddons** [comment]
Try to install the previous one, 22.1:
https://addons.mozilla.org/en-US/firefox/addon/groupspeeddial/versions/
You will need to disable Auto-update in the about:addons page to prevent updating to last version.
What kind of Firefox are you running? It looks "unusual" :)

**Comment by HugoBo-SS** [comment]
This is a lotion )) :
https://github.com/Aris-t2/CustomCSSforFx/releases

22.1 works. Thanks

**Comment by fastaddons** [comment]
Hmmm.... the customCSS file should not interfere, but I think there is some javascript running that's not handling properly the new API.
I'll look into it, maybe report it to them.

**Comment by Ainson** [comment]
Same, everything disappeared today after updating Firefox extensions (Win 7 64, latest Firefox 111.0.1). Just a black page.

Tried all the fixes suggested like restarting, reinstalling etc, but nothing.

Reverting to the previous GroupSpeedDial version 22.1: got the extension working again.

(A backup gave me back my settings and dials, but not the thumbnail images, despite creating a backup with those included. I have to load all manually which is a PITA and probably the last time before I give up speed dial extensions altogether and revert to Firefox home default dials, as this will be my 4th or 5th thumbnail reinstalls and equally many speed dials extensions.)

**Comment by fastaddons** [comment]
@Ainson are you sure the backup has also thumbnails? See the file size, it should have above 1MB if it has thumbnails.
The backup restore should work without issues, if it doesn't, that would most probably point to issues with database store in your Firefox.
Let's try a simple experiment - install my addon into a different browser (Edge, Chrome, Firefox ESR, Brave) and try to import it there.

**Comment by Ainson** [comment]
The backup files are around 11MB so should be full of thumbnail images.

I installed your addon in Vivaldi and tried to import a backup there, but same issue. It loads a handful of images but stops after that.

I have several backups and tried them all so seems unlikely they would all corrupted.

Main issue is of course why the addon would completely stop working like that. There seems to be something inherently unstable with addons generally, as this is about the 5th speed dial I'm using after issues with all of them (all suddenly lost). Although GroupSpeedDial lasted the longest, so there's that.

**Comment by fastaddons** [comment]
This sounds very bizarre.
Could you please send me your backup file to my support email? Under full confidentiality.
If I can reproduce the issue, I can fix it.

I remember some issues in the past regarding restoring the backup, but the problem was "incomplete backup file" caused by corrupted record in the database which interrupted export. I think... 

In any case, @Ainson , could you please clarify - if you reinstall the addon, and you did restarted Firefox after uninstalling, the addon was still not working? Even when it was empty, without importing your backup file?

**Comment by Ainson** [comment]
Email with backup file sent to your support address.

And yes, confirm it was like that. Uninstall the addon, restart Firefox – all black page except the burger bar and an arrow top right corner, but none of them did anything when clicked. The addon was also missing from the right-click context menu on pages ('Add this Page to dial').

**Comment by fastaddons** [comment]
Thanks, I've tested it just now but it looks fine. All dials have a thumbnails.
I've tested it in Firefox ESR, Beta and also Chromium.

Are you sure you have imported the same file you've send me into the Vivaldi? It really should work.

Regarding the Firefox, if the addon is broken even after reinstalling, then something in your Firefox is most probably broken.
Try this simple steps:
1. open "about:profiles" page
2. click "Create new profile"
3. proceed creating new profile
4. once it's created, click "Launch profile in new browser"
5. install my addon there and try to import it again
Note that new profile is set as default so make sure to click "Set as default profile" button for your main profile to revert it.

**Comment by Ainson** [comment]
I made a new profile, started that, installed GroupSpeedDial and tried to import my backup, but no change. Just a few thumbnails show, and those seem to be the ones generated from the Internet. My own created custom thumbnails will not load.

As I spent this morning manually loading all my thumbnails in version 22.1, I tried to back up that and restore it in the new profile, but still the same.

It's the same in Vivaldi, so seems unrelated to Firefox. Windows 7? .NET? Java? SQLite?

**Comment by Ainson** [comment]
I just realized that after pressing the 'import settings and dial' button that it changes and says 'working'. After I let it finish and THEN click lower button 'Save changes and close', everything is imported as it should.

Before I just hit the 'import' button and then 'save changes and close' button immediately after, without realizing that a process must finish between those two.

Sorry for not realizing sooner, but maybe an idea to grey out the 'save changes and close' button during the import process to prevent similiar for others in the future.

The main issue of the latest 22.3 version not working still remains however.. It does work in a new Firefox profile, and also in Vivialdi. Just not in the main Firefox profile. It stopped working after I updated a lot of addons two days ago. Not sure if GSD was updated then.

**Comment by fastaddons** [comment]
We've exchanged few emails with @Ainson so yeah, the import will be improved to prevent accidental "interruption" when the import is in progress.

Now regarding the original issue - the broken 22.3 version, we've been able to identify the root cause - missing "[caches](https://developer.mozilla.org/en-US/docs/Web/API/caches#browser_compatibility)" API.

I would guess that the cache in your browser is disabled, let's try this to fix it:
1. open "about:config" page
2. using the filter look for "dom.caches.enabled" and check if the value is "true" (if it's false, double click it to switch it to true)

In any case, the cache was added only to help with background image when it comes from internet to prevent re-loading too often, so it's not crucial. I'll make it optional in the next release 22.4.
Still, some other addons or web pages may fail as well if they expect this API to be available, since there is no reason for modern browser to not have it available.

**Comment by Ainson** [comment]
That fixed it!

Thanks a lot for the fast help. So nice to have a good speed dial working.

**Comment by Juraj-Masiar** [comment]
Version 22.4 was approved today and it should fix the issue for everyone even with cache disabled.

**Comment by Ainson** [comment]
Can confirm 22.4 works even with "dom.caches.enabled" set to false
