### ISSUE TITLE
Can I hide the url text in the bottom left corner of the link window when hovering over the selector wheel shield?

### ISSUE THREAD

**Issue by RemixPL1994** [fastaddons/GroupSpeedDial#235]
Can I hide the url text in the bottom left corner of the link window when hovering over the selector wheel shield?

This is what the shield looks like when the cursor is not currently stopped in this place:

![obraz](https://user-images.githubusercontent.com/52541621/227898842-a83ee835-82b3-4431-b33c-4944b2c9c095.png)

And this is what it looks like when I hover over my shield:

![obraz](https://user-images.githubusercontent.com/52541621/227898975-82d9f503-f6be-4209-9d32-c2192c26e27d.png)

Because of this, I can't see what is written as text at the bottom in the caption of the shield because the url address covers it.

![obraz](https://user-images.githubusercontent.com/52541621/230800336-16a0d0ab-f5bc-4276-acea-56ffef153d5a.png)

Is there any way in addon to enable/disable some options or apply custom CSS style in your addon any special separate setting for mozilla firefox browser to hide showing this url text in bottom left corner when hovering over shield?

It would be nice if it worked.

![obraz](https://user-images.githubusercontent.com/52541621/227900833-f2ba0143-52d3-4a53-967f-7d8e89bf6db3.png)

**Comment by Juraj-Masiar** [comment]
Nope, this is a browser feature.
However, using special "userChrome.css" file you can alter Firefox and I'm pretty sure this would be possible.
More info about that here:
https://www.userchrome.org/
You can try to google it or ask community here:
https://www.reddit.com/r/FirefoxCSS/
