### ISSUE TITLE
Can we add manual single favicon hiding for individual shields?

### ISSUE THREAD

**Issue by RemixPL1994** [fastaddons/GroupSpeedDial#236]
Can we add manual single favicon hiding for individual shields?

![obraz](https://user-images.githubusercontent.com/52541621/227902698-25e367b1-1bda-4e19-9f75-a459e2a85dac.png)

I would love to hide the favicon icons wherever I have a set of pages in my shield and leave them where I have individual pages.

I marked in green and red how I would like it to look.

Red - no favicon.

Green - favicion visible.

Of course, I know that it is possible to hide the entire shield signature at the bottom, but then the text also disappears.

As you can see in my screenshot I also use shields like gta5mods or gtaforums where it looks more transparent for them.

A solution to make the favicon disappear but the text remain would be really great. I would use this for other individual dials to further improve the clarity of the whole :)

**Comment by Juraj-Masiar** [comment]
Sure thing, next version (22.5) will have "Edit dial / Visual / Hide dial favicon" option.
