### ISSUE TITLE
Troubleshooting: Data Storage Edge Case

### ISSUE THREAD

**Issue by github1otez** [fastaddons/GroupSpeedDial#241]
Hi Juraj, not a bug report for your end, just a little help requested to navigate my way through where FF will have stored your extension data (another user mentioned some automatic backup/history locations in another issue from January?). 

C drive was filled with 50GB of Crusader Kings 3 crash logs, so I had no disk space available. I fixed as soon as I noticed and I only noticed anything strange had happened when I opened FF, all my dials were gone. This was today, there hasn't been a FF update I've noticed, and nothing in my dials has changed for weeks...so I'm hoping there is a cache somewhere I can recover!

I believe the drive being full and the extension data being lost are related, as it was only for a minute or so that the drive was full, and until then I had been using FF with all my dials just fine. But openeing FF with the full drive, my dials were gone. They have not returned on a FF restart, or a system reboot. Perhaps FF tried to write a new history file and had no space? I would *hope* that FF wouldn't delete the old file before successfully verifying the creation of a new one!

Thanks!
Mat

**Comment by fastaddons** [comment]
Hello,
See this recovery article for more info:
https://github.com/fastaddons/GroupSpeedDial/wiki/Recovery-of-your-dials,-how-are-dials-stored-and-how-to-make-a-backup

Please let me know if info there doesn't help.

**Comment by github1otez** [comment]
Thanks, the History Feature is brilliant! Coffee inbound for the help :)

**Comment by fastaddons** [comment]
Hurray :)
I'm happy it worked!
I've invested a lot of time and effort into backing up data into different storages and then making them available through the History, so every time it helps someone it makes me supper happy I did that :)
