### ISSUE TITLE
Group Speed Dial

### ISSUE THREAD

**Issue by 2journey** [fastaddons/GroupSpeedDial#243]
The Group Speed Dial Addon to Chrome doesn't seem to work. The addon works fine with Firefox. Sadly, Firefox doesn't function well with Youtube. How to fix the Addon?

**Comment by Juraj-Masiar** [comment]
Hello,
I'm sorry for the delay, my notifications were disabled for moment...
Could you give me more info? Mostly Chrome version.
Also, what do you see on the dials page in Chrome?

**Comment by 2journey** [comment]
Hello Mostly Chrome. The Addon is enabled, however doesn't show up on navugation bar. The addon works with Firefox. I don't use Firefox much because browser is terrible with Youtube.

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 13, 2023 at 6:17 AM, Juraj ***@***.***> wrote:   


Hello,
I'm sorry for the delay, my notifications were disabled for moment...
Could you give me more info? Mostly Chrome version.
Also, what do you see on the dials page in Chrome?

**Comment by Juraj-Masiar** [comment]
I'm sorry for the huge delay again :),
If you still have this issue, click the "jigsaw puzzle" icon on the toolbar and look for my extension icon there - Chrome is now by default hiding all extensions there.

**Comment by 2journey** [comment]
Good news...Mystery solved! The functions of Chrome web browser changes so much. I clicked the "jigsaw puzzle" icon on the toolbar, looked for group speed dial extension icon and literally click the pin, in order for Group Speed Dial to be visible. Dear Lordy!
