### ISSUE TITLE
Setting to "always open in new tab" is suddenly intermittent

### ISSUE THREAD

**Issue by FloridaGal** [fastaddons/GroupSpeedDial#247]
**Describe the bug**
In the last day or two - out of the blue - my default setting to "always open dials in a new tab" is working intermittently. I haven't added anything new, but Firefox has recently updated. Thanks for any help in getting this resolved, it isn't major but it is inconvenient. Cheers!

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: Windows 11
 - Browser and version: Firefox 112.0.1 (64-bit)
 - GroupSpeedDial version: 22.4

**Additional info**
Add any other info about the problem here.

**Comment by Juraj-Masiar** [comment]
Hello,
Could you please describe the problem more? What does the "intermittently" mean? Will the page open in current tab or not at all?
Also, does this happen only with some specific dial?
And lastly, which of these options do you have enabled?
![image](https://user-images.githubusercontent.com/6358971/233767275-4d97d9b8-1b0f-4369-bcab-8e1de47a5e99.png)

**Comment by FloridaGal** [comment]
Hi Juraj,

I need to use it for a bit more time to see when it happens exactly and I will get back to you on that.

By intermittently I mean sometimes it does exactly what it’s supposed to and other times it opens in the tab containing the dials instead of in a new tab.

In the meantime I’m attaching captures of my settings as requested.

Cheers and thanks!

Linda Farmer
