### ISSUE TITLE
Thumbnails not syncing between browsers

### ISSUE THREAD

**Issue by danbarns** [fastaddons/GroupSpeedDial#255]
![Screenshot 2023-05-22 162514](https://github.com/fastaddons/GroupSpeedDial/assets/116592728/e50e8e39-da38-450b-9556-64227036909e)

My dials are syncing between browsers, but thumbnails are not; neither between Firefox and Chrome not between Chrome profiles. I am using the same account and am clicking on the sync button. I have even tried changing a thumbnail and syncing to no effect.

From left to right: Firefox, Chrome Profile 1, Chrome Profile 2

**Comment by Juraj-Masiar** [comment]
Hello,
Did you enabled Thumbnails synchronization on each browser?
You need to do it manually from Options page / Thumbnails.

**Comment by danbarns** [comment]
Thanks for that suggestion. One browser was off, 2 were on. Even the 2 that were on aren't syncing. I added thumbnail sync to the 3rd, clicked manual sync button and no effect.

**Comment by Juraj-Masiar** [comment]
Regarding the sync thumbnails logic, when you connect new device into the sync, only missing thumbnails will be downloaded.
So all existing thumbnails will stay there and they will start synchronizing only if they change again (on any of the devices).

So one simple solution would be to uninstall my addon from the device, restart the browser and install it back. Then enable thumbnails sync and all data should get downloaded.

Or you can export data to a file and import it to the other device/browser.

**Comment by danbarns** [comment]
The export/import worked. I tested by adding a new dial and adding a new thumbnail and syncing across all browsers seems to be working. Thanks!

**Comment by Juraj-Masiar** [comment]
I'm happy to hear that :)
Have a nice weekend!
