### ISSUE TITLE
Opening an Incognito Window on Brave / Vivaldi works but generates Error :( "Cannot read properties of null (reading 'tabs')"

### ISSUE THREAD

**Issue by SplittingDistant** [fastaddons/GroupSpeedDial#257]
**Describe the bug**
Opening an Incognito Window on Brave / Vivaldi works but generates Error :( "Cannot read properties of null (reading 'tabs')"
May also happen with other Chrome based browsers (I am unable to test), but does not happen with Firefox based browsers
**Steps To Reproduce**
Happens every time  Incognito window is opened
**Expected behaviour**
Error message should not appear
**Device info:**
 - operating system: Win10
 - Browser and version: Brave & Vivaldi (latest versions)
 - GroupSpeedDial version: 22.8
**Additional info**
Incognito windows also open at reduced size, but this may be as per design.

**Comment by SplittingDistant** [comment]
Hi Juraj-Masiar,

Many thanks for the quick response!

Here's the Screenshot:

![Screenshot (24)](https://github.com/fastaddons/GroupSpeedDial/assets/2060794/c2c521ee-d82f-43a8-8c03-9cd51dad3ccd)

The Incognito Window was opened by Right Clicking  the dial and selecting "Incognito Window". 

The group list is visible, as tabs across the top of the window. I don't use the "recently closed dial" facility.

The screenshot is of a specially created group to prevent my personal group names appearing on the screenshot.

I've tested with all extensions turned off and the still issue occurs. 

I hope this is of use to you.

**Comment by SplittingDistant** [comment]
Many thanks Juraj.

**Comment by Juraj-Masiar** [comment]
No problem :)
I've just finished implementing the fix so it will be part of the next release. Probably next week because I want to implement a few more things.
