### ISSUE TITLE
"Hide "+" button at the end of groups list"  only works for Cloud Tabs

### ISSUE THREAD

**Issue by arroznegro** [fastaddons/GroupSpeedDial#260]
Not sure if this is a bug or a feature.

If using the local SpeedDial, the "+" button is persistent, no matter the setting in the options. 
If I use the Cloud Dials, the  "+" button is gone.

Cloud Dial:
![Cloud Dial Screenshot_2023-06-09_08-59-48](https://github.com/fastaddons/GroupSpeedDial/assets/52073152/46aee2fb-3c8d-4a36-9102-0ef9fa5356d3)
Cloud Dial settings:
![cloudScreenshot_2023-06-09_09-04-17](https://github.com/fastaddons/GroupSpeedDial/assets/52073152/47a93331-e27b-4d76-a470-245cdc7e099c)
Local Dial:
![Local DialScreenshot_2023-06-09_09-02-15](https://github.com/fastaddons/GroupSpeedDial/assets/52073152/a4469ed1-a75a-4555-8dbf-d300b4047087)
Local Dial settings:
![localScreenshot_2023-06-09_09-03-22](https://github.com/fastaddons/GroupSpeedDial/assets/52073152/6b0d6ad4-d4ce-45c2-a81e-e1b7dbbdf34c)

Are there other settings I need to look at?

Thanks.

**Device info:**
 - Arch Linux 
 - Firefox Version 114.0 
 - GroupSpeedDial version: 22.8

**Additional info**
Add any other info about the problem here.

**Comment by Juraj-Masiar** [comment]
Hello,
Cloud dials are currently not editable, so the plus button is hidden by default.

Also, unrelated, in the Options page / Thumbnails tab, you can enable thumbnails synchronization and you will see your thumbnails in the cloud dials page too.
