### ISSUE TITLE
Group Icon are not synchronised

### ISSUE THREAD

**Issue by dJeePe** [fastaddons/GroupSpeedDial#264]
**Describe the bug**
It seems that the group icons are not synchronized between the different versions (Chrome, edge and cloud).

**Steps To Reproduce**
- Add a group icon on chrome
- the icon does not appear on the edge version
- the icon does not appear on the cloud version by a space is added

**Device info:**
 - GroupSpeedDial version: V22.9

**Additional info**
Chrome version with a icon :
![image](https://github.com/fastaddons/GroupSpeedDial/assets/85245954/2aee8c7d-0f4e-4167-8315-ec86f1f6c1d5)

Cloud version with a space :
![image](https://github.com/fastaddons/GroupSpeedDial/assets/85245954/ec577fdf-0c71-4727-8181-d0876bb94a84)

Edge version with nothing :
![image](https://github.com/fastaddons/GroupSpeedDial/assets/85245954/0a4bdc42-2c51-4ef7-a9ff-e8cbd959b37d)

**Comment by Juraj-Masiar** [comment]
Hello,
Make sure your Edge is using the last version 22.9. I've just noticed the Edge store was a bit slower approving my update so some users may be still using 22.8 version.
If the icons are still missing after the update, try to change something in the Chrome and let it sync to Edge.

Regarding the Cloud, that's indeed broken. I'll try to fix it now.

**Comment by Juraj-Masiar** [comment]
Cloud has been fixed now :)
