### ISSUE TITLE
Add Page to Dial

### ISSUE THREAD

**Issue by eethom** [fastaddons/GroupSpeedDial#269]
**Describe the bug**
Add Page to Dial intermittent, on most occasions one has to open the group first in another tab before the page can be added.
Even then it it sometimes random and takes 2 attempts

**Steps To Reproduce**
Have many groups - I have around 48 Groups

**Expected behavior**
Should add dial without problems

**Device info:**
Windows 10: 
Microsoft Edge: Version 114.0.1823.79
 - GroupSpeedDial version: 22.9

**Additional info**
Happens also on Chrome & Firefox running their latest versions

**Comment by Juraj-Masiar** [comment]
Hello,
This feature has been buggy for some time and I lost count how many times I've been fixing it and I can't believe it's still not fully fixed (since last version 22.9 fixed two issues related to this).

Could you describe what exactly happens when it doesn't work?
The normal process is - you click "Add this page to dials", dials page opens, you navigate and click target dial, exit action popup is displayed.

I need exact steps to reproduce the issue and if I can reproduce it here, I'll do my best to fix it (hopefully for good this time).
One last question - does this break when there is a duplicate of the page detected?

**Comment by eethom** [comment]
Thanks for your reply

Let me check it over the next few days

As it seems to be working now - perhaps the V22.9 updated fixed the issue.

The reason I say this is because for quite some time I have been using a workaround and manual adding a website I wanted to keep by going to the group where I wanted to store a page and clicking + box to copy and paste the URL in.
Add page to dial has let me down so much that I thought a page was being added and later finding out it was not.
Perhaps a popup would be good here to indicate successful ADD

**Comment by eethom** [comment]
Yes it still occurs intermittently
Add page to Dial
Picked a random URL to add to group called Peru
See attached screenhots
Selected add  dial to group Peru then nothing happened in the browser
Then Going to Peru group - there is not a new dial
![image](https://github.com/fastaddons/GroupSpeedDial/assets/129281754/eb8ceca2-e9ac-4fe0-9e88-41248d8a2a6c)

![image](https://github.com/fastaddons/GroupSpeedDial/assets/129281754/d09a5018-a911-405a-8b3d-554390b680e6)

**Comment by Juraj-Masiar** [comment]
I see, so this happens when using this special "fast insert" mode. I thought you mean the normal mode where the dials page opens and you choose where to insert it.

I'll investigate it now.

**Comment by Juraj-Masiar** [comment]
So, I've checked the code and everything looks fine.
The only way for it to fail is if there is already such page in the target group, then it would not add it.
Could you next time check the dials page / Main menu / History - and see if the first entry there is the "dial edited - group '<your group name>'; Dial: '<name of the dial'>".

Maybe you miss click and selected another group (one above/below)? :)

In any case, I see I'm missing some "feedback loop" there.
I need to implement some easy pop-up that would tell user "Success", "Duplicate detected - page is already in the group", "Failed" (although so far I can't see any way for it to fail, except for total storage breakdown but that's unlikely).
I'll try to build something like this for the upcoming release.

**Comment by eethom** [comment]
Hi
As the screenshots show the url was not in the target group
There was nothing in the history related to adding this dial.

Here is the stats for reference:
Dials info 
Groups: 244
Dials (not empty): 7,559
URL dials: 7,559
Group dials: 0
Search dials: 0
Live dials: 0
Multi dials: 0
Multi dial links: 0
Text dials: 0
Auto reload dials: 0
Data size 
IndexedDB (img + back): 356.0MB
storage.s: 113.0B
storage.l: 1.4MB
localStorage: 61.0KB
Dials: 2.9MB
Options: 2.7KB

I guess I will continue to use my manual method until you add the success popup to confirm I added the URL to a group

thx

**Comment by eethom** [comment]
Issue Resolved.
The clue for me was in the stats above
Groups showed 244, I should only have 48 groups
The DB had 5 copies of these groups.
Deleting the duplicated to:
Dials info 
Groups: 48
Dials (not empty): 1,562
URL dials: 1,562

The add page to dial now works.
Looking forward for the success popup update
Thanks

**Comment by Juraj-Masiar** [comment]
Yes, it's already in progress, look :)
![image](https://github.com/fastaddons/GroupSpeedDial/assets/6358971/2d2f0944-9b87-4153-9654-a631c0155d9a)

Can you tell me how did you ended up with so many duplicate groups?

**Comment by eethom** [comment]
Hi

Love that success graphic.

Duplicated groups - why?
My guess is that I use Group Speed dial on 4 different computers, and I exported the dials with thumbnails.
I used this export file and imported into the other 3 PC's to save the downloading of all the thumbnails.
I guess that each time I imported the dials  - it added them to the online sync DB

**Comment by eethom** [comment]
Thanks Juraj

The latest release with the success popup is brilliant.

**Comment by Juraj-Masiar** [comment]
I'm happy you like it :).
There is also big red popup if the operation fails (but you should never see it), which already helped me find the root cause of the bug you've originally reported. It was indeed failing in some cases if you didn't have dials page opened "recently"...  a "race condition" type of bug (one of the worst type).
