### ISSUE TITLE
Better organizing support - moving multiple dials

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/GroupSpeedDial#27]
Doing some cleanup in your dials is really hard because it has to be done one by one.
Usually editors supports some "Select mode" where you can click on many items to mark them and then do some action with all of them.

**Comment by Mav3r1x** [comment]
Any update on this?

**Comment by fastaddons** [comment]
Sorry, not yet.
I'm now finishing a huge upgrade that took me so many weeks (or months). Also there is now many pressing things waiting in line...
But the good news is that after I finish this, it will be much easier to add some of the new features because the "Edit dial" and "Edit group" windows are now build with new Vue framework and material design (which finally supports dark mode!).

**Comment by Mav3r1x** [comment]
Oh, that's exciting. When do you plan to release the new upgrade?

**Comment by fastaddons** [comment]
The plan was like a many weeks ago :D
All the features are done, I'm just testing and fixing bugs now.
But there is a whole bunch of things I have to do before the release (merge new translations, fix automated tests, prepare release notes, etc...) so if things go well, it will be by the end of this week.

**Comment by FAdamfamily** [comment]
> The plan was like a many weeks ago :D All the features are done, . . . . . . it will be by the end of this week.

Im still waiting for the end of this week
FA

**Comment by fastaddons** [comment]
Oh  man, I can't believe the time goes so fast. 
But I'm adding multi-select feature right now, it will be part of the next release 19.9 very soon and it will allow easy selecting and moving of multiple dials.

**Comment by fastaddons** [comment]
Hello,
19.9 was just released in Firefox (Chrome version is still in review queue) with a new "Dials selection" feature:
- you can now activate "Select dials" mode
- click or select dials you want to move
- right click to access context menu and click "Cut"
- then right click and "Paste" dials in target group
- more operations and a status bar / command bar / duplicate finder will be added soon
