### ISSUE TITLE
Invalid credentials on login and resetting password

### ISSUE THREAD

**Issue by kidtom** [fastaddons/GroupSpeedDial#275]
I've tried to login to my account and get a message that I have invalid credentials. I click on forgot password thinking if I changed my password it would solve the problem. After proving I'm human, I click on the button to reset password. Then I get redirected back to the login page with no apparent way to reset my password. I'm just running around in circles. How do I reset my password? I thought I would receive an email with a link to reset it, but I have yet to find a way to do so and can't get into my account. 

![Screenshot 2023-08-20 131646](https://github.com/fastaddons/GroupSpeedDial/assets/142746181/d6013d3c-2227-4916-ba61-afe5f9a4842c)

![Screenshot 2023-08-20 131728](https://github.com/fastaddons/GroupSpeedDial/assets/142746181/e3a02ee6-f84a-4821-876b-69fe80d082f8)

![Screenshot 2023-08-20 131759](https://github.com/fastaddons/GroupSpeedDial/assets/142746181/64c857d2-b4ac-4eec-963a-fffa79de4c3d)

**Comment by Juraj-Masiar** [comment]
Hello,
Maybe your account was created using your existing google account - in that case there is no password to reset and all you have to do is click the Google icon provider.

**Comment by kidtom** [comment]
No, I didn't create it with my Google account.  What good is the button to reset password if it just sends me back to the original login page? I don't know if this is a glitch or what.

**Comment by Juraj-Masiar** [comment]
The reset password will send you email with reset link to your email address. If you are not receiving the reset link it either means there is no such account or that the account doesn't have a password.

**Comment by kidtom** [comment]
I use a password manager so the username and password were there when I created the account.

**Comment by Juraj-Masiar** [comment]
Any chance you deleted your account in the meantime? :)
Could you send me your email used for registration? I can check it in the database. You can send it to my support email: admin[at}fastaddons[dot]com

**Comment by kidtom** [comment]
No, hadn't deleted the account that I can remember. I just hadn't logged into my account for some time. I'll send you the email.

**Comment by Juraj-Masiar** [comment]
I've checked the server for the email you've send and there is no such account :).
Are you 100% sure you've created one?
In any case, unless you are trying to recover your data, you can just create new account and problem is solved :).

**Comment by kidtom** [comment]
Yes, I'm sure because there's no reason I would have had the login credentials in my password manager otherwise. It's possible I might have deleted the account although I don't remember doing it. I have a pretty crappy memory anymore. That would be the only explanation I suppose. I did have some dials created and didn't want to start from scratch, but no big deal. Thanks for trying to sort it out for me. I guess maybe I need a memory manager as well.

**Comment by Juraj-Masiar** [comment]
Well, that sounds like the only explanation since I'm not deleting any accounts either so it should be there.
I'll go sleep now since it's one hour before midnight here so if you need further assistance, I'll be back in ~10 hours :). Good night!

**Comment by kidtom** [comment]
Nope, you can close this one. Thanks.
