### ISSUE TITLE
no new subjects or tabs

### ISSUE THREAD

**Issue by insbrian** [fastaddons/GroupSpeedDial#277]
**Describe the bug**
when the app opens there is no ability to create a new topic or ad a tab to an existing one
**Steps To Reproduce**

**Expected behavior**
usually there is a plus sign to add a tab or something to add a topic

**Device info:**
 - operating system: windows 10
 - Browser and version: firefox 117.0, current versions of opera, vivaldi, and brave
 - GroupSpeedDial version: cannot find version number

**Additional info**
Add any other info about the problem here.

![image](https://github.com/fastaddons/GroupSpeedDial/assets/107693808/cf621bc9-16a0-4ebd-86e0-df1681264b27)

**Comment by Juraj-Masiar** [comment]
Hello,
You are probably viewing a cloud dials webpage:
https://group-speed-dial.fastaddons.com/cloud/
Which works in every browser (even phones) but it's not editable.

To edit your dials, install the addon the browser you are using. For chromium based browsers you can install it from here:
https://chrome.google.com/webstore/detail/group-speed-dial/imfeikbeimbfpmgfkkmjekabdehiiajc

**Comment by insbrian** [comment]
Something else is going on. I have it installed on firefox and 3 other
chrome browsers. This is not the cloud version. This just happened very
recently. I coudn't say the exact day. the version is 23.1

firefox installed
[image: image.png]
and nothing has changed
[image: image.png]
still not able to to add anything
same issues on the chrome browsers

vivaldi installed
[image: image.png]
no change
[image: image.png]

brave installed
[image: image.png]

no change
[image: image.png]

opera installed

[image: image.png]

no change
[image: image.png]

I have no idea how or why this is happening. I use your app all day every
day. I hope you determine what the issue is

Sincerely,

Brian Sanet

**Comment by insbrian** [comment]
all fixed!!!! you truly are a magician

Sincerely,

Brian Sanet

**Comment by insbrian** [comment]
i take it back. firefox works but the chrome apps still out of action

Sincerely,

Brian Sanet
Sanet Insurance Brokerage
201-391-3434    www.insbrian.com

If you've liked my service , a referral is the greatest compliment you can
give me.


10,000 people a day are turning 65! Are you one of them? We can help you
with all your Medicare questions and help you enroll .

**Comment by insbrian** [comment]
i take that back . im an idoit

Sincerely,

Brian Sanet
Sanet Insurance Brokerage
201-391-3434    www.insbrian.com

If you've liked my service , a referral is the greatest compliment you can
give me.


10,000 people a day are turning 65! Are you one of them? We can help you
with all your Medicare questions and help you enroll .

**Comment by Juraj-Masiar** [comment]
Hello again,
I hope it works now. I should change the cloud dials to make it more clear it's the cloud version.
