### ISSUE TITLE
Store the Container Tab type to use by default with a dial.

### ISSUE THREAD

**Issue by lgvr123** [fastaddons/GroupSpeedDial#279]
In Firefox, one can open URL in special Container Tabs. 

When using GroupSpeedDial, the default container tab is the "No Container" type. One can right-click the dial to select another Container Tab type.

Among the dials, some dials are meant to be always open in a dedicated Container tab type. 

Today this situation always requires a right-click on the dial and the selection of the correct Container Tab.

The suggestion is to be able to store which Container Tab to use by default dial by dial. The default value being "No Container". 
The benefit would be that when clicking on a dial it would automatically be opened in the right Container Tab type.

An extra feature would be to define a default Container Tab type at the level of the group too.
The benefit would be that every dials of the group would open (unless they have another default set) in that Container Tab type without requiring a default being set dial by dial.

**Comment by Juraj-Masiar** [comment]
Hello,
Well, I have a good new and bad news.
The good news is, it's already implemented.
The bad news is, it's payed feature available only with PRO license:
https://github.com/fastaddons/GroupSpeedDial/wiki/PRO-version-features#firefox-containers-support

I mean assigning dial to a specific container (in the Edit dial / Setting tab).
Assigning group to a container has not been implemented yet (it's on my todo list though).

In any case, if you assign a domain to a specific container using the Firefox Containers feature, it should get opened in the assigned container if you open it by clicking on a dial.

**Comment by lgvr123** [comment]
The good news is that I already have the PRO license. And that I found the option. I didn't search far enough in the dial's option ! Should I close this ticket ? Or reformulate it to limit it "Assigning group to a container" ?

**Comment by Juraj-Masiar** [comment]
Let's keep it open for the group container feature.
It should be fairly easy to implement so I'll try to do it today (so it will be part of the upcoming 23.2 release).
