### ISSUE TITLE
Thumbnails don't resize when changing the Dial size

### ISSUE THREAD

**Issue by Mav3r1x** [fastaddons/GroupSpeedDial#29]
I tried using [this image](https://i.imgur.com/y3caJBu.png) as a thumbnail, but on the dial it shows like [this](https://i.imgur.com/zMyvQDg.png). And when changing the dial to a smaller size, it goes further [out of focus](https://i.imgur.com/YEDawNb.png). Ideally the image should resize, so it is completely visible.

**Device info:**
 - operating system: Windows 10
 - Browser and version: Chrome v87
 - GroupSpeedDial version: 15.2

**Comment by fastaddons** [comment]
In the "Edit dial" window / Thumbnail tab / "Position:" you can change the thumbnail position to "Center (contain)", that will keep the image in the middle and fully visible on all sizes.

**Comment by Mav3r1x** [comment]
wonderful. thanks.

**Comment by Mav3r1x** [comment]
Any way to do this for all dials at once?

**Comment by Juraj-Masiar** [comment]
Not really, but if you need to do it for a new dial, you can copy existing (for example with drag and drop while holding "Ctrl") and then change URL.

Also if you use right click on an image (on some website) and select "Use this image as thumbnail" and then select some dial, it will automatically use the center position.

I'm thinking, maybe when I do the "edit mode" with multiple selected dials, I could allow opening "Edit dial" window with some options enabled/disabled which would be then applied to all dials...
Or maybe do it on the Group level in the Edit group window? I have to think this through...

**Comment by Mav3r1x** [comment]
> (oh man, I've used wrong account here again :D)
LOL. doesn't matter.

I guess you could implement both methods. whatever you think is more efficient.

**Comment by fastaddons** [comment]
I agree, eventually it should be both methods. The group level settings is a must and editing of selected dials is just super useful and should be easy enough, I just need to iterated selected dials and apply settings on each one.
