### ISSUE TITLE
how do i get the link to install group speed dial on firefox v102 ?

### ISSUE THREAD

**Issue by dduran1210** [fastaddons/GroupSpeedDial#295]
can you post a website showing gsd for older firefox versions. ?

i

**Comment by Juraj-Masiar** [comment]
Hello,
You can find previous versions here:
https://addons.mozilla.org/firefox/addon/groupspeeddial/versions/

Last one compatible with Firefox 102 is 23.0.

**NOTE that Firefox ESR 102 is no longer supported by Mozilla and is now missing security updates so it's highly recommend to upgrade to Firefox ESR 115.**

Stay safe :)
