### ISSUE TITLE
Add page or link to dial

### ISSUE THREAD

**Issue by 2journey** [fastaddons/GroupSpeedDial#301]
On navigation menu, after right clicking the Group Speed Dial, there is no Add page or link to Group Speed Dial. Before I was able to. Under Options, I have checked the box to enable. Did I miss something?

Windows 10
Chrome 117
Group Speed Dial 24.6

**Comment by Juraj-Masiar** [comment]
Hello,
This sounds interesting... I'm not sure though how the right click the popup works and didn't know people are using it.
The common way is the left click which should by default open the popup window where you have the "Add this page to dial" button on the left side.
Alternatively, right click on a page should show context menu where is again "Add this page to dial" option.

But I can see the right click on the toolbar icon can also show custom menu item, so I guess I can add it there. I'll try to do it now so it should be part of the next release (probably in a week or so).

**Comment by Juraj-Masiar** [comment]
I have the fix ready now, so it will work in the next version:

![image](https://github.com/fastaddons/GroupSpeedDial/assets/6358971/7306f94e-623b-4882-a044-d2c2e84fa717)

But I'm only starting work on the new release so please be patient...
Thank you for reporting this!

**Comment by 2journey** [comment]
Can I switch back to the previous version?

**Comment by Juraj-Masiar** [comment]
Sadly, not in Chrome, only Firefox store supports installing previous versions. Chrome store doesn't store past versions.
But I'm a bit confused, I haven't removed the menu item in the last version, I don't think it was ever there so downgrading wouldn't fix it.

**Comment by 2journey** [comment]
Hmm...I've been using Group Speed Dial with Chrome browser for a long. May have just solved my problem...do donations for plugin expire? Is there a record of my purchase? The Add this to dial is enabled through donation.

**Comment by Juraj-Masiar** [comment]
Well, officially the PRO version is only for Patreon supporters. 
People that donate sometimes gets 1month per dollar (or euro) of PRO version.
There should be a record of your donation, look for some email from PayPal or "ko-fi.com", depending on what you used. Or send me email with your email address and I can check it here.

**Comment by 2journey** [comment]
OK, I attempted to find a record of transaction on my end, however sadly couldn't. The email address should be under  LFUNG7@YAHOO.COM.

**Comment by Juraj-Masiar** [comment]
Hello again,
I can't find anything either.
But let me upgrade you for 12 months for free.
Enjoy! :)
And happy new year!

**Comment by 2journey** [comment]
Hi there,Thank you for the upgrade! Now, how do I Add a link to the dial? Normally, I would click on Group Speed Dial icon on navigation menu to login and then, click the same icon and the context menu shows up. Currently, I need to right click and then? Attaching screenshot.
-Leslie
    On Friday, January 5, 2024 at 01:39:49 AM PST, Juraj Mäsiar ***@***.***> wrote:  
 
 


Hello again,
I can't find anything either.
But let me upgrade you for 12 months for free.
Enjoy! :)
And happy new year!

**Comment by Juraj-Masiar** [comment]
Hello,
I'm sorry for the delay.
The normal approach is that you click the toolbar icon and then click "Add this page to dial", like this:
![image](https://github.com/fastaddons/GroupSpeedDial/assets/6358971/a988dadc-f1ae-4cb0-ab04-0cdd21d35233)

Or from the context menu:
![image](https://github.com/fastaddons/GroupSpeedDial/assets/6358971/132f5614-249b-478b-8ef6-898052fc02dc)

PS: this is a github notification email, you can't send it an image through email, only using the web interface:
https://github.com/fastaddons/GroupSpeedDial/issues/301

**Comment by 2journey** [comment]
Hi there,
When I right click the Group Speed Dial icon on navigation menu, my Add This Link/Dial dashboard looks different as well as the Context Menu. I have attached a screenshot of both. Hope you can open this files.
![groupspeeddial-error-3](https://github.com/fastaddons/GroupSpeedDial/assets/130416447/809b8170-d587-4df6-aeef-b97a07a8e2e1)
![groupspeeddial-contextmenu](https://github.com/fastaddons/GroupSpeedDial/assets/130416447/257ae3f9-4633-4068-b811-8d9926579153)

**Comment by Juraj-Masiar** [comment]
I see you have the "Toolbar icon - instant redirect to dials page" option enabled, so the popup window won't show for you.
In that case, you need to right click on the page and use context menu item (right click on empty space anywhere on the page and click "Add this page to dial").

**Comment by 2journey** [comment]
Is there a way for the popup window to show?

**Comment by Juraj-Masiar** [comment]
> Is there a way for the popup window to show?

Not while the "Toolbar icon - instant redirect to dials page" option is enabled.
But the right click on a page should still work fine.
