### ISSUE TITLE
Unable to edit dials on top half of page

### ISSUE THREAD

**Issue by GitGone58638** [fastaddons/GroupSpeedDial#302]
I am running the latest version of Firefox and a fully updated Windows 10. (I even resized the partition for the latest update in Windows 10.)  My dials is set as the default page when I open Firefox. Normally in order to edit a dial I right-click on the individual dial and the Dial edit menu appears - usually partially underneath the right-click menu in Firefox. Hitting the escape key one time closes the Firefox right-click menu and leaves the dial menu available for editing the dial.. 

Currently, the dial edit menu does not appear if the dial exists of the top half of the page. It works normally If the dial exists on the bottom half of the page. If I drag the full-size page down halfway, I can then - and only then, edit the dial. This is fully reproducible time after time on Two completely separate computers running the identically updated Windows 10 operating systems with synced Firefox browser clients..

**Steps To Reproduce**  Fully described above!

**Expected behavior** Expected behavior would be both the Firefox right-click menu and the dials editing menu were appearing usually partially covering each other. A single click of the keyboard escape key unfathomably removes the Firefox right-click menu, leaving the dial editing menu fully accessible.

**Device info:**
 - operating system: Windows 10 fully updated with the latest updates. Firefox browser fully updated to the latest version. And group speed die or updated to the latest version. Updates are turned on for all three. Operating system, browser, and group speed dial.

 - GroupSpeedDial version: ? 24.6?

**Additional info**
Add any other info about the problem here.

**Comment by Juraj-Masiar** [comment]
Hello,
Are you using some custom CSS styles for Firefox (also known as "userChrome.css")?
My addon also has "Custom CSS styles:" option in the Options page, did you make some changes there?

**Comment by GitGone58638** [comment]
Sorry it took so long to get back to you. I was dealing with some completely unrelated issues here.

I'm not using any custom CSS styles. At least none that I'm aware of. Nothing related to chrome as far as I know.

What happens, and nothing is changed, is that the menu to make changes in the group speed die out pages hidden behind the right-click menu that comes up normally with Firefox. If I take the entire page and drag it halfway down so that I'm only looking at the upper half of the page, then the two menus are separated enough so that I can access the speed dial menu. Otherwise the speed down menu is almost exactly aligned with the Firefox right-click menu. I have not found a way to separate the two menus so that I have access to the speed dial menu other than by dragging down the page halfway and then re-right clicking on one of the dials to bring up the speed down menu. In that instance it is not hidden behind the Firefox right-click menu.

If there is anything I can do to help you, or if there is some "about" that will send you details of the information on my system, I would be happy to do so.

Again I apologize for the lengthy reply time.

GitGOne58638

**Comment by Juraj-Masiar** [comment]
I see, this should be easy:
1. open "about:config" page
2. look for "dom.event.contextmenu.enabled"
3. make sure it's set to "true"

**Comment by GitGone58638** [comment]
Thank you!!!!!!!!!!!!!!!!!!
Works GREAT now!
Warmest regards,
GigGone58638
