### ISSUE TITLE
Search dial customization: Toggle to disable escaping special characters in the dial

### ISSUE THREAD

**Issue by sundayLOOKplants** [fastaddons/GroupSpeedDial#304]
**Problem:**
When using search dials that take urls as input, or other text with special characters, the characters are escaped, rendering the input invalid.
Example use case: I have a Wayback Machine search dial that does not work correctly atm.

**Proposed solution:** I would like a checkbox for avoiding the default escape behavior, so a Wayback Machine dial can work correctly.

**Alternatives I've considered:**
Making this the default behavior would break other search fields, so it does not seem like an option.

**Comment by Juraj-Masiar** [comment]
Done:
![image](https://github.com/fastaddons/GroupSpeedDial/assets/6358971/aa6d51bf-3a56-40c0-ac0b-ebe8041c3415)

It will be part of 24.7 release, probably next week or week after.
Thanks again for reporting this!
