### ISSUE TITLE
Not syncing between different browsers

### ISSUE THREAD

**Issue by leestrayer** [fastaddons/GroupSpeedDial#306]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: 
 - Browser and version: 
 - GroupSpeedDial version: 

**Additional info**
Add any other info about the problem here.

**Comment by leestrayer** [comment]
I have the extension running on Firefox and Chrome with a paid subscription, but the syncing between all isn't working. Some dials sync, others don't, some won't even update when changes are made. Missing custom thumbnails can't be updated. 
![Screenshot 2024-02-05 153231](https://github.com/fastaddons/GroupSpeedDial/assets/8070387/693c08b8-c8cb-4a53-bcb7-ab8d5628e186)
Screenshot on Chrome
![Screenshot 2024-02-05 153331](https://github.com/fastaddons/GroupSpeedDial/assets/8070387/effab7be-52e7-4179-83e9-42c514a546a6)
Screenshot on Firefox
Any ideas?

**Comment by Juraj-Masiar** [comment]
Hello,
First make sure you are logged in the same account:
https://group-speed-dial.fastaddons.com/
(see if the account info is the same on both devices/browsers)

Regarding thumbnails synchronization, make sure you have enabled it on both browsers - in the Options page / Thumbnails tab / Thumbnails synchronization.
Thumbnails are synchronizing only once an hour, but you force the sync. by clicking the "synced" button in the cloud icon on the dials page.

**Comment by leestrayer** [comment]
Box was unchecked on one of the browsers. Solved it. Thanks!

**Comment by Juraj-Masiar** [comment]
Thank you for the info!
I see I need to make this more intuitive, maybe enable it automatically on a new device if it's already enabled on existing devices.
Please let me know if you need further assistance, you can also write me email to admin@fastaddons.com
