### ISSUE TITLE
Live dial for local website not working after reinstall

### ISSUE THREAD

**Issue by PilgrimToHyperion** [fastaddons/GroupSpeedDial#307]
Hello,

I reinstalled a new copy of of Windows 11 a few days ago and restored my dials. I have one live dial I use that points to a local Home Assistant url. It's been working fine for months, but now just displays the Home Assistant logo when I add it as a live dial.

![image](https://github.com/fastaddons/GroupSpeedDial/assets/28935079/b239f255-20d6-4999-9a80-c721737f08d5)

![image](https://github.com/fastaddons/GroupSpeedDial/assets/28935079/dee519ef-181a-4e69-b9f2-ad9ebfe7561e)

![image](https://github.com/fastaddons/GroupSpeedDial/assets/28935079/bf683ace-d4dc-4ba5-b35b-3522b7fd0eaa)

Setting it as a webpage dial works fine:
![image](https://github.com/fastaddons/GroupSpeedDial/assets/28935079/0c1c9fe2-3cc2-4a78-a6f3-fbb5087d225d)

This error seems related:
`15. 2. 2024 8:06:15 15324ms, fr - problem with thumbnail: isSolid: true, badName: false, errorPage: undefined
undefined
{"work":{"groupId":20,"url":"http://192.168.1.171:8123/power-situation","dialSize":0,"type":-1,"delay":0,"isManualReload":true,"isVisibleSpin":true,"refreshMethod":1,"isGroupDial":false,"lastRunTime":0},"frame":{"dial":{"index":1,"groupId":20,"domId":"dial_1","type":0,"url":"http://192.168.1.171:8123/power-situation","name":"192.168.1.171:8123/power-situation","size":0,"created":1707977169,"visual":{"noTitle":false,"noIcon":false,"padding":0}},"groupId":20,"isGroupDial":false,"url":"http://192.168.1.171:8123/power-situation","width":1232,"height":843,"upscale":2,"title":"Home Assistant","flagBadName":false,"node":{},"isManualReload":true,"left":0,"top":0}}
c@moz-extension://e2e7e815-3cab-4421-8760-44c535c2b87e/reload/reload.js:1:66031
lt@moz-extension://e2e7e815-3cab-4421-8760-44c535c2b87e/reload/reload.js:1:97317`

I'm using the latest Firefox on Windows 11 and version 24.6 of the extension.

What am I missing?

**Comment by Juraj-Masiar** [comment]
Hello,
Live dials are supported only in the PRO version, so maybe you are not logged in your cloud account?
https://group-speed-dial.fastaddons.com/

**Comment by PilgrimToHyperion** [comment]
Thanks for the feedback.

I am a pro subscriber. 
![image](https://github.com/fastaddons/GroupSpeedDial/assets/28935079/1b05fa1d-04fe-439e-b153-db2d3ad12cd8)

**Comment by Juraj-Masiar** [comment]
In that case, are you sure my extension is installed? More importantly, make sure you are not viewing the Cloud dials page:
https://github.com/fastaddons/GroupSpeedDial/wiki/Cloud-Dials-web-page
That one doesn't support live dials.

Also, try to create another live dial, will that work?
And does other PRO features work OK?
And what version of my extension and browser are you using?

**Comment by PilgrimToHyperion** [comment]
Out of the blue it just started working without any changes that I've made. Maybe Firefox updated or perhaps it was a Home Assistant update. 

Thanks for a wonderful piece of software!
