### ISSUE TITLE
Small problem with deprecated Browsers (Old trusty Win7 Desktop)

### ISSUE THREAD

**Issue by Delyrio** [fastaddons/GroupSpeedDial#311]
I was very hesitant to post anything about this because of the obvious reason (title post) but then I lose nothing by posting it.

So here it goes, I can't change the background image at all (on any of the 3 browsers [Edge, Firefox* and Chrome] that I use on this desktop), none of the options work but one, bings image of the day, the rest is a no go.

However, on version 24.3 (with the old menu) which is still installed on the Firefox* browser, everything works just fine, so the problem might not be totally related to deprecation.

Thanks for your time reading a pretty DOA post :D

PS. Yes I tried to update to Win10 but got BSOD boot loop every time I tried.

**Comment by Juraj-Masiar** [comment]
Hello,
You should be able to update my addon to 24.7, at least in your Firefox. Or have you tried it and it doesn't work?
First check if you are running Firefox ESR 115, this one should still work on Windows 7 and my addon fully supports it - at least till September when new Firefox ESR is released.

However, Chromium browsers are stuck at version 109 and they most likely won't run my latest version. But they are also full of security holes so I would strongly recommend not using them. Firefox 115 is fully secured until September/October.

Regarding the bug, it sounds very strange. I can't think of a reason it wouldn't work, especially the simple options like solid color. Please check the version of my addon, which one are you running?

**Comment by Delyrio** [comment]
Hey, thanks for your swift reply.

As for the versions, the Chromium based browsers are up to date GSD (24.8) they just don't change the background. On FireFox everything works but it is the old version of GSD (24.3), that refuses to auto-update (thankfully tbh) so I don't plan to update it manually as I don't want all 3 to be missing that option.

As for up-to-date browsers on my other PCs (Win10, Win11) everything works flawlessly hence I didn't flag this post as "bug" because it isn't, background change just got broken with the GUI change of GSD on deprecated browsers IMO.

Thanks again for your time and keep up the good work, I migrated to GSD from other dial once they started to treat their users as cash cows (removing basic dial options behind paywall and forcing ads on its users).

**Comment by Juraj-Masiar** [comment]
Let's try one experiment - export your data from the Windows 10/11 system and import it to the old system.
That way we will know if the problem is in the options page or in the background handling code.

You can export your data form the Options page / Import backup tab.

**Comment by Delyrio** [comment]
> Let's try one experiment - export your data from the Windows 10/11 system and import it to the old system. That way we will know if the problem is in the options page or in the background handling code.
> 
> You can export your data form the Options page / Import backup tab.

Tried it and no change, everything imports as it should including the background image, but as soon as I go to change it to something else no option works at all but the bing one.

Was lurking around the settings to see if I can spot a simple solution and noticed that when I try to change the background to any option that is not working, no file in any of the folders (Local Extension Settings being the most important I believe) pertaining to the extension gets the modified timestamp (as in the setting has been commited/saved to a file) but some .log files.

**Comment by Juraj-Masiar** [comment]
The experiments shows that if the data are correctly stored, they are also correctly applied.
So the issue must be that the Options page wrongly sets the data. But why...

I don't think I will be able to help :(
The fact that you are using unsupported operating system is really bad. And what's worse, next year even Windows 10 will reach EOL (end of life, so no more security updates).

**Comment by Delyrio** [comment]
It's fine, none of this is an issue with the extension, it's everything surrounding it that's the problem (Win7, deprecated browsers).

With this post just wanted to see if there was a simple solution to the problem, just my OCD not allowing me to have something not doing what I want.

Keep up the good work, thanks again for your time :100: 

Cheers
