### ISSUE TITLE
My thumbnails are too small (not filling the box.)  How do I enlarge them?

### ISSUE THREAD

**Issue by RosewoodLover** [fastaddons/GroupSpeedDial#322]
all my older thumbs 100% fill the box.

now they're 75% filling the box.    🤨

i must be doing something differently!?

i tried changing to full screen (while making thumbs).

i tried zooming in or out.  this changes the auto-size number 

(eg i can get big numbers like 2000x1000)

but the actual thumb is still small.

i'm creating thumbs from either URL or file.  same results.

(chrome, windows 10.)

**Comment by Juraj-Masiar** [comment]
Hello,
It's the new default for thumbnails from Public library. 
You can change that easily in the Edit dial / Visual / Thumbnail padding.
Once you change that, all new dials should use the changed value.

**Comment by RosewoodLover** [comment]
thank you!
