### ISSUE TITLE
Thumbnail Aspect Ratio is Reduced

### ISSUE THREAD

**Issue by Infinitebaffle** [fastaddons/GroupSpeedDial#325]
When loading any image file for thumbnail, the the image has been reduced significantly. Have tried adjusting virtual resolution, and individual thumbnail settings to no avail. Seeking older version of Group Speed Dial until bug fixed. Anyone have a link?

If you have existing images, try loading any new  image, and thumbnail will be reduced.

If this is the new standard, I would like to be able to zoom image to fill dial, either trough settings, or resizing images to specific size. The thumbnail size difference is an inconvenience for users with existing speed dial backups.

 - Parrot Security 6.1 (lorikeet) x8
 - Brave 1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit)
 - GroupSpeedDial version: 25.1

Tried creating thumbnail image from .png and .jpg images. Used multiple sized images.
![Screenshot at 2024-05-04 10-11-16](https://github.com/fastaddons/GroupSpeedDial/assets/101475244/d75f5e22-9ddc-4327-a780-9972a67ff0da)
![Screenshot at 2024-05-04 10-57-51](https://github.com/fastaddons/GroupSpeedDial/assets/101475244/7a19d144-87bc-4d52-bb21-41ddacdc8658)
![Screenshot at 2024-05-04 10-43-12](https://github.com/fastaddons/GroupSpeedDial/assets/101475244/5927ad5b-8dd0-4983-9eea-82b7049f8da5)

**Comment by Infinitebaffle** [comment]
The default thumbnail padding has somehow changed. If the pad setting were a snake, it would have bit me.

**Comment by Juraj-Masiar** [comment]
Hello,
I'm sorry for confusion. This is indeed a new "feature", you can now set a custom padding that's then remembered for each new dial. And by default it's set to some value.
I should have made it more clear, the padding setting is "hidden" in a different tab so it's totally not clear why the image won't fit :(.
I'll try to improve it.

**Comment by Infinitebaffle** [comment]
> Hello, I'm sorry for confusion. This is indeed a new "feature", you can now set a custom padding that's then remembered for each new dial. And by default it's set to some value. I should have made it more clear, the padding setting is "hidden" in a different tab so it's totally not clear why the image won't fit :(. I'll try to improve it.

What happened is the thumbnail padding was reduced. If you set it to max by default it should fix. No worries. Group Speed Dial is a great program. Good job!
