### ISSUE TITLE
thumbnails are not synchronized.

### ISSUE THREAD

**Issue by Domo222** [fastaddons/GroupSpeedDial#33]
The thumbnails are not synchronized. i.e. the thumbnails on the PC and the cloud are partly different. My impression is that the last changes were no longer synchronized. 
Many greetings Dominik

**Comment by fastaddons** [comment]
Hello,
The thumbnails synchronization is currently slightly delayed (it runs every 4 hours). This is to save some performance on my server as those thumbnails can be hard to process. Dials itself are synced 10 seconds after last change.

I'm now upgrading my server so depending on the new performance I may reduce that.
Also dials with auto-reload enabled are currently excluded from the automatic sync. and will be synchronized only when manual sync is triggered - when you click the "synced" label in the cloud icon (on the dials page).

**Comment by Domo222** [comment]
sorry, unfortunately it still doesn't work. the displayed time of the synchronization remains the same since yesterday: January 27th 21:09:38. so some thumbnails are still missing or not properly updated. resynchronizing does not change anything!
can you delete the account and synchronize again, or is there another solution?

**Comment by fastaddons** [comment]
Can you verify that you are logged into the same account?
https://group-speed-dial.fastaddons.com/

And did you clicked the "synced" label? It should trigger the thumbnails sync.
Note that if you enable sync on a second device which already has some thumbnails, these thumbnails will not be replaced, only after you update them on one of the devices they will be synced.
Only missing and updated thumbnails are automatically downloaded.

**Comment by Domo222** [comment]
sync works now,
But the following problem. In some of the dials I added text via https://maketext.io/. I want to change this again. What also works on the PC but not in the cloud. I also completely deleted the dial and replaced it with a jpg. The text is still in the cloud!
. I've tried everything. The text appears again and again in the cloud!

**Comment by fastaddons** [comment]
So the thumbnail gets uploaded to the cloud but the other device won't download it during the sync, right?
And it affects only the MakeText type?
Could you try to right click one of those problematic dials and from the context menu click "Advanced / Restore previous thumbnail", then click it again (to revert it). Then try to run the sync on both devices.

**Comment by Domo222** [comment]
no upload does not work correct. 
"Advanced / Restore previous thumbnail" has not changed anything

I hope you can see the attached screenshots. Maybe the Problem gets clearer then.

PC-Dial:
![PC 2021_01_28_18_35_33_Window](https://user-images.githubusercontent.com/68423740/106176928-2e05fe00-6198-11eb-9d47-ceefb3fa7672.png)

Cloud-Dial. this "wrong" dial is synchronized with another notebook:
![cloud 2021_01_28_18_36_06_Window](https://user-images.githubusercontent.com/68423740/106176804-0f076c00-6198-11eb-8ead-9eba8c2737e6.png)

**Comment by Domo222** [comment]
can you tell me how to delete my account. i will try to upload my dials again. Thank you

**Comment by fastaddons** [comment]
There is no delete in my old server, that's why I'm building a new one for the past few weeks.
I can delete your account manually but I can guarantee you it won't help.

I've just tested the thumbnails sync using the MakeText.io images and it works as expected, so let's try again step by step.
This is what I did and it for sure works.
1) having two devices A and B logged into the same account
2) activating Thumbnails sync on BOTH devices! This can be done through the main menu / Quick options / Synchronize thumbnails.
3) create new MakeText.io on of the dials in the device A
4) trigger manual sync by hovering the cloud icon and clicking the "synced" label - it should says something like "synchronizing 1 thumbnail"
5) trigger manual sync on device B same way
6) now the device B has the new thumbnail
7) on device B using context menu / Advanced / Restore previous thumbnail we revert thumbnail
8) trigger manual sync on B
9) trigger manual sync on A
Device A has now reverted thumbnail.

Could you try this on your device?

**Comment by Domo222** [comment]
Thank you for the detailed instructions. First of all I would like to say that at the moment it is not that important to me to use this text function MakeText.io. because I saw that I can upload thumbnails as a file from my PC too.
Still, I followed your instructions. the following result:
to. 1. to 4. everything works fine.
from 5. the following problem: the manual synchronization on device B generates a dial but completely without a thumbnail.
To check, I then checked the cloud and found that the thumbnail had been transferred incorrectly. I had already observed this behavior with other thumbnails. I think something fundamental doesn't work for me when uploading.
I would be grateful if you could keep helping me. maybe I can also create another new account. The synchronization was completely okay with me at the beginning, until I had used the text function MakeText.io and then later wanted to replace the text with a jpg thumbnail from my own PC.
see screenshots

PC
![PC 2021_01_29_18_50_33_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106310278-95d54b00-6263-11eb-81bd-c6a93061096c.png)


Cloud
![Cloud 2021_01_29_18_51_27_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106310211-7e965d80-6263-11eb-8017-0ca73a779a9d.png)

**Comment by Juraj-Masiar** [comment]
When you say "_B generates a dial but completely without a thumbnail_" - what does that mean?
When you trigger sync on the device A, then cloud should have the image. Every time you update a thumbnail and click the sync, the image will be be in the cloud. If it's not in the cloud, something went wrong.
Also my current (old) server supports only basic image types, so if you are using custom images from your drive it's better to keep the format simple - so using JPG, PNG and SVG.

**Comment by fastaddons** [comment]
Additionally there is a size quota on the server (around 40MB, which is normally enough to store thousands of thumbnails).
Once you hit that, new thumbnails won't be uploaded. If you are uploading custom high resolution thumbnails, you may have hit it. But there is no way to check that right now (again, my old server is missing many features...).

Actually there is way to estimate your thumbnails size - from the Options page / Import backup tab export your dials and thumbnails and then check the file size.

**Comment by fastaddons** [comment]
Regarding quotas:
```
//   3 MB - max image size
//  40 MB - normal user total size
// 100 MB - Pro user total size
// 200 MB - Enterprise user total size
```
I have around 2000 dials in more than 50 groups and I'm still below 40MB.

**Comment by Domo222** [comment]
Do you mean this file? It has 3,15 MB.
export_2021_01_29___17_04_57.group_speed_dial

Device B, Notebook
![notebook 2021-01-29 19_51_04-GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106315639-d6d15d80-626b-11eb-95f6-e95a30b8cff7.png)

I have only .jpg and .png files

**Comment by fastaddons** [comment]
Ok,let's debug this. Are you using Firefox or Chrome?

**Comment by fastaddons** [comment]
Also that dial without a thumbnail - are you saying you can't generate a thumbnail for that dial? That would point to some database issues in your browser. If you are using Firefox, please try to visit this storage test page:
https://firefox-storage-test.glitch.me/

**Comment by Domo222** [comment]
I didn't quite understand you.
In the beginiing everything went fine. 
I managed to create different types of thumbnails and synchronized them from device A to device B.
i have used these:
automatically generated thumbnail 
thumbnail from public library. 
Load individual thumbnail from file.
Text thumbnail

I use chrome.

**Comment by fastaddons** [comment]
I'm trying to isolate the problem.
Are both of your devices unable to sync thumbnails to the cloud? Or just one?
Try to update one of your thumbnails, then click the sync and then check the cloud account to see if it's there.
If this is related to only one of the devices, we can check the logs to see why the upload failed.

**Comment by Domo222** [comment]
I have just created a new Dial on devices A.
The automatically generated Thumbnail is immediately synchronized with the cloud. However, the Thumbnail looks different in the cloud. Then I replaced the Thumbnail with a public library image. this change is not displayed on the PC. However, you can see the change with the updated thumbnail in the cloud.  
I tested the same procedure on device B and it gave the same result.

**Comment by Domo222** [comment]
now I have a guess what it might be. I signed in to your cloud with a different Google account,
 not the Google account from which I downloaded the extension.

**Comment by fastaddons** [comment]
One more thing regarding the cloud - I've just realized my old cloud pages are still available and these may have problems displaying thumbnails.
The correct cloud URL is now this:
https://group-speed-dial.fastaddons.com/cloud

The old that should not be used are:
https://group-speed-dial.fastaddons.com/dials
https://group-speed-dial.fastaddons.com/cloud2

Regarding your cloud account, just visit the main page on both devices to see if you are logged in the same account:
https://group-speed-dial.fastaddons.com/

**Comment by Domo222** [comment]
both devices have this account.
https://group-speed-dial.fastaddons.com/cloud

**Comment by Domo222** [comment]
I have installed Firefox and the extension and found that when I use Firefox and synchronize the dials (download) from the cloud, I get exactly the same false identical display as with Chrome.

**Comment by fastaddons** [comment]
Oh man, I'm confused :). When you say "_same false identical display_" I have no idea what you mean.

**Let's start again from the very beginning.**
First of all, make sure you are logged in a same account on all devices. That means that when you open this page:
https://group-speed-dial.fastaddons.com/
You will see the same name, last name, full-name and the same email in both devices / browsers.

After that let's try some simple experiment, like creating new dial with URL "https://github.com". Will this work? Because it must work. If not, tell me which device, and we can start analyzing the logs to see why not.

**Comment by Domo222** [comment]
"same false identical display" . 
I would like to say that the display of the dials in both browsers is identical and therefore not as desired.

the information is identical on both devices. 
However,  last name none and  email none


dial with URL "https://github.com"

PC, Device A:
![PC 2021_01_30_18_03_24_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106362926-cc739a00-6325-11eb-85de-8280dae7824c.png)

Cloud, Notebook Device B:
![Cloud  and Notebook 2021_01_30_18_02_16_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106362936-da291f80-6325-11eb-9e62-fff141d93d7f.png)

**Comment by fastaddons** [comment]
And the thumbnails synchronization is enabled?

![_syncrhonize_thumbnails](https://user-images.githubusercontent.com/55486931/106363004-26745f80-6326-11eb-911f-4fa49b1212b5.png)

**Comment by fastaddons** [comment]
Also when you say "Cloud, Notebook Device B:", could you check the cloud page on the device A?

**Comment by Domo222** [comment]
sorry this was my mistake.
screenshots from PC, Device A and cloud are ok, 
but device B show the following screenshot
Device B:
![Device B 2021_01_30_19_04_54_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106364429-347aae00-632f-11eb-8cd8-5803e60e6b9b.png)

**Comment by Domo222** [comment]
the thumbnails synchronization was enabled on both devices

**Comment by fastaddons** [comment]
What about the Cloud page in the device B - is the image there?
https://group-speed-dial.fastaddons.com/cloud

**Comment by Domo222** [comment]
no!

Device A:
![PC 2021_01_30_18_03_24_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106362926-cc739a00-6325-11eb-85de-8280dae7824c.png)

Device A and Device B, cloud:
![Cloud  and Notebook 2021_01_30_18_02_16_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106362936-da291f80-6325-11eb-9e62-fff141d93d7f.png)

Device B:
![Device B 2021_01_30_19_04_54_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106364429-347aae00-632f-11eb-8cd8-5803e60e6b9b.png)

**Comment by fastaddons** [comment]
>  screenshots from PC, Device A and cloud are ok,

Before you said the cloud is OK. Are you sure the cloud is not ok? You see how this is confusing for me here...

**Comment by Domo222** [comment]
I hope I can explain it: 
in the last answer I sent the current screenshots. before I made a msitake. Sorry!

there is a difference between the device A and the cloud. That means: the thumbnails were not transferred correctly from the Device A to the Cloud . 
I am sure the cloud is not ok!

**Comment by fastaddons** [comment]
Could you try the same experiment from the second device? Just create new dial with automatically generated thumbnail and then trigger the sync and check the cloud.
This sounds very strange...

**Comment by Domo222** [comment]
yes ok. create from second device=device B:

Device B:
![notebook 2021-02-02 09_44_31-GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106575687-a411b880-653c-11eb-82cc-3aada0c531c8.png)

Device B and Device A, cloud:
![cloud von notebook und PC 2021-02-02 09_46_49-GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106575796-c3104a80-653c-11eb-9697-052d6301a77f.png)

Device A:
![pc 2021_02_02_09_49_05_GroupSpeedDial](https://user-images.githubusercontent.com/68423740/106575856-d1f6fd00-653c-11eb-8259-e81725174dda.png)

**Comment by fastaddons** [comment]
OK so now we know that somehow you can't upload thumbnails from any of your devices.
Let's debug it.
1) disable thumbnails synchronization (from main menu / Quick options / Synchronize thumbnails)
1) restart Chrome (or whole PC)
1) open "chrome://extensions/" page
2) click the "Developer mode" in the right corner
3) click my extension "Details" button
4) in the "Inspect views" section, click the "background/background_gsd.html" link
5) in the new window, click the "Network" tab
6) enable thumbnails synchronization
7) make a screenshot of the "Network" tab and send it to me

**Comment by fastaddons** [comment]
Something like this:
![Screenshot 2021-02-03 10 29 00](https://user-images.githubusercontent.com/55486931/106726624-e30e3f80-660a-11eb-9670-ae1216aa4a11.png)

**Comment by Domo222** [comment]
sorry but i cannot find: " 8. enable thumnails synchronization"

here are The sreenshots
![2021_02_03_12_46_14_DevTools_chrome_extension_imfeikbeimbfpmgfkkmjekabdehiiajc_background_backgr](https://user-images.githubusercontent.com/68423740/106743413-a51b1680-661e-11eb-94d8-ed5be7414a22.png)

![2021_02_03_12_46_33_DevTools_chrome_extension_imfeikbeimbfpmgfkkmjekabdehiiajc_background_backgr](https://user-images.githubusercontent.com/68423740/106743432-a9dfca80-661e-11eb-9151-01762bb30cf5.png)

![2021_02_03_12_47_13_DevTools_chrome_extension_imfeikbeimbfpmgfkkmjekabdehiiajc_background_backgr](https://user-images.githubusercontent.com/68423740/106743446-aea47e80-661e-11eb-8952-10e1324537d4.png)

**Comment by fastaddons** [comment]
Well if you don't enable the thumbnails synchronization again then it's gonna be empty :)
You can enable the synchronization the same way you disable it:

![_syncrhonize_thumbnails](https://user-images.githubusercontent.com/55486931/106744517-2c1cbe80-6620-11eb-88b9-0fb9f744934d.png)

**It's a checkbox, so when it's checked, it's ON when it's unchecked it's OFF.**

**Comment by Domo222** [comment]
![2021_02_03_19_38_24](https://user-images.githubusercontent.com/68423740/106793437-c3513880-6657-11eb-9fdb-29e1cc66ccb8.png)

**Comment by fastaddons** [comment]
Great! Thanks, this looks promising. There are some errors, probably when comparing server and local images.

Could you tell me what version of Chrome are you using? You can see it in "chrome://settings/help" page.
Also I suppose you use latest version of my extension 15.4, right?

**Comment by Domo222** [comment]
extension Version 15.4: yes

Google Chrome ist auf dem neuesten Stand.
Version 88.0.4324.150 (Offizieller Build) (64-Bit)

**Comment by fastaddons** [comment]
So it seems that there is indeed some problem, but I'm not sure where. I'm missing some advanced error logging in the thumbnails sync code so I've just added it now and it will be there in the next release 15.5.
However the error you see "undefined is not a function" is hard to imagine since I'm using TypeScript so my compiler would see it. Not to mention it wouldn't work for anybody else, not just you.

Could you try to disable all your other extensions to see if it helps?
Simply go here: chrome://extensions/
Disable all extensions.
Restart Chrome.
Open the dials page and trigger the manual thumbnails sync.

**Comment by Domo222** [comment]
disable all other extensions: ok
Restart Chrome: ok
Open the dials page and trigger the manual thumbnails sync: ok
upload thumbnails is not working

**Comment by fastaddons** [comment]
Hello again. I'm sorry for the delay.
Could you please try it from a different browsers? If you can, please try Firefox and some other Chrome based browser, like the new Edge, Brave, Vivaldi or even Opera.

Once I release the new version (it will be version 16.0) it will log out more information about the error so it will be easier to find the cause. I'm still working on the server so this will take a while...

**Comment by Domo222** [comment]
the result with firefox:

Device A, firefox
![Device A firefox  2021-02-09 11_58_37-GroupSpeedDial](https://user-images.githubusercontent.com/68423740/107362533-2a983e00-6ad9-11eb-82e3-faa68b5bb0f9.png)

Device A, firefox cloud
![Device A firefox cloud 2021-02-09 11_58_27-GroupSpeedDial](https://user-images.githubusercontent.com/68423740/107362547-2ff58880-6ad9-11eb-9d42-3e43660d414d.png)


Device B. firefox
![Device B firefox 2021-02-09 13_01_24-](https://user-images.githubusercontent.com/68423740/107362568-34ba3c80-6ad9-11eb-8189-70d4e69815f6.png)


Device B firefox cloud
![Device B firefox cloud 2021-02-09 13_01_24-](https://user-images.githubusercontent.com/68423740/107362581-37b52d00-6ad9-11eb-99a0-7abf9993f129.png)

**Comment by fastaddons** [comment]
Thanks! Could you open the browser console in the Firefox (Ctrl + Shift + J) and then click the "synced" label to trigger the thumbnails synchronization and then send me the error that should appear in the browser console window?
It's possible that Firefox has better error logger and it should print the row and column number in the source code that will tell me what function fails.

**Comment by Domo222** [comment]
if there is information that should not be publicly visible, please let me know so that I can delete it!
![error konsole firefox](https://user-images.githubusercontent.com/68423740/107421304-17f22900-6b1a-11eb-876e-e03e6677f15d.png)

**Comment by fastaddons** [comment]
Of course, but don't worry, this doesn't have any private info. 
But this is not the same error than in Chrome, but it is also interesting and may be related. It seems that dial type on one of your dials is wrongly set and then it expects some data in place where no data are present. It's called "data inconsistency". That's why the problem appears on your devices and not on others.
Let me investigate this... I should be able to find the piece now

**Comment by fastaddons** [comment]
Oh man, I've found it!!!
So the problem is that one of your dials is using thumbnail from the "Public library" but no image was selected.

This was most probably introduced with the new "Edit dial" window. Oh, this is nasty bug!
So what you need to do is find a dial that has Thumbnail set to "Public library" and either change it to "Auto generated" or actually choose one of the thumbnails from the Public library.
If you need help identifying a dial, I can write you some script that will list all dials with "Public library" type.

Thanks for helping identifying the problem! I'm sorry it took me so long... I'm still very busy with the new server.

**Comment by fastaddons** [comment]
OK so I've wrote the script that will find the dial and print the info about it.
So just open your dials page, open developer console (Ctrl + Shift + K) and execute this code:
```
JSON.stringify((await browser.storage.local.get('groups')).groups.flatMap(g => g.dials.filter(d => d.thumbnail && d.thumbnail.type === 3 && !d.thumbnail.value)))
```
You should not execute codes you don't understand, so let me explain it. It will get your groups, then filter all dials where thumbnail type is "3" (public library) and value is missing.
It will print all info about the dial so just check the URL and then you should be able to identify which one it is.

**Comment by Domo222** [comment]
so now it worked. I fixed the thumbnail that wasn't working. Thank you very much.
unfortunately there is another problem. all thumbnails were initially perfectly synchronized between device A and the cloud. then, however, the "wrong" thumbnails from device b were synchronized back to device A via the cloud. In this respect I have numerous "wrong" thumbnails.

how can I restore a backup in the history.
when i click on it nothing happens.

**Comment by fastaddons** [comment]
Nope, the History stores only dials data, not thumbnails data.
But there is a single backup for each thumbnail. So when you right click a dial and press "z" (or by going to "Advanced" / "Restore previous thumbnail") then you can revert the previous thumbnail.
But you have to do it for each dial manually. But using the right click and "z" key should be pretty fast.

**Comment by Domo222** [comment]
now in Device A all of the Thumbnails are perfect. How can I ensure that the thumbnails are transferred from Device A to the cloud and not the other way around? 
at the moment the synchronization is disabled.

**Comment by fastaddons** [comment]
First of all, make sure to create a backup - you can export your dials and thumbnails to a file from the Options page / Import backup tab. There is a checkbox to export also thumbnails.

Anyway, the rules for the synchronization are simple - if you change thumbnail, it will be uploaded to the cloud. So if you used the "Restore thumbnail" on your dials then they are "newer" and thus will be uploaded to the cloud. Just make sure you don't update them on some other device again.
But enabling synchronization on a new device will always download all missing thumbnails.

**Comment by Domo222** [comment]
now, everything is perfect !
Thank you very much.
