### ISSUE TITLE
Extract bookmarks when addon doesn't start

### ISSUE THREAD

**Issue by arbaev** [fastaddons/GroupSpeedDial#334]
Hi! 
Is there a way to save bookmarks when the addon stopped working? Just a blank black screen, if I go to settings - also a black screen. Restarting the system does not help.

Device info:
    operating system: windows 10 pro 22H2
    Browser and version: Firefox 127
    GroupSpeedDial version: 25.2

**Comment by Juraj-Masiar** [comment]
Hello,
Check this recovery article:
https://github.com/fastaddons/GroupSpeedDial/wiki/Fixing-broken-dials-page

The options page should work no matter what, try to open it from the "about:addons" page:
![image](https://github.com/fastaddons/GroupSpeedDial/assets/6358971/e509d63b-a469-4132-bc0a-a04bcc302f5f)

If the options page also shows only black screen, could you press "Ctrl + Shift + K" to open Console and send me the errors you see there? Ideally also screenshot of it, that could help me find the issue.

We can also try to recover data from the store using the console.

**Comment by arbaev** [comment]
Thanks for the quick reply!
Yes, I read this article and going to options also leads to a black screen. Screenshot of the error in the console:
![Monosnap Options - Group Speed Dial 25 2 — Mozilla](https://github.com/fastaddons/GroupSpeedDial/assets/13077390/170e3a5c-18de-4fb2-b2de-7730765553ec)

**Comment by Juraj-Masiar** [comment]
Hmm, that's pretty brutal error, the whole `browser.tabs` API is undefined, which should be not possible.
Any ideas why could it break? Did you do some changes to your Firefox?

Anyway, let's try to export the stored data, the backups are in 3 different storages so hopefully one of them will still work.
1. open dials page or options page
2. open the console again (Ctrl + Shift + K)
3. in the console, execute this:
```
browser.storage.local.get().then(console.log)
```
And if it doesn't print error, then right click the word "Object" and click "Copy object", like this:
![image](https://github.com/fastaddons/GroupSpeedDial/assets/6358971/b5333f4d-7685-4ab9-a114-a233e647a89c)
4. paste the text in a Notepad and save the file as "backup.group_speed_dial".
5. you should be able to import this file in another installation (for example try in Chrome or Edge)

If there is an error, try this:
1. in the console window, execute:
```
await browser.storage.sync.get()
```
Does it print error?
If yes, try this:
```
localStorage._bck_sync_backup
```
Does it print a lot of text?

**Comment by arbaev** [comment]
Oh, great! Managed to save all bookmarks to a file. Thank you very much! (now it works fine in Chrome)

However, further removal of the extension, rebooting the machine and installing the extension did not have any effect. Still a black screen with the same error. I can't figure out why. It all started today with long pauses when starting Firefox, then it stopped loading altogether.

**Comment by Juraj-Masiar** [comment]
So, everything works now? I'm happy to hear that!

Interesting. It's good to know the troubleshooting mode has some recovery "effect" too, usually simple restart is enough but I guess not always. Hopefully it won't happen again. 

Please let me know if you need further assistance :)
