### ISSUE TITLE
Cannot refresh dials

### ISSUE THREAD

**Issue by BobHD** [fastaddons/GroupSpeedDial#341]
**Describe the bug**
In the search of why Firefox tabs were crashing, I did a fresh install because C: needed to be repaired, keeping the same profile.
At some point, every thing was working fine, except that GSD had lost all its settings.
I had a backup, so I could import them all.
But now, I have only been able to refresh the first 2 dials. All others show a spinning circle, and it never stops.

**Steps To Reproduce**
Hard to tell, first time I installed that did not happen. Refreshing was slow, but worked.

**Device info:**
 - Windows 10
 - Firefox Dev Edition 127.b01
 - GroupSpeedDial version: 25.6

**Comment by BobHD** [comment]
Well, after much trying, it worked by refreshing all by visiting the site.

**Comment by Juraj-Masiar** [comment]
I've improved reloading in the upcoming release, so it should fix future issues.

**Comment by BobHD** [comment]
Great, thanks.
