### ISSUE TITLE
Custom background create two layers

### ISSUE THREAD

**Issue by Luke0094** [fastaddons/GroupSpeedDial#343]
Once you load an image it will loaded two times, one for the dials and one for the group bar, more you extend the group bar more this will be noticeable.
<img width="1919" alt="image" src="https://github.com/user-attachments/assets/c7cd51ff-26e2-441d-a4f7-3df2123833f8">

**Comment by Juraj-Masiar** [comment]
Hello,
I can't reproduce it here.
Maybe you've set a global background (in the Options page) and then also a group-specific background in the "Edit group" window.
Note that group specific backgrounds are not extending to the whole screen, only behind the dials area.

**Comment by Luke0094** [comment]
Yes, that was the case, thank you.
