### ISSUE TITLE
Title icon override

### ISSUE THREAD

**Issue by mikwei** [fastaddons/GroupSpeedDial#347]
If I use the Visual Icon selection for a group, would like that displayed in Page Title(tab) instead of the defaults set in Options / General.  FYI - the icon for group doesn't currently show up in the page Title.  It does show on group dials correctly.

It just makes it easier to find in tabs if many open.

**Comment by Juraj-Masiar** [comment]
Interesting idea!
I don't see why not. I've just tested it and it seems to work fine, although I need to test if I can also invert the color when browser is using dark theme (since those icons are by default black).

**Comment by Juraj-Masiar** [comment]
Good news, new version 25.9 will add option "Set tab Favicon as current group icon" in the Options page / General.
It should be released after review sometime this week.

**Comment by mikwei** [comment]
That was quick,  Thanks

𝓜𝓲𝓴𝓮 𝓦𝓮𝓲𝓼𝓼𝓮𝓷𝓫𝓸𝓻𝓷 ***@***.***>
