### ISSUE TITLE
Can not set Group's container from Personal to "No Container"

### ISSUE THREAD

**Issue by shuxiao9058** [fastaddons/GroupSpeedDial#348]
**Describe the bug**

**Steps To Reproduce**
Set "My" Group to Personal, Save changes

<img width="845" alt="image" src="https://github.com/user-attachments/assets/d040998e-d74e-46c8-a1ad-966f48006a7b">

Edit Groups , set Contains to "No Container", but not works.

<img width="838" alt="image" src="https://github.com/user-attachments/assets/84d512fe-a042-4e87-a108-8a9f4370708d">

**Expected behavior**

**Device info:**
 - operating system: macOS 14.6.1
 - Browser and version: Firefox 129.0.1
 - GroupSpeedDial version: Group Speed Dial 25.6

**Additional info**
Add any other info about the problem here.

**Comment by Juraj-Masiar** [comment]
Hello,
I'm sorry for the delay, I've been preparing new release.
I can indeed reproduce it here, I will fix it now.

**Comment by shuxiao9058** [comment]
@Juraj-Masiar Thanks for your awesome work.
