### ISSUE TITLE
Can't change background again

### ISSUE THREAD

**Issue by NeonBanshee** [fastaddons/GroupSpeedDial#349]
After I installed this, I changed the background wallpaper, didn't like it, went to change it again and it only changes a small part on the "groups list"

- Browser and version: firefox 59659484
 - GroupSpeedDial version: 25.6

**Comment by Juraj-Masiar** [comment]
Hello,
You are likely using also "group-specific" background (each group can have own background image).
Right click group name / Edit group / Background.

**Comment by NeonBanshee** [comment]
Oop, yeah that was the problem, thank youu!
