### ISSUE TITLE
Tab behavior (new or this)

### ISSUE THREAD

**Issue by osminogig** [fastaddons/GroupSpeedDial#35]
Hello!

For me, any action in the browser is accompanied by the opening of a new tab.
But searching in the address bar and opening a bookmark in the GroupSpeedDial tab opens in the same tab :((

Please make the appropriate option !

_(CentBrowser)_

**Comment by fastaddons** [comment]
I think something like that is already there (if I understand the problem correctly).
Check the Options page / Dials / "Always open in New tab" checkbox.

Regarding searching in address bar - this is outside my reach. Maybe there are extensions that can change this, but anyway it's not related to the page you are on (in this case the Dials page).

Only searching through my "Search dial" can be customized (search dial is a type of dial, see Edit Dial window).

But maybe you can find some browser setting for that.

**Comment by osminogig** [comment]
**Thanks for the help and the best Speed ​​Dial ! (transferred from FVD)**

![2021-2-2 0-2-58](https://user-images.githubusercontent.com/12220671/106519082-d47d3680-64eb-11eb-9dff-8cf3680e8c9b.png)
and Open from clipboard - too in New foreground tab

**As I understood from experiments, it is the browser itself that sets this behavior.
On its native SD, it opens everything in the current tab ! Idiocy !
I will ask a question on the CentBrowser forum ..

Sorry to take your time, all the best!**

**Comment by fastaddons** [comment]
No problem, I'm glad you found the solution.
Have a nice week :)
