### ISSUE TITLE
Cannot open local file from dial

### ISSUE THREAD

**Issue by maharvey** [fastaddons/GroupSpeedDial#36]
**Describe the bug**
I have HTML documentation on my local machine that I want to open with a dial. I can paste the URL into the browser and it opens file, but if I create a dial and click on it nothing happens, it is as if the dials is non-clickable. If I right click on the dial and copy the URL and paste it manually into the browser, it opens.

**Steps To Reproduce**
1. Create or copy an HTML file to your local filesystem. Verify you can open it in a browser.
2. Create a dial with a link to the HTML file. (URL will be "file:///path/to/file.html")
3. See that the dial is non-responsive and doesn't open the page.

**Expected behavior**
Dial should open the link.

**Device info:**
 - operating system: Linux (Manjaro, up to date)
 - Browser and version: Firefox 86.0
 - GroupSpeedDial version: 15.5

**Additional info**
Nothing else.

**Comment by Ainson** [comment]
This first did not work for me until I tried to put them as separate inputs in about:config. Then it worked.

That is, you enter for example the first part capability.policy.policynames as a string, then localfilelinks without the quotes in the text box that comes up next to it.

Same for the last two lines of course:

capability.policy.localfilelinks.checkloaduri.enabled = "allAccess"
capability.policy.localfilelinks.sites = "moz-extension://UNIQUE_ID_OF_MY_ADDON_ON_YOUR_PC"
