### ISSUE TITLE
All of a sudden.. edit dial brings up a distorted interface

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/GroupSpeedDial#37]
All of a sudden.. edit dial brings up a distorted interface, everything enlarged. I reset Chrome but it is the same. In the mean time Firefox does not have this problem.
![Screen Snip](https://user-images.githubusercontent.com/25828460/110216196-b785ab80-7e7b-11eb-9740-ba2b3f7b2523.JPG)
Thanx!

_Originally posted by @paolpaul in https://github.com/fastaddons/GroupSpeedDial/issues/34#issuecomment-792000609_

**Comment by fastaddons** [comment]
Hello @paolpaul ,
For for future, please create new issue if the problem is not related to the specific issue.

Anyway - your Chrome window is extremely small. Did you changed resolution or scaling level for your monitor?
Or maybe you just applied zoom on the page? Check main menu (three dots icon) to see what is the zoom level for your dials page.

**Comment by fastaddons** [comment]
Hej @paolpaul, what value do you have in the Scale and layout in your windows?
(right click on your desktop and select "Display settings" and scroll down to this:
![Screenshot 2021-03-06 19 13 33](https://user-images.githubusercontent.com/55486931/110216582-267cf780-7eb0-11eb-9c10-74468765e20a.png)

**Comment by paolpaul** [comment]
I reset Windows 10, and reinstalled Chrome and it appears to be OK now.
thanx for yout quick attention.
For 25 years I have been messing around with graphic configurations, fonts
and such and it is no doubt y fult that it was messed up smile.

Thanx again Juraj..!

**Comment by fastaddons** [comment]
No problem!
I'm glad it's working now :).
