### ISSUE TITLE
Local files don't open on click only right click + new tab

### ISSUE THREAD

**Issue by Tiffys** [fastaddons/GroupSpeedDial#41]
**Describe the bug**
If you have a local file as a tab like for instance file:///C:/Users/Tiff/Pictures/Reference/WHR/WHR.htm then when you left click on the dial it will not open, no matter how many times you click it. Only right click + open in a new tab will open it.

**Steps To Reproduce**
- Set the URL of a dial as a webpage stored locally on your computer.
- Try to open it with left click.

**Expected behavior**
- URL opening as normal with left click as webpages hosted on the web.

**Device info:**
- operating system: Windows 10 Pro
- Browser and version: Chrome Version 86.0.4240.198 (Official Build) (64-bit)
- GroupSpeedDial version: 15.4

**Comment by Juraj-Masiar** [comment]
Hello,
You have to enable access to local files for my extension onthe the page: 
chrome://extensions

![Screenshot 2021-03-22 22 16 29](https://user-images.githubusercontent.com/6358971/112059679-6dc7e100-8b5c-11eb-8063-28a19ded1e96.png)
