### ISSUE TITLE
Can't launch the SD Dials after update

### ISSUE THREAD

**Issue by VladSimPit** [fastaddons/GroupSpeedDial#42]
Hello,
Here is my problem:  I have reinstalled my Linux Mint (previously saved and copied the all firefox addons settings as I usual did before), after firefox start and open the GSD  I got this:

//------------------------------------------------------------------------
Environment health-check error: Error
An unexpected error occurred

Error: An unexpected error occurred

Environment: Group Speed Dial 15.5; info: os: linux, arch: x86-64; name: Firefox, vendor: Mozilla, version: 87.0, buildID: 20210318103112;
Pixel ratio: 1
Running time: 4748 / 113691.175
Stats: NA - 
Runtime errors:
4/8/2021 10:41:26 PM:	 critical error!:
undefined
undefined
null
Data:{"message":"Exception while loading settings and database","data":{}}
c@moz-extension://25716b5f-b5dc-4036-9e9c-b487545eebf6/background/background_gsd.js:1:22097
t@moz-extension://25716b5f-b5dc-4036-9e9c-b487545eebf6/background/background_gsd.js:1:51401
@moz-extension://25716b5f-b5dc-4036-9e9c-b487545eebf6/background/background_gsd.js:1:84502

Version: 15.5; OS: {"os":"linux","arch":"x86-64"}; Browser: {"name":"Firefox","vendor":"Mozilla","version":"87.0","buildID":"20210318103112"};
//--------------------------------------------------------------------------------------------------

I have a lot dial pages/subpages, and now nothing... can you help?

**NOTE:** I have replaced the **xxxx.sqlite** file saved several months ago, and everything work, but this is very old backup.
Regards.

**Comment by fastaddons** [comment]
Hello,
This is a browser problem - the error you see is cause by Firefox not being able to load the database.
However, there is several backups that could help, one of them is in the Firefox Sync storage (or should be).
So all you need to do is check the History:
![history](https://user-images.githubusercontent.com/55486931/114095159-65daa180-98bd-11eb-9c46-3794e4239617.png)

It should be called "Automatic backup" and it may be a few days old. But it should be there.

**Comment by VladSimPit** [comment]
Hi, 
Thank you so much! I have recovered the 2-day version. 
The problem was, that with broken database file this menu has not been available, so I needed to manually place an old backup file saved several months ago to see this menu.

Vlad

**Comment by fastaddons** [comment]
I'm glad to hear that! :)
Yeah, when the main storage is broken, then nothing will be loaded. But that's a extremely rare, usually only IndexedDB database gets corrupted and for those cases the menu is still available.
To fix whole storage one would have to reinstall whole addon, but I'm pretty sure the Firefox Sync storage should survive even that.

Anyway, I'm happy it worked! 
I can go sleep with a good feeling now :)
Good night.
