### ISSUE TITLE
Home page lost + Import Dial disappered!

### ISSUE THREAD

**Issue by David1501** [fastaddons/GroupSpeedDial#43]
Hi,

not sure what it happened but clicking home icon don't do anything anymore...
So i found it out that in "preferences" "copy homepage link" is empty..
in Import/Backup the "import settings and dials" is gone (it completely disappeared) and in Firefox Home
"Custom URLs" is empty too.

Tried to reinstall Group Speed Dial but it doesn't fix if..

Any Suggestions?

THX very Much

David
![Screenshot from 2021-04-14 20-49-07](https://user-images.githubusercontent.com/24269618/114763260-e6d4e580-9d62-11eb-9f2e-50be06a6109a.png)
![Screenshot from 2021-04-14 20-48-48](https://user-images.githubusercontent.com/24269618/114763264-e76d7c00-9d62-11eb-8912-a1d77265c5cf.png)

**Comment by fastaddons** [comment]
Hello,
That looks like some serious error. Probably broken IndexedDB database engine.
Could you visit this storage test page:
https://firefox-storage-test.glitch.me/
(the test takes about 10 seconds and you should see "Storage is working." message)

If the test fails, then your database engine is broken and you will have to use Firefox Reset to fix it:
https://support.mozilla.org/kb/refresh-firefox-reset-add-ons-and-settings
Resetting profile will preserve your passwords, bookmarks and other important things (but not add-ons data, so make sure to export your addons data if possible).
Before resetting your profile I would suggest you to setup Firefox Sync. - this will backup the list of installed add-ons and after reset it will reinstall them.

**Comment by David1501** [comment]
> 
> 
> Hello,
> That looks like some serious error. Probably broken IndexedDB database engine.
> Could you visit this storage test page:
> https://firefox-storage-test.glitch.me/
> (the test takes about 10 seconds and you should see "Storage is working." message)
> 
> If the test fails, then your database engine is broken and you will have to use Firefox Reset to fix it:
> https://support.mozilla.org/kb/refresh-firefox-reset-add-ons-and-settings
> Resetting profile will preserve your passwords, bookmarks and other important things (but not add-ons data, so make sure to export your addons data if possible).
> Before resetting your profile I would suggest you to setup Firefox Sync. - this will backup the list of installed add-ons and after reset it will reinstall them.

Fixed! Thank You very much for the help!! 

David
