### ISSUE TITLE
How to show 5 * 8 speed dials instead of 3 * 4? Hide empty Speed dial frames?

### ISSUE THREAD

**Issue by tobwz** [fastaddons/GroupSpeedDial#44]
When I open a new tab then Group Speed dial shows currently 3 rows with 4 columns each of Speed dials.

How can I increase the number to 5 * 8 speed dials?

Is there a way to hide empty speed dial frames?

**Comment by tobwz** [comment]
Ok, it works.

One more related question:

Currently the speed dials pushed into the upper left corner.

Can I somehow center them in the mid?

**Comment by fastaddons** [comment]
Yes, in the "Edit group" window enable "Fixed" ratio, then your dials will be centered (by width / height, depending on number of rows / columns).
You can also increase padding around dials from the Options page.
