### ISSUE TITLE
How to hide/disable "Tab" bar with "Home group", Cloud and Menu circle button?

### ISSUE THREAD

**Issue by tobwz** [fastaddons/GroupSpeedDial#46]
I don't need multiple groups. Default "Home Group" will be sufficient.

So I want to hide the complete group tab bar at the top with "Home group" and "+" tab, cloud and menu circle button.

Whenever I need to change something in options I will use the Firefox toolbar button context menu.

How can I achieve this?

**Comment by fastaddons** [comment]
Well, from the "Options page / Groups" you can hide the whole top-bar. But the option to hide group list only is not there.
But you can do it with a custom CSS style - paste this line in the Options page / General / Custom CSS styles field:
```
#groups { display: none }
```
