### ISSUE TITLE
Option to prevent thumbnail updating when you edit link to the dial

### ISSUE THREAD

**Issue by terminatorOST** [fastaddons/GroupSpeedDial#50]
Most of my dials have "custom thumbnail from file", and when you edit the link even slightly it clears it straight away.

**Comment by fastaddons** [comment]
Good point. The thumbnail is set to regenerate when URL changes (what is ok for auto generated).
I will fix it in the next release.
For now you should be able to restore previous thumbnail from context menu / Advanced / Restore previous thumbnail.
Thank you for reporting this!

**Comment by terminatorOST** [comment]
Dammit, I didn't know about the restore option :)
I used to just search the image and crop it the way I need anew.
Thank you!
But yeah, it would be preferable if for custom ones to be kept.

Update: You right, it doesn't work for now.
But I'll be careful till the update to not lose anything ))

**Comment by fastaddons** [comment]
I'll fix it in the upcoming release, probably version 16.0. But it will take some time, there is many fixes and features I want to include in this release.

**Comment by terminatorOST** [comment]
That's OK. That's just a feature that would be nice to have, not something "addon-breaking" :)

**Comment by fastaddons** [comment]
I've just finished fixing this, it should work in the upcoming version 16.0.
I'm still working on some more fixes and features for this release so it may take a week or two to release it...
