### ISSUE TITLE
can't add more than 9 dials to a group (or maybe I'm just dumb?) 

### ISSUE THREAD

**Issue by hannahlynn2** [fastaddons/GroupSpeedDial#52]
**Describe the bug**
I just installed this extension on Firefox (fully updated) and i love it & the concept but I have a lot of things to save in one group. I can't scroll down for empty dial spaces, I tried to save the bookmark to an empty group and then move it through right click to my "books to catalog" group (the group that won't allow me to have more than 9 dials) but it won't go into the group. After 9 dials it won't allow me to move anything else into a group. The limit is 9. 

**Steps To Reproduce**
Adding dials, as usual, to my "books to catalog" group, going to add a 10th dial to the group, it won't allow me. and I tried it in other groups. Limit is nine. 

**Expected behavior**
To be able to add more than 9 dials per group. 

**Device info:**
 - operating system: Windows 10 upated
 - Browser and version: Firefox Version 88.0.1
 - GroupSpeedDial version: Most recent update as of 5-26-21

**Additional info**
Add any other info about the problem here.

![image](https://user-images.githubusercontent.com/84832393/119610423-362d1d80-bdc7-11eb-8f0b-65983df8fdb8.png)

when you look at the image, below the 9 dials, there's no space to scroll to add more or anyway to add more

**Comment by fastaddons** [comment]
Hello,
You need to change the current group dimensions - you can do this in the "Edit group" window - you can open it either from the main menu (upper right corner), or by right click on a group name / Edit group.
You can change the number of rows / columns there or you can make the group scrollable.

**Comment by hannahlynn2** [comment]
> 
> 
> Hello,
> You need to change the current group dimensions - you can do this in the "Edit group" window - you can open it either from the main menu (upper right corner), or by right click on a group name / Edit group.
> You can change the number of rows / columns there or you can make the group scrollable.

Thank you! That worked perfect for me. I just made the columns 3 and the rows like 400. 

Is there anyway, when adding a dial, so it to just add without going back to the homepage.
For instance, I'm on a webpage, I want to click the icon, select a group, and add the dial while staying on the webpage?

**Comment by fastaddons** [comment]
Yes, there is.
In Options page / Context menus, enable "Show list of groups in context menu for fast insert". Then when you right click in a web page, you can choose to what group to add it without opening the dials page. I think... I haven't used it in a while :)

**Comment by hannahlynn2** [comment]
Yes, thank you!
