### ISSUE TITLE
Right click problem

### ISSUE THREAD

**Issue by Ameseattle** [fastaddons/GroupSpeedDial#57]
When I right click on a dial it opens the dial in a new tab.  This just started today.  I am trying to get to the dial context menu to refresh thumbnails.  I have tried right clicking on a tab but that does absolutely nothing.  Is there another way to open the context menu?  Is there a way to refresh tabs without the context menu?  Thanks in advance!

**Comment by Ameseattle** [comment]
hmm... I just tried again... now it works perfectly!  This happened a few weeks ago and it resolved itself then as well... I wonder if it has to do with updates from you and firefox not being in synch?

**Comment by fastaddons** [comment]
Hello,
This is for sure not related to my addon. The context menu handling is very simple and stable technology used on many pages so browser updates won't break it.

In your case, if right-click was opening dial in a new tab, it means that left click was send after the right click. Maybe hardware issue with your mouse, or something in the operating system... Hard to say. If you can, try to switch mouse next time it happens to see if it's related.
