### ISSUE TITLE
Specified dial images contain flipped graphics

### ISSUE THREAD

**Issue by paulholder** [fastaddons/GroupSpeedDial#59]
I have a couple of dials that are supposed to use small images that I created.  They are showing, but they have a portion at the bottom that is a flipped upside down copy.  If I play with the other options (they're current set for "full width - top align" is Visual, so if I try "Centre (Contain)" or other options) they get really bizarre.

Picture here:  https://snipboard.io/dD03vU.jpg

**Comment by fastaddons** [comment]
Hello,
Yes, that's a new feature :)
The point is to fill up the empty space if the thumbnail is not big enough - for example when your window is not maximized or on the phone in vertical mode.
**Please give it a try... if you still don't like after few days, then disable it - in the Options page / Dials / "No image reflection".**

**Comment by paulholder** [comment]
OMG I hate it so much, but my tastes are not yours.  If people want something to fill it in, why not offer a simple background colour (per dial.)  In my case, I quite like the white and sized my graphics accordingly, and felt betrayed by this change--thus this bug report.  (Sorry about that, I did look for something in the settings, honest, but I guess I missed it.)

In any case, here is an image of how a couple of other of the layouts look... I think they're kinda strange choices, and look buggy, especially "cover" because it crops off my content in favour of the flipped graphic.

https://snipboard.io/JNrPji.jpg

Anyway, sorry to have wasted any of your time, I'll move on now...

**Comment by fastaddons** [comment]
Hello Paul,
It will be applied only for the "Full width" option, but I see it's broken in the preview (thanks for pointing this out!).
Anyway, it should look more like this:
![Screenshot 2021-08-04 18 11 29](https://user-images.githubusercontent.com/55486931/128216598-a3f63751-4632-4e9a-b089-d4a632eb468d.png)

And it should not be visible normally, only when window is resized into non-monitor-like size.
Anyway, thanks for the feedback! I really hope people won't hate it :).
Have a nice day!
