### ISSUE TITLE
Dial in new Tab: Automatic change to new tab doesn't work

### ISSUE THREAD

**Issue by Oldbac** [fastaddons/GroupSpeedDial#61]
My Situation: 
Lenovo M57 and M90
OS Linux Mint Mate 20.2 or 19.3 
Browser Firefox 90.0.2 64bit
Newest GroupSpeedDial

Problem:

Dials:
x Immer in neuem Tab öffnen:                           works
x Automatische Umschaltung auf neuen Tab:   **doesn't work since yesterday**

Thank you!

**Comment by fastaddons** [comment]
Hello,
Thank you for reporting!
I'm working on a fix, it will be finished in a few hours. More info here #60
