### ISSUE TITLE
Change in group opening by default

### ISSUE THREAD

**Issue by seacask** [fastaddons/GroupSpeedDial#64]
**Describe the bug**
GroupSpeedDial set as homepage  with 6 groups and goup#1 used to open by default. 
Since the upgrade to version16 group#2 now opens by default
Reinstalling version 15.7 restores the status quo and group#1 opens by default again which is what I desire

**Device info:**
 Operating System is Windows 7
Browser is Firefox  version 90.02
GroupSpeedDial version 15.7  for reasons as stated above
**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
Hello,
I'm unable to reproduce it :(
Does it happen every time? Or is it consistently always the wrong group?

This is how it should work:
If you copy homepage link from the Options page and paste it in Firefox settings / Home / Homepage, then when you open your homepage, the first group should be selected.
The homepage URL should look something like this:
moz-extension://219d66d7-7408-4cda-84f1-eb857e952f9e/dial.html

If you want non-first group to be selected first, you can append "#x" where "x" is group ID. For example:
moz-extension://219d66d7-7408-4cda-84f1-eb857e952f9e/dial.html#15

This can be "somehow" affected by using "Remember last opened group" setting in the Options page / Groups tab.

**Comment by seacask** [comment]
Hello and thanks for the quick reply
It would seem that the version 16 upgrade had changed the firefox homepage  extension to #2

I changed this back to #1 and reset the homepage to this setting and it seems to have cured the problem
 many thanks
Peter

**Comment by fastaddons** [comment]
Well, that is strange... something else must be wrong, addons cannot change URL in the Firefox settings. Also I don't remember changing code related to group navigation in this release, but I did changed a lot of code so it's possible.
Anyway, I'm happy it works now :), hopefully it won't break again.
Have a nice weekend :)
