### ISSUE TITLE
Incorrect search results while search dials by dial title

### ISSUE THREAD

**Issue by heytex** [fastaddons/GroupSpeedDial#67]
**Describe the bug**
While search by dial title it always shows incorrect results. 
I have 1766 dials in 58 groups and it always shows 280~320 unrelated results varies by keyword while typing.  
It used to be correct. Not sure which version started broken.

**Steps To Reproduce**
1. open search speed dials.
2. toggle second box (search by title) and type in keyword.
3. incremental results are wrong as well as the final results.

**Expected behavior**
Correct searching results.

**Device info:**
 - operating system: Mac OS Big Sur 11.5.1
 - Browser and version: Both Edge Dev 94.0.975.1 and Chrome 92.0.4515.131 have same issue.
 - GroupSpeedDial version: 16.2

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
What the hell :D.
I've just tested it and indeed I'm getting crazy random results. It seems that some dials will be part of the result-set no matter what.

And I've released new version just yesterday :(.
I will look into it now and if I can fix it, I will release 16.4 hotfix right away.
Thanks for reporting!

**Comment by fastaddons** [comment]
Fixed in 16.4.
Firefox version is released, Chrome / Safari versions are being reviewed.
Thanks again for reporting this!

**Comment by heytex** [comment]
That's fast.. thanks for the rapid response and this must-have addon. 👍
