### ISSUE TITLE
Perpetual scrolling through Groups

### ISSUE THREAD

**Issue by Coreyartus** [fastaddons/GroupSpeedDial#75]
I am on Firefox and Chrome for Mac.  I scroll over any of the windows in any of the groups or tabs above, and it starts a cascading perpetual scroll through all groups in descending order until sliding the mouse off the active window, at which point it stops.

I have restarted my computer, quit the browser, even turned off my mouse.  Nothing helps.

I am unable to click on any of the windows in order to activate the link as the scrolling prevents any clicking of the selection.

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: Mac OS 11.6
 - Browser and version: Firefox version 92.01, Chrome 94.0.4606.71
 - GroupSpeedDial version: 16.6

**Additional info*
It seems that when the "Scroll through Groups" button is active, it automatically scrolls when the mouse is hovering over the window.  Clicking that button off prevents the perpetual scrolling.

**Comment by fastaddons** [comment]
So, is the caused by the "Scroll through Groups" option?
But I'm still not sure I understand, you say it keeps scrolling even without you touching the mouse / touchpad?

**Comment by Coreyartus** [comment]
I figured it out.  It was my mouse.

I am SO SORRY if I caused you any frustration.  You do excellent work, Juraj, and I’m happy to support you on Patreon.  My sincerest apologies.

--Corey

From: Juraj Mäsiar ***@***.***>
Reply-To: fastaddons/GroupSpeedDial ***@***.***>
Date: Friday, October 1, 2021 at 11:52 PM
To: fastaddons/GroupSpeedDial ***@***.***>
Cc: Coreyartus ***@***.***>, Author ***@***.***>
Subject: Re: [fastaddons/GroupSpeedDial] Perpetual scrolling through Groups (#75)


So, is the caused by the "Scroll through Groups" option?
But I'm still not sure I understand, you say it keeps scrolling even without you touching the mouse / touchpad?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffastaddons%2FGroupSpeedDial%2Fissues%2F75%23issuecomment-932695859&data=04%7C01%7C%7Cb68df53700db4d9f1fc808d98571366f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687543552662473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BN%2FAFDTO4HPFqEOkALsX6Qabr4FcZgEhjJIXOOrD%2BdQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAV4EJYT7NFYB4TBDXU4SJ4TUE2T3DANCNFSM5FF3G6DQ&data=04%7C01%7C%7Cb68df53700db4d9f1fc808d98571366f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687543552662473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FDu%2BP9eQdIDdC918mCpgQpVAU8hsC4I9YVQQf%2BT0WE8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb68df53700db4d9f1fc808d98571366f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687543552672463%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6v1cSiosk6ox%2BmeBcUq5XI%2BrPvUXGbErRpxG2tFdkvk%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb68df53700db4d9f1fc808d98571366f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637687543552672463%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PR%2BfOoVjZCIG5Y5SIrb1qrJD%2F%2FHPT1zb4D4XB73KYK4%3D&reserved=0>.

**Comment by fastaddons** [comment]
No problem :)
Congrats to a new mouse then? :)
And have a nice weekend!
