### ISSUE TITLE
iOS/iPadOS  Safari support

### ISSUE THREAD

**Issue by NoFace3D** [fastaddons/GroupSpeedDial#76]
Please consider support for iOS/iPadOS Safari browser.
If not local, then cloud version would be sufficient to replace new tab page.
Thank you

**Comment by fastaddons** [comment]
Hello,
Don't worry, I'll do my best to release it for iOS devices. Hopefully things will work similarly to desktop Safari.
But I'm still waiting for my very first iPad tablet which is out of stock so it may take a few weeks.
The cloud page should work already as a workaround, although it's not perfect...

**Comment by Juraj-Masiar** [comment]
All my Safari extensions are now deprecated:
https://ko-fi.com/post/Im-done-developing-Safari-extensions-D1D3MYJPL
