### ISSUE TITLE
brave browser

### ISSUE THREAD

**Issue by bey0099** [fastaddons/GroupSpeedDial#80]
**Describe the bug**
thumbs not generating correctly.
The same thumbnail is generated to multiple dials - for example a thumbnail of a single website is partially loaded on 2 dials.
Also there some performance issues - very very slow

**Steps To Reproduce**
click on multiple dials on generate thumbnail. 

**Expected behavior**
each thumbnail with the image of their respective site url

**Device info:**
 - operating system: windows 11
 - Browser and version: Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)
 - GroupSpeedDial version: 16.6

**Additional info**
thanks for the excellent plugin

**Comment by fastaddons** [comment]
Thanks for reporting!
Do you have multiple monitors?
And do you have some DPI scaling enabled? If you don't know, then go to the dials page / main menu / Advanced / Send error logs - click it and in the modal window see the value on the second row, the "Pixel ratio: <some number>"

I will be releasing new version soon so I will try to fix this.

**Comment by bey0099** [comment]
Hello Juraj

First, thank you for you reply

I send you an image representing the error that I have encountered. There you can see the same website thumbnail (webpage preview) in different dials with different urls.
And also the logs you requested

I hope this helps you resolving the issue

Best regards

Rui Miguel

**Comment by fastaddons** [comment]
Thank you for the logs.
I think I found the problem. I will be releasing an upgrade probably today or tomorrow.

**Comment by fastaddons** [comment]
New version 16.7 has been released.
It should work now. If not, please reopen this issue.
Thank you for reporting and have a nice weekend :)
