### ISSUE TITLE
all tabs gone

### ISSUE THREAD

**Issue by kaeboom** [fastaddons/GroupSpeedDial#84]
**Describe the bug**
hi, since the last update i lost all my tabs. 
Now i have an empty interface I have try the restauration button and nothing
and i have tried to login with my account and it don't work too

**Device info:**
 - operating system: windows 11
 - Browser and version: firefox 94.0.2 (64 bits
 - GroupSpeedDial version: 16.8

**Additional info**
Add any other info about the problem here.

![Screen Shot 11-23-21 at 11 19 PM](https://user-images.githubusercontent.com/94936496/143138448-cb7eb6e9-1016-4ccd-a08c-4fb1b1cca004.PNG)

![Screen Shot 11-23-21 at 11 20 PM](https://user-images.githubusercontent.com/94936496/143138561-1f9e35b9-6dc7-4457-a1a5-04834948306e.PNG)

**Comment by fastaddons** [comment]
Could you please try to visit this storage test page?
https://firefox-storage-test.glitch.me/
(the test takes about 10 seconds and you should see "Storage is working." message)

Was the addon removed? Or just lost data? It sounds very strange.
Also, what about the History backups - from the bottom screenshot, what happens if you click through the items?

**Comment by kaeboom** [comment]
here is the result:
`
Overview:
Storage is working. This is your first visit or all storage was automatically cleared.
Specific Subsystem Statuses:

LocalStorage
    Good: Totally Working. (fullyOperational)
QuotaManager
    Good: Totally Working. (fullyOperational)
IndexedDB
    Good: Totally Working. (fullyOperational)
Cache API
    Good: Totally Working. (fullyOperational)

Debug Info:

{
  "v": 1,
  "curVersion": 94,
  "prevVersion": 0,
  "ls": {},
  "qm": {
    "lastWorkedIn": 94
  },
  "idb": {
    "persistentCreatedIn": 94,
    "persistentLastOpenedIn": 94,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 94,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 94
  }
}
`
the addon was not removed.there was just the upgrade.
when i clik on a backup there is nothing

**Comment by kaeboom** [comment]
here is when i try to login
![Screen Shot 11-23-21 at 11 37 PM](https://user-images.githubusercontent.com/94936496/143140149-a687ae24-5461-4bb2-a7fd-3cdfeef2e67e.PNG)

**Comment by fastaddons** [comment]
But you see the backup rows in the "History / backup" window, right?
Try to restart Firefox or even better, whole PC. That often helps with this random issues.
Don't reinstall it yet! Uninstalling will delete all data so let's try to save them first.

**Comment by kaeboom** [comment]
the think is i have also the addon on chrome on an older version and it work
![Screen Shot 11-23-21 at 11 39 PM](https://user-images.githubusercontent.com/94936496/143140361-b57b953a-b18e-4d7f-a8cb-2db6a588a01b.PNG)
![Screen Shot 11-23-21 at 11 40 PM](https://user-images.githubusercontent.com/94936496/143140366-376ed12d-4273-46bb-84af-0ef25950c682.PNG)

**Comment by kaeboom** [comment]
yes i have a list of backups
![Screen Shot 11-23-21 at 11 41 PM](https://user-images.githubusercontent.com/94936496/143140528-471bd2bf-ddde-44e7-a0d0-cd93ad0467b8.PNG)

**Comment by kaeboom** [comment]
the think is i have also the addon on chrome on an older version and it work
![Screen Shot 11-23-21 at 11 39 PM](https://user-images.githubusercontent.com/94936496/143140361-b57b953a-b18e-4d7f-a8cb-2db6a588a01b.PNG)
![Screen Shot 11-23-21 at 11 40 PM](https://user-images.githubusercontent.com/94936496/143140366-376ed12d-4273-46bb-84af-0ef25950c682.PNG)

**Comment by fastaddons** [comment]
Wait a second :), the "Speed Dial [FVD]" is a different addon made by a different person.
I've read the FVD had some privacy violations and was removed from Firefox today. Some shady stuff...

**Comment by kaeboom** [comment]
i am a noob

**Comment by kaeboom** [comment]
and i am going to buy you a coffe

**Comment by fastaddons** [comment]
:D, that's ok... 
BTW, my addon supports importing data from the FVD, if it's still running in Chrome:
https://www.youtube.com/watch?v=H2maRJ9gFKU

**Comment by fastaddons** [comment]
coffee would be great, it's almost midnight now and I have still so much work to do!

**Comment by kaeboom** [comment]
howsome!! i will do it now!!!

**Comment by kaeboom** [comment]
same here, i am in paris
