### ISSUE TITLE
Reflection feature only working on some groups

### ISSUE THREAD

**Issue by irishrow** [fastaddons/GroupSpeedDial#87]
I imported Firefox Add-on settings from newly-banned FVDspeeddial into GroupSpeedDial that I had already created before I found out I could retrieve and load the FVDdata.  Import worked well, reflection was set ON.
I wanted to see how GSD rendered NON-reflection feature, so I turned it OFF.
I liked it better on, so I turned it back ON. 

I expected all dials to be reflective, but they are not.  8 groups...1,3,and 7 are not rendered reflective.

I refreshed thumbnails several times.  All groups are set as: 5 column, fixed, 20, 16, scrollable.

**Device info:**
 - operating system:  Windows Pro 10 64-bit
 - Browser and version: Firefox 94.0.2 (64-bit)
 - GroupSpeedDial version: v16.8

**Additional info**
The three groups that are no longer reflective are probably ones that I visited while reflection was turned off.

**Comment by fastaddons** [comment]
Hello,
Actually, the reflection should be by default not visible if your window is maximized.
The thumbnail dimensions are calculated in a way that they will fill whole dial (plus few pixels) if your window is maximized - which is the most common state for most users.
The reflection is then visible only if you resize the window (like snapping it to a side of the screen).

However, the reflection can also appear if you change dimensions of the group, like adding more columns or removing rows or changing dials ratio (in Fixed mode). But reloading thumbnails should again re-generate thumbnails into correct dimensions.

If you want to force reflection into dials even when having maximized window, you can try to change the target resolution - in the Options page / Thumbnails / "Auto-reload target screen resolution" - change it to manual and lower the second value (maybe by 200px).

As you can see, the whole situation is pretty complicated :). I will have to introduce some new layouts to make things easier to setup.
