### ISSUE TITLE
Columns 10/11 Blank - no thumbnail **SOLVED

### ISSUE THREAD

**Issue by kwambono** [fastaddons/GroupSpeedDial#89]
** UPDATE - Please ignore: solved by selecting context menu > sort by / remove empty dials ***

-----

Hi - have this problem - anything over 8 columns shows as blank but makes the space. when mouseover the area where the thumbnail should be I see the highlight shadow of the thumbnail rectangle. Expecting: thumbnails to flow through column 10 before starting next row.
Thanks

**Comment by fastaddons** [comment]
Yeah, this is the "fixed layout". I'm gonna add a new "Dynamic layout" soon that will behave similarly to other popular addons.
