### ISSUE TITLE
Chrome doesn't send all cookies

### ISSUE THREAD

**Issue by pundoo** [fastaddons/GroupSpeedDial#9]
**Describe the bug**

This is kind of a weird bug. Not sure if its entirely related to this extension or chrome has some bug in itself.
So, I've recently came across a site called [trdr.io](https://www.trdr.io/console). For some reason when visiting this site from group dials, chrome doesn't send all cookies with the request _(which prevents a user to keep logged in)_. This only happens when visiting the site from saved dials, otherwise works as expected when visiting directly, so doesn't seem its an issue with the site itself.

**Steps To Reproduce**

1. Go to [trdr.io](https://www.trdr.io/console)
2. Create an account and sign in
3. Add `https://www.trdr.io/console` in group dials
3. Visit site from dials

**Expected behavior**

Send all cookies

**Device info:**
 - operating system: Windows 10 (v1909)
 - Browser and version: Chrome 81.0.4044.138
 - GroupSpeedDial version: 14.9

**Additional info**

You can verify this by opening the 'Network' tab in DevTools and inspecting the Cookie header in request. All other cookies get sent expect `sessionId` even though its present in cookie storage.

**Comment by pundoo** [comment]
Nevermind. Figured the cause!

It was due to.. `SameSite` attribute being set to `Strict` for 'sessionId' cookie. So was indeed an issue on their part.

**Comment by Juraj-Masiar** [comment]
Interesting, thanks for the info!
