### ISSUE TITLE
Using productivity mode, you can still access locked dials by using "scroll through groups"

### ISSUE THREAD

**Issue by Balint197** [fastaddons/GroupSpeedDial#90]
**Describe the bug**
When using productivity mode it is possible to access locked dials by scrolling. This is unintended behaviour.

**Steps To Reproduce**
* Activate productivity mode, and lock some dials
* Enable scroll through groups
* Scroll on the home group, and you'll be able to access the locked dials

**Expected behavior**
Locked dials get "scrolled over" and only enabled groups are accessible by any means. 

**Device info:**
 - operating system: Windows 10, Ubuntu
 - Browser and version: Firefox 94
 - GroupSpeedDial version: 16.9

**Comment by fastaddons** [comment]
Good catch! Thank you for reporting this, I will try to fix this in the next release.

**Comment by fastaddons** [comment]
Fixed in the upcoming release 17.0.
I have few more small things to fix but I think I will be able to release it tomorrow.
Thank you again for reporting bugs :)
