### ISSUE TITLE
I can't find my dials and groups anymore after a ff crash

### ISSUE THREAD

**Issue by paul22718** [fastaddons/GroupSpeedDial#93]
**Describe the bug**
Hello, I have the same problem like user "rwfoster2021". firefox browser crashed and now all dials are missing and GSD is starting from scratch. Where can I find my dials and groups respectively how can I recover my dials and groups, or they are lost for ever?

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system:  windows 8.1.
 - Browser and version:  firefox 95.0.b1
 - GroupSpeedDial version:  Firefox 95.0.b1

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
Hello Paul,
First, try to restart Firefox or whole PC, that often helps.
After that, check the history:
![_history](https://user-images.githubusercontent.com/55486931/144490040-3025951f-3cec-4d6c-b84c-3cc7bbdc23b0.png)

Additional questions:
- was addon removed? or only data disappeared?
- how long did it take to open Firefox? Was it slow?
- did you lost data in other addons?
- why do you have Firefox beta 95.0.b1?, current beta is already  95.0.b12
- when you say Firefox crashed - what exactly happened? Can you see the crash in the "about:crashes" page?
