### ISSUE TITLE
Dial Icons Not transferring from Firefox to Brave

### ISSUE THREAD

**Issue by gswilder** [fastaddons/GroupSpeedDial#97]
I setup all my groups, dials, custom thumbnails on Firefox. I have a cloud account and everythings seems synced.. also have done a backup and export with dials to be safe.

Now I am trying to setup on Chrome browser. Once I signed in, I got all my dials and links... but most of the dials are blank.. The dial links are all correct.. Just not all the dial images...

I have attached a photo below of the dials in Firefox (good), and Chrome (not good).

I do have a lot of dial logos from files..

How do I get all my custom dial logos back..

**Device info:**
 - MAC OS Monterey
 - Chrome and Firefox 
 - Latest version

**Additional info**
Add any other info about the problem here.
![Firefox](https://user-images.githubusercontent.com/46789963/145691261-3d040a77-c9a6-4067-8c76-002a5ae8e23e.jpeg)
![ChromeNew](https://user-images.githubusercontent.com/46789963/145691266-20655e7a-9bd7-4c5c-b50b-7f792692fb7f.jpeg)

**Comment by fastaddons** [comment]
Hello, I've replied to your email so let me just paste it here agai:

Thumbnails synchronization must be enabled on each device manually.

So open Options page / Thumbnails tab and check the first checkbox there ("enable thumbnails sync.").

The synchronization should start automatically, but if it doesn't, then click the "sync" label in the cloud icon on the dials page. That will for sure trigger it right now. Then do the same on the other device and it should be synced.

After that, the thumbnails should stay in sync.
